### ISSUE TITLE
MKS TFT32

### ISSUE THREAD

**Issue by medicshort87** [makerbase-mks/MKS-TFT#100]
Any reason why after firmware update it is stuck on the booting screen?

**Comment by seabassattitude** [comment]
I'm not sure if this is allowed or not, someone please let me know if it isn't. I'm including a link to a YouTube video that walked me through the firmware flashing and configuring process that fix this problem for me.

https://youtu.be/fmEB93af4o8

**Comment by MS1987** [comment]
1. You have updated the wrong version of firmware.
2. Accident happenned when you were updating.

**Comment by glucz** [comment]
I'm stuck on the booting screen too. I'm quite sure I updated the right version. How can I update again? it goes into the booting loop immediately when I power it on

**Comment by seabassattitude** [comment]
This is same problem that happened to me. I posted Youtube link above. I followed this procedure to configure and flash firmware. Once you get the firmware flashed correctly, it will load normally. If it continues to only show BOOTING, then you haven't done it right.  Follow procedure in video. Once you have correctly updated firmware, this thing is plug and play. I really like this interface over the scroll knob printer came with.

**Comment by glucz** [comment]
Thanks. I saw that. The problem is that I was stuck on the booting screen. It was not updating the firmware even when I rebooted with the SD card that had the update. I ended up using a different SD card as suggested by someone else.

**Comment by seabassattitude** [comment]
I also switched SD cards. I hope you got it working now.

**Comment by dpatricio** [comment]
Switching cards didn't work for me. Has anybody found the bin to flash the bootloader? I guess that's the only option...
