### ISSUE TITLE
mks tft32 features not working

### ISSUE THREAD

**Issue by tritium01** [makerbase-mks/MKS-TFT#103]
ok so Just updated TFT. trying to use it for a cyclops setup in a mks v1.0 board. Can't get the screen to read temperature or features to work. Baud rate is correct and config settings are correct. Any idea?

**Comment by makerbase-mks** [comment]
Which version is not normal, do you use the old version?

**Comment by dudisr** [comment]
@tritium01 check it out the issue that i opened, its something similar. At this moment is not all functional but is on the go ..  take a look #110

**Comment by Andrei-Pozolotin** [comment]
See #285
