### ISSUE TITLE
z-breakfunction not working?

### ISSUE THREAD

**Issue by JONTY44** [makerbase-mks/MKS-TFT#107]
why z axis breakpoint function does not work in autobed leveling, i mean when i tap continew button from the tft, print will start from the same z perameters where it stops ,but the autobed leveling feature is getting off..thats why i m getting leveling issues..why is it so?

**Comment by gomines** [comment]
I’ve encounter the same problem in the “power off-resume” feature. 
Haven’t tried it, but i think activating the option on the motherboard’s firmware to save the grid on memory will make it load when you resume printing

**Comment by JONTY44** [comment]
thats right but there should be load command added on continue button on tft, otherwise evenif the grid stored in firmware memory, it will not load at restart, so the problem continues

**Comment by makerbase-mks** [comment]
@JONTY44  You need to preheat the printer. When the temperature reaches the target temperature, move the z-axis to the height you want to Continue. Click the "Continue" button.

**Comment by gomines** [comment]
Any update on how to load the grid when restarting a print? 
I tried using this commands on the starting scripts and using the "more" buttons but with no success.
M374: Save grid to /sd/cartesian.grid  
M375: Load the grid from /sd/cartesian.grid and enable compensation (NOTE you must home after this)  
M500: Saves the probe points

**Comment by JONTY44** [comment]
@makerbase-mks i know the continue button function, but what i m saying is that i m using autobed leveling feature and after pressing continue button the print will start but autobed leveling is getting off, so my print start on unlaveled bed, in other words my leveling points are not recovered.

suggestion:
i think u need to add M420 S1 GCODE command on top of continue button command so that  autobed level mesh is getting recovered before it continue from breakpoint. so that after continue button the print will follow autobed level mesh
