### ISSUE TITLE
MKS TFT28 Won't print

### ISSUE THREAD

**Issue by Bolino08C** [makerbase-mks/MKS-TFT#108]
Hello !
MKS TFT28 won't print with FW3.01 and Marlin 1.1.8, but everything else is ok.

**Comment by makerbase-mks** [comment]
what's the phenomenon of your printer,that's OK when I test the firmware of TFT32_v3.0.1 and Marlin 1.1.8 with delta machine.

**Comment by Bolino08C** [comment]
I can control all functions heating heads, bed, origin, read on sd/usb... But when I want to print, it doesn't pass anything , no heating and movements.

**Comment by Bolino08C** [comment]
I've found ! In Marlin firmware I've activated  ADVANCED_OK at section serial. Now I've unactivated this fonction it's Ok.
