### ISSUE TITLE
MKS PWC (Auto-Off) + SBase

### ISSUE THREAD

**Issue by gomines** [makerbase-mks/MKS-TFT#112]
Hi, i was wondering how to run the:  PWC module V1.0+MKS Sbase V1.3 (+smoothieware)+MKS tft32. (i undestand it works with Smoothieware too).

I've done the following connections: 
![coneccion](https://user-images.githubusercontent.com/35586270/36057698-87f482dc-0df0-11e8-983e-dbaf89b09f5a.png)
(Using the B4 pin on the TFT, not the B0 AND connecting the button with the sequence Blue(o)-Green(I)-Yellow(c))

and added the following lines to the smoothieware's config.txt file:
switch.psu.enable                            true             # turn atx on/off
switch.psu.input_on_command       M80              # Power On
switch.psu.input_off_command       M81              # Power Off
switch.psu.output_pin                     1.22             # Open drain, inverted to control an ATX PSON signal
switch.psu.output_type                   digital          # on/off only</code>

With all of this, the problem is: For as long as i press the button, the printer is ON. But when i let go of the button the printer turns OFF. I think the 1.22 pin does not send the right signal to the relay to keep the printer ON.

Any suggestions? Does this module really work with the Sbase?

**Comment by makerbase-mks** [comment]
switch.psu.enable                            true             # turn atx on/off
switch.psu.input_on_command                  M80              #
switch.psu.input_off_command                 M81              #
switch.psu.output_pin                        1.22          # open drain, inverted
switch.psu.output_type                       digital          # on/off only
switch.psu.failsafe_set_to                   0                # so the ATX turns off on a system crash
#switch.psu.ignore_on_halt                   false
switch.psu.startup_state             true

**Comment by gomines** [comment]
Still not working :( could it be the firmware? or a faulty relay?

**Comment by makerbase-mks** [comment]
Can you test whether P1.22 has output high level?

**Comment by gomines** [comment]
How can I test this? and can you explain a little more at which level it is supposed to be?

**Comment by makerbase-mks** [comment]
Do not release the button and use a voltmeter to measure whether the P1.22 pin outputs a high point

**Comment by makerbase-mks** [comment]
Do not release the button, use a voltmeter to measure P1.22 pin is high

**Comment by makerbase-mks** [comment]
Do not release the button, use a voltmeter to measure P1.22 pin is high

**Comment by KuroiSabato** [comment]
little question:
want to use bigger  push button (19mm), but it is a 24volts.
if i connect it to the 24v power supplier, should it work? Or I do need a 240v button and connect it to the pwc as the diagram?

**Comment by makerbase-mks** [comment]
It is able to work properly
This is the pwc_v2.0 wiring diagram：
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT2.8-3.2/MKS%20TFT28%2032%20V3.0%20datasheet.pdf

**Comment by zheka1980** [comment]
I try to connect MKS TFT35 and MKS PWC 2.0
 have found instrution - PB4 - is auto power off (right upper onnector on PWC), and PB0 - is power detection (right down onnector on PWC). I have connected, how it written. When ON button pressed - printer works. When I press button agait to make printer OFF - printer was ON still, without any reaction. It not catching POWER LOSS signal.

 I tried to change connection - if I connect PB4 to VCC - I see on display "closing machine". But on PB0 - still +5v. AND MKS PWC not take off power. I think than some ouptup pin on MKS TFT32 must go to logic "0" after power loss and appearing "closing machine" after POWER LOSS ?

 Anybody have MKS TFT35 and MKS PWC?

**Comment by zheka1980** [comment]
And I tried to add to config text 

switch.psu.enable true # turn atx on/off
 switch.psu.input_on_command M80 #
 switch.psu.input_off_command M81 #
 switch.psu.output_pin 1.22 # open drain, inverted
 switch.psu.output_type digital # on/off only
 switch.psu.failsafe_set_to 0 # so the ATX turns off on a system crash
 #switch.psu.ignore_on_halt false
 switch.psu.startup_state true

But p1.22 is always ON.

**Comment by gomines** [comment]
Hi, i started this issue cause i couldn't make my PWC work, had the same problem as you mention. Had the connections as i wrote before and did everything as the manual did, even looked everywhere on the internet (also saw some russian posts) and after all of that my pwc still didn't work!

Changed my Sbase to an Gen v1.4 cause i wanted to use different drivers. In this case using marlin i was confident that the PWC would work after reading issue #59 and again, my PWC didn't work.

Don't know if the module has an issue or what, but i'll show you an alternative and is what i'm currently using on my 3D printer: the Arduino module Relay. This module is very easy to connect and started working from my first try.
![image](https://user-images.githubusercontent.com/35586270/42175718-cbd5f5f4-7dfc-11e8-9d94-f1cdf417480e.png)


I know this ain't a solution to make your PWC work, but sincerely i've given up on this module to work and there ain't further information about it. I'll leave you with the information for connections on the Arduino Relay module that i used:
http://3dtoday.ru/blogs/sergey1232/modernization-of-power-supply-flyingbear-p902-automatic-turnoff-after-/

**Comment by gomines** [comment]
After working with this module, i was thinking if having the push button connected to all 3 cables: Common, NO (normally open) and NC (normally closed) should have something to do with the problem... since in this arduino module you only need to have C and NO to make it work.

**Comment by nip2k2** [comment]
Hi,
I have MKS TFT32 + MKS GEN v1.4 and MKS PWC with Marlin. Really dont know how to make it work...
- I´ve connect like the diagram.
- I´ve make modificacations on mks_config.txt
- I´ve make modificacations on configuration.h and pins.RAMPS.h (Marlin).

Very frustrating!
Printer power goes off if I release power button...
Makerbase-mks any solution?
Thanks.

**Comment by gomines** [comment]
Hi nip2k2, i was in the same spot as you. It really is frustrating since i too followed all the instructions with no success. Can't give you any solution but to try using the Arduino Relay module instead or as you can read in my other comments, try not connecting all 3 wires from the push buttom C, NO and NC (haven't tried this, just some thoughts of what the problem could be). 
Hope someone can give a solution to this problem and that you can make it work!

**Comment by nip2k2** [comment]
Hi!! I´ve try everithing including not connecting all 3 wires from the push buttom, I think its a problem with the button.... unbelievable, cant make it work!
Makerbase-mks??????
Please!

**Comment by hermitcrabslab** [comment]
OK so with Marlin 2.0.x bugfix is working, all I did is to change PS_ON_PIN   to P1_22 in Marlin/src/pins/pins_MKS_SBASE.h
On smothiee it power up but does not shutdown, I have the message on screen and I have to remove the P1_22 wire to full shutdown here is my part of config:

#Power supply control
switch.psu.enable                            true             # turn atx on/off
switch.psu.input_on_command                  M80              #
switch.psu.input_off_command                 M81              #
switch.psu.output_pin                        1.22             # open drain, inverted
switch.psu.output_type                       digital          # on/off only
switch.psu.failsafe_set_to                   0                # so the ATX turns off on a system crash
#switch.psu.ignore_on_halt                   true             # so the ATX does not turn off on a HALT condition (like limit trigger)
                                                              # However leave commented or set to false if you want the ATX to turn off for an over heat fault condition
switch.psu.startup_state                     true

Any idea what is missing/wrong to have full shutdown feature with smoothie?

**Comment by yummyburger** [comment]
hi, i have same issue but i have tft35 and my connection is different.

I connect the power detection and auto off from pwc directly to tft35. it can be turn on but cannot turn off

![htb1h_evcxsybunjssphq6zgvvxap](https://user-images.githubusercontent.com/20485407/44800700-a348ff80-abe9-11e8-87b9-4cfb7ed6a842.jpg)

**Comment by coolt5** [comment]
A good news to everyone use MKS Gen L 1.4 with MKS TFT and MKS PWC v2
i mange to solve it .
it was the wiring from the bored MKS (PWC v2) to (MKS Gen L 1.4) the red(vvs) and black(Ground) was revers . so just swap them and it will work.
