### ISSUE TITLE
SD Upload

### ISSUE THREAD

**Issue by vader333** [makerbase-mks/MKS-TFT#113]
I'm using an MKS TFT 28 with MKS wifi. I can't use Wifi to upload to SD Card. Repetier host gives the error: no firmware response detected for sd card action. Pronterface is stuck at sending line 24. How can I fix this problem? My MKS wifi is configured as Access Point (AP).

**Comment by makerbase-mks** [comment]
The function of SD Upload is upload to main board SD card.

**Comment by iprepiprep** [comment]
Hi makerbase-mks,
could you please explain. Using repeater-host we can access the SD card inserted into MKS-TFT
- mount SD - works fine
- unmount SD - works fine
- listing SD content - works fine (see picture attached)

 Why upload does not work?


![repeater](https://user-images.githubusercontent.com/37359522/37385195-3bbfdf7c-2710-11e8-975e-67b880a2158c.png)

**Comment by OversizedWizard** [comment]
Exact same issue. Also USB port don't see anything at all

**Comment by odudex** [comment]
In both Pronterface and Repetier Host the SD Card upload stops at 84% and freezes. It does not delete gcode files too.

**Comment by Paragaz** [comment]
Same problem here.

**Comment by mcsultan** [comment]
tft35. same here, please find a solition.

**Comment by furymountain** [comment]
Probably a dead thread, but for me when using Upload to SD card it starts to print over the connected port. It doesn't upload the file at all.

**Comment by makerbase-mks** [comment]
To implement the function of transmitting gcode file, you need to install the MKS plugin with use MKS TFT.
