### ISSUE TITLE
Disable "beep" on startup

### ISSUE THREAD

**Issue by dell9** [makerbase-mks/MKS-TFT#116]
Hello! 

Unable to find possibility to disable "BEEP" sound on powering up. Screen model in TFT32, the latest firmware is used. 

Is it possible to remove this beep?

**Comment by makerbase-mks** [comment]
You can remove the beep on the hardware.

**Comment by dell9** [comment]
Ok, thank you. Will desolder beeper. But this is not good option since beeper can be useful for endusers as filament ending or power lost indicator...

**Comment by ozayturay** [comment]
The "booting . . ." text and the buzz is irritating and the "You can remove the beep on the hardware." is not a real solution. I guess i'll sell my tft32 and use a 128x64 graphic lcd instead. Shame on you MakerBase. :(

**Comment by Evg33** [comment]
You can adjust the volume by M3 bolt in hole.
