### ISSUE TITLE
MKS Wifi

### ISSUE THREAD

**Issue by Thailoz** [makerbase-mks/MKS-TFT#118]
Hi i can connect via proterface but when i send a command i get no response ive also tried with repetier host and gett a timeout error
i have a TFT32 v3.01 firm ware and an mks sbase v1,3

any ideas ?

**Comment by Thailoz** [comment]
Ok done some more testing if I connect directly to the mks sbase board Wi-Fi works fine gets correct response from commands in prontaface. 
If I connect wife through the TFT I get no response to commands sent I have checked baudrates are the same

**Comment by makerbase-mks** [comment]
Mks_clound APP also can not use TFT WIFI?

**Comment by Thailoz** [comment]
I will test that tomorrow please supply an up to date link for the app

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-APP

**Comment by OversizedWizard** [comment]
Works until I disconnect Wi-Fi. Reconnect and I cannot control printer while it's printing or get any status. From Any app. Tft28 ramps 1.4 makerbase wifi
