### ISSUE TITLE
No printing MKS TFT 32 v3.01 Marlin

### ISSUE THREAD

**Issue by tsmaa** [makerbase-mks/MKS-TFT#119]
My equipment:
Creality v2.0 motherboard + MKS-TFT32 V3.01 + MKS Wifi + LCD12864 + 3d-Touch

Micro-sd 32gb format fat32 and micro-sd 64kb fat32 tested.

My firmware:
Marlin 1.1.8

All features like move, preheat, wifi access,extrude from mkscloud and pronterface are functionning OK at 115200 baud rate but a big issue discovered on print function !

When trying to print a gcode file from MKS TFT32 SD slot, after selecting & confirming the file, the screen continously increments time lapse but not printing occured after waiting a period of 20 minutes and more, no print. I can stop (cancel) the printing process at any moment. It seems like no gcode was sent  (uploaded) to printer from mks tft32 and there is no preheat settings (from gcode) that were occured and run. All tested gcode files were printed with success from LCD12864 SD slot and from Pronterface via USB serial baudrate 115200.

This issue (print a file) made the MKS TFT32 useless. I'm waiting for your solution after-sale ou support.

**Comment by makerbase-mks** [comment]
I need your gcode file to test.

**Comment by tsmaa** [comment]
gcode file sent to your mailbox.
Please, check it


[test_for_issue_119 github.zip](https://github.com/makerbase-mks/MKS-TFT/files/1796762/test_for_issue_119.github.zip)

**Comment by tsmaa** [comment]
[test_for_issue_119 github.zip](https://github.com/makerbase-mks/MKS-TFT/files/1796764/test_for_issue_119.github.zip)
Hi,


here is one gcode for testing MKS TFT-32


I recall: If printing from pronterface or from lcd12864, the 3dprinting is successful completed. BUt, no printing from TFT-32 v3.01



-----Original Message-----

**Comment by makerbase-mks** [comment]
I test it is ok with TFT32_v3.0.1 and Marlin 1.1.8.I think you need send me Marlin firmware.

**Comment by tsmaa** [comment]
No printing MKS TFT 32 v3.01 Marlin #119

My setup:
Creality CR-10 mainboard v2.0 300x300x400
3d-touch
MKS TFT32 v3.01
MKS TFT WIFI ESP8266 snap-in version (without cable)
LCD12864
Filament runout sensor

All versions up to dated March 15,2018
My custom files compiled with github Marlin 1.1.8 dated February 10,2018

When trying to print a gcode from MKS TFT32 microSD , no heating, no fan phases started. I can only hit Option, stop icons.

When i hit stop icon, the printer stopped normally.

Problems: no gcode was sent to Marlin or MKS TFT32 firmware wait for an acknowledge (ACK ?)

Pictures and setup files included for help debug for Marlin 1.1.8
[Marlin 1.1.8 CREALITY CR-10S V2.0.zip](https://github.com/makerbase-mks/MKS-TFT/files/1814149/Marlin.1.1.8.CREALITY.CR-10S.V2.0.zip)

**Comment by makerbase-mks** [comment]
I test your gcode file is ok with the marlin 1.1.8 and tft32_v3.0.1.The mainboard is MKS_Gen_L V1.0
[https://github.com/makerbase-mks/Marlin/blob/master/Marlin-1.1.8(original).zip](url)

**Comment by makerbase-mks** [comment]
I test your gcode file is ok with the marlin 1.1.8 and tft32_v3.0.1.The mainboard is MKS_Gen_L V1.0
[Marlin 1.1.8](https://github.com/makerbase-mks/Marlin/blob/master/Marlin-1.1.8(original).zip)

**Comment by tsmaa** [comment]
I do not own the MKS_GEN_V1.0 mainboard.
I'm an owner of Creality V2.0 mainboard shipped with CR-10S.
I recall my setup with Marlin 1.1.8 bugfix, serial baudrate115200:
Creality v2.0 motherboard + MKS-TFT32 V3.01 + MKS Wifi + LCD12864 + 3d-Touch

May you send a debugging output version of the firmware of MKS-TFT32 which can output logs-traces messages. Then, i will send you back the logs file captured from prontoface.

Or, you make testings compatibility with Creality V2.0 mainboard.
It's up to you 

Last option is to publish the source code MKS-tft32 v3.01

**Comment by tsmaa** [comment]
One more remark: your [Marlin 1.1.8](https://github.com/makerbase-mks/Marlin/blob/master/Marlin-1.1.8(original).zip) is not the last version available on github https://github.com/MarlinFirmware/Marlin/tree/bugfix-1.1.x

Question: How do you explain that all features of MKS-TFT32 V3.01 are functional but the printing function hang indefinitely ?

**Comment by tsmaa** [comment]
Start printing failed with marlin 1.1.8 firmware: after confirmation of selected gcode file from microsd, no processing to print. Definitely no compatibility of MKS TFT32 3.01 and marlin 1.1.8 + Creality CR-10 v2.0 mainboard.

Checked many times with gcode files: no success.

When will you fix this bug ?

**Comment by makerbase-mks** [comment]
You can replace it with a small SD card.

**Comment by tsmaa** [comment]
NO SUCCESS: already checked with many capacity of sd card: 8 GB, 16gb, 32GB of brand Sandisk, Kingston, Transcend. If i used these cards from a LCD12864, the printing function is completed successfully but NOT from MKS TFT32 v3.01 !!!

MKS TFT32 v3.01 is definitely buggy when i confirm printing any gcode file !

**Comment by makerbase-mks** [comment]
I test your gcode file is ok with the Marlin_1.1.8_bugfix_1.1.x and tft32_v3.0.1.The mainboard is Creality V_2.1
[Marlin_1.1.8_bugfix_1.1.x](https://github.com/makerbase-mks/Marlin/blob/master/Marlin-bugfix-1.1.x(20180120).rar)

**Comment by BlackWolf57** [comment]
Same for me.
The only way is to set TFT at 250000 baud and it work.
But if you are on Linux like me 250000 baud seems don't work on USB serial and you should make a choice.

Not tested with baudrate lower than 115200

**Comment by tsmaa** [comment]
Thank you BlackWolf57 for your suggestion.

I confirm that at 250000 baudrate, the 3dprint from TFT32 SD support succeded. Eureka !
But there is a drawback: Pause/resume printing loops occured  randomly (message: checksum error and resend line number xxxx) if Printrun (Prontoface) is connected on port com3 at same time.

So, there is still a bug with MKS TFT32 printing process with low baudrates. Normally, lower baudrates must be more accurate and stable but not with this firmware. Serial conflict ?

**Comment by lifeandfun** [comment]
Same for me,too

I have tested my MKS TFT24 v1.0 at 250000 baudrate already but nothing happen , my 3d printer still not receive gcode form SD card.

Because MKS TFT24 English firmware was deleted, so i try to replace it with MKS TFT28/32 English firmware. Manual control is ok, but can not print with SD card. Maybe this is the reason.

Please share me MKS TFT24 English firmware. Thank you so much.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.4
