### ISSUE TITLE
Status screen all messed up on TFT32

### ISSUE THREAD

**Issue by Bigfellas** [makerbase-mks/MKS-TFT#12]
I am running an MKS TFT32 The status screen is not displaying properly. All other menus and buttons are fine. Any thoughts. see picture
https://1drv.ms/i/s!AgFOUJh3Fjh1gqQUE5e9Aa_heQHJag

**Comment by makerbase-mks** [comment]
sorry,i can't see the picture.
can you send email to king@makerbase.com.cn

**Comment by Bigfellas** [comment]
Thanks. I have sent that to your email.

**Comment by pmbroth** [comment]
I had that happen as well, switch to the retro firmware, you wont have that happen,  I forgot which one it was either simple or the other one, I cant remember the third one.  But I know 2 our of the three works, and Retro definitively worked.

**Comment by Bigfellas** [comment]
Thank you

**Comment by makerbase-mks** [comment]
Hello,is your MKS TFT V1.0 version? This theme just can be used above V 1.1 version.

**Comment by Bigfellas** [comment]
Yes it is a v1.0. So sad for me
