### ISSUE TITLE
Mks tft 

### ISSUE THREAD

**Issue by Thailoz** [makerbase-mks/MKS-TFT#121]
Hi Can I use both the MKS DET Power Outage Detection Module and the MKS PWC Controller Board at the same time on the TFT32 with the MKS Sbase board if so how do i connect them

**Comment by Thailoz** [comment]
Please advise as i am now wiring the printer

**Comment by makerbase-mks** [comment]
that can not use both the MKS DET and MKS PWC.

**Comment by makerbase-mks** [comment]
using the pb4 for the PWC and the pb0 for the 220det.

**Comment by Thailoz** [comment]
ok ty and do i need to add anything in the config file

**Comment by ksbhatt89** [comment]
Hi, Thailoz,

Did you get the solution?
