### ISSUE TITLE
MKS TFT offset Z

### ISSUE THREAD

**Issue by fredwait4it** [makerbase-mks/MKS-TFT#122]
hi, i just own a mks tft 2.4 screen and it works pretty fine but i have one problem : 
How do you change the Z offset by the screen ??
i often change my nozzle and i have to change the offset in order to have a good 1st layer

thank you for your help

**Comment by makerbase-mks** [comment]
The current firmware does not yet support.

**Comment by merinkumar** [comment]
but it be in future release for tft24/28/32 ?
