### ISSUE TITLE
dual filament sensor

### ISSUE THREAD

**Issue by KuroiSabato** [makerbase-mks/MKS-TFT#123]
have a tft 32. and base v1.3
using the pb4 for the PWC and the pb0 for the 220det.
How can I configure the pb1 and the pb5 for 2 filament sensors?
on the manual, is not clear hot to config a dual sensor...

can you help me?

**Comment by makerbase-mks** [comment]
The function of pb5 pin is close.

**Comment by KuroiSabato** [comment]
What does it mind? I can't have two sensors?

**Comment by KuroiSabato** [comment]
?

**Comment by makerbase-mks** [comment]
using the pb0 and pb1 for the filament sensors.Only three pins can be used.

**Comment by makerbase-mks** [comment]
you can connect two filament sensors to pb0.

**Comment by KuroiSabato** [comment]
ok. but doing so, i'll need to always have filament on both extruders... right?

**Comment by makerbase-mks** [comment]
yes.
