### ISSUE TITLE
Auto Leveling, How to save?

### ISSUE THREAD

**Issue by KuroiSabato** [makerbase-mks/MKS-TFT#124]
How to save an auto leveling procedure using the TFT32?
Normally, after the procedure, M500 should  be used to save, but, in the MKS_CONFIG there is no option for a M500 command.
So, how to do it?

notes: 
I don't want to connect the printer to the PC ;
I  don't want to create a "MORE" button, as it is a "nameless" and  has not a own logo.

**Comment by KuroiSabato** [comment]
????

**Comment by makerbase-mks** [comment]
>cfg_auto_leveling_cmd:G28;G29;M500;
