### ISSUE TITLE
MKS TFT32_L 3.0 updating issue

### ISSUE THREAD

**Issue by Yeti2137** [makerbase-mks/MKS-TFT#125]
Brand new tft32 will turn on and say the normal “booting...” message, but then the screen turns black after and nothing else happens. Also, when I try to update the firmware, it gets stuck at 100% and then gets stuck there as well.

**Comment by makerbase-mks** [comment]
what the version of tft?

**Comment by Yeti2137** [comment]
Firmware version 3.0.1 and hardware version 3.0

**Comment by makerbase-mks** [comment]
are you used the external SD-card slot?

**Comment by BSODOverride** [comment]
I'm having the same issue. I am using an SD card (2GB). Mine does not go to a black screen after the "booting..." message though. Mine sits at "booting...". It also goes to "100%", and sits there, during update. I have tried using different baud rates, firmware versions (English v3.0.1: red and blue, Win8 v3.0.1 English: classic, retro).

**Comment by makerbase-mks** [comment]
@YetiPaladin @BSODOverride  If you have this problem at the beginning of this product please contact sales

**Comment by BSODOverride** [comment]
I got it figured out. I needed to change SD cards. I tried using a 2GB SD as suggested by others, mine was a micro SD. I switched to a standard size SD card @ 32GB (way overkill, I know, its all I have lol), and it worked flawlessly. Also, the standard card I used only supports FAT, as opposed to FAT32 which is what i was being told was needed, yet it worked.
