### ISSUE TITLE
SIMPLE mode shows blank rectangle on the upper half of the screen

### ISSUE THREAD

**Issue by martind-n** [makerbase-mks/MKS-TFT#128]
Hi.

Trying SIMPLE mode for TFT32 firmware 3.0.1 and it shows a blank rectangle on the upper half of the screen. It used to work on firmware 3.0.0 so there has been a degrade here.

Regards,
Martin.-

**Comment by makerbase-mks** [comment]
what's style?red or blue?

**Comment by martind-n** [comment]
Hi.

Both of them actually.

**Comment by makerbase-mks** [comment]
I test it is ok.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT2.8-3.2/Firmware/TFT28%2032_V3.0.1_English.zip

**Comment by martind-n** [comment]
Lucky you...
Retested with the SW on your link and the white rectangle is there...
