### ISSUE TITLE
TFT35 Loses connection after power cycling 

### ISSUE THREAD

**Issue by Stretchster** [makerbase-mks/MKS-TFT#132]
Hi all, i have a weird issue. I purchased a TFT35 and updated the firmware. All works initially. When I reboot the unit or power cycle it seems the screen does not communicate anymore with the Gen L board. If i reload the firmware all is good again until i power down. Can someone please help? Much appreciated.

Thanks
Stretch

**Comment by makerbase-mks** [comment]
you need to update the firmware to V_1.0.1

**Comment by Stretchster** [comment]
Finally, it worked.
