### ISSUE TITLE
MKS TFT35 - Size for the booting logo and buttons

### ISSUE THREAD

**Issue by Timppa71** [makerbase-mks/MKS-TFT#133]
Hi.

I did not found any information what is the right size of the booting logo for MKS TFT35? Also, what is right size for button pictures? Can you share this information, please?
Is there datasheet for the product?

**Comment by makerbase-mks** [comment]
the button pictures size is 117*140 ,and logo is 480*320.

**Comment by Timppa71** [comment]
Hi.

Thanks for the info.

However, this is strange because I can make a custom buttons (with size 117x140px) for any other buttons except "More" buttons (bmp_morefunc1 to bmp_morefunc7)? They just don't show correctly. Only button picture which is shown correctly is "zoffset" button.

This is how "More" buttons are look like:
![20180514_180536](https://user-images.githubusercontent.com/38979937/40005951-e099cb0e-57a1-11e8-893e-d4ac047090ab.jpg)

 I have same problem with "Custom" button pictures also.

**Comment by makerbase-mks** [comment]
bmp_custom1.bin to bmp_custom6.bin

**Comment by Timppa71** [comment]
Yes, indeed. My bad.

Great support, thank you so much!
