### ISSUE TITLE
MKS-TFT35 More Button no. 7 not recognized

### ISSUE THREAD

**Issue by Timppa71** [makerbase-mks/MKS-TFT#134]
More button no.7 does not work. If I add any of gcode command under "moreitem_button7_cmd" it doesn´t recognized. If I swap gcode between buttons no.6 and no.7, the gcode will work (so there is nothing wrong in my gcode...)

How to fix this?

**Comment by Timppa71** [comment]
Any comments for this problem, please? Do you need more information to solve this?

**Comment by makerbase-mks** [comment]
Give me your config file.

**Comment by Timppa71** [comment]
Ok, you can find config file in attachment...

[mks_config - copy.txt](https://github.com/makerbase-mks/MKS-TFT/files/2090209/mks_config.-.copy.txt)
