### ISSUE TITLE
MKS tft28 V3.0 Ramps 1.4

### ISSUE THREAD

**Issue by merlin2105** [makerbase-mks/MKS-TFT#135]
Hello ,

I have my tft28 v.30 after instructions to my Ramps 1.4 connected, BAUDRATE set, it also starts, but I can not control my printer with it, no commands are sent, firmware tft is v3.0.1 and Marlin 1.18 which is wrong here , where can me help 

Thanks

**Comment by merlin2105** [comment]
The Mega 2560 was the Problem

**Comment by Edusuf** [comment]
Just change the comunication port on Marlin to port 2 and connect the TX and RX from the tft to the last 2 pins of aux 4 in ramps 1.4 and that should do the trick, worked for me

**Comment by Bimblis** [comment]
Hi.

What do you mean "The Mega 2560 was the problem"? What was the problem?
