### ISSUE TITLE
MKS support SLOW no reply

### ISSUE THREAD

**Issue by Stretchster** [makerbase-mks/MKS-TFT#137]
Why does it take so long to get back to people who are in need of help? I asked a question here 3 days ago and no answer. i also emailed direct 2 days ago amd still no reply. I cannot use my printer and need to know if i have a defective product so i can return to vendor before my time runs out.

**Comment by makerbase-mks** [comment]
What is your trouble?

**Comment by Stretchster** [comment]
The trouble is your support is very slow unfortunately. Almost 13 days for an answer. Hopefully you guys will change that.
