### ISSUE TITLE
Retro style user interface for MKS-TFT35

### ISSUE THREAD

**Issue by Timppa71** [makerbase-mks/MKS-TFT#140]
Hi.

Do you have any plans to add Retro style user interface (or something similar to this) for MKS-TFT35? Now there is only Classic- and Simple styles... I would like to see my machine extruder- and bed temperatures even in start-up screen (like TFT32).

**Comment by makerbase-mks** [comment]
Thanks your advise,we'll consider it.

**Comment by Timppa71** [comment]
Thanks, I will looking forward to it.

**Comment by Steve021171** [comment]
Well, I would love to have that as well. But  after more then two years without any results I'm not very confident we'll ever see that.
So... what is the status??

**Comment by mks-viva** [comment]
@Steve021171 
Hi! We recommend you to use MKS Robin Nano V2+MKS TS35 to support more style UI
