### ISSUE TITLE
message error problem

### ISSUE THREAD

**Issue by TiZYX** [makerbase-mks/MKS-TFT#142]
Hi,
i want to replace my mks mini12864lcd by a mks tft2.4 but after test, the tft doesn't display the différent error message like wrong temp....
and it doesn't display that the printing is stopped like all other lcd screen (like mini12864 ) does

also how display information like the offset (like position by the gcode M114)

thank you so much

**Comment by makerbase-mks** [comment]
Later releases will have an error message.
