### ISSUE TITLE
TFT24 fw 302 Russian language

### ISSUE THREAD

**Issue by LyaminSS** [makerbase-mks/MKS-TFT#144]
Russian language
the letter "Я" is displayed incorrectly
How to fix?

![image](https://user-images.githubusercontent.com/39009713/40002820-3a952f96-57ab-11e8-91af-1cc40bc804f4.png)
![image](https://user-images.githubusercontent.com/39009713/40002851-4eafbc12-57ab-11e8-92d8-9b5803700240.png)
![image](https://user-images.githubusercontent.com/39009713/40002860-51d13f42-57ab-11e8-82cf-faf94292f815.png)

**Comment by LyaminSS** [comment]
version 301 has this problem too

**Comment by LyaminSS** [comment]
that's how it will be correct
![image](https://user-images.githubusercontent.com/39009713/40003080-dcf19db0-57ab-11e8-8cea-82f194f8a2bd.png)

**Comment by makerbase-mks** [comment]
we'll fix the bug recently.

**Comment by LyaminSS** [comment]
I see new files on the server
I flashed display
The problem is not solved.

**Comment by LyaminSS** [comment]
![image](https://user-images.githubusercontent.com/39009713/46257189-2605f880-c4cf-11e8-8f28-a503eeb5bdc2.png)

**Comment by LyaminSS** [comment]
3.0.3 not fixed!
Give a solution!

**Comment by makerbase-mks** [comment]
We will update and resolve this issue soon.

**Comment by makerbase-mks** [comment]
We have modified it.

**Comment by LyaminSS** [comment]
Fine. I'll check it out.
I will write a review.

**Comment by LyaminSS** [comment]
![image](https://user-images.githubusercontent.com/39009713/48486154-86ad8280-e83c-11e8-9649-db6a59f6058e.png)
Thanks!
