### ISSUE TITLE
MKS SBase 1.3 + MKS TFT32 USB and SD printing just stops in the middle of a print

### ISSUE THREAD

**Issue by FloxRoxX** [makerbase-mks/MKS-TFT#145]
As mentioned in the topic:
Hardware: 
-MKS SBASE 1.3 with latest Smoothieware firmware
-MKS TFT32 with firmware 3.0.1
-Original cable used that came with the board
Slicer:
Simplify 3D

Problem: The print just stops in the middle of printing the first layers and will not continue from then on.

What can we do about this issue? I already consulted other issue threads but all i found was for marlin boards and not for smoothieware...

**Comment by makerbase-mks** [comment]
Have you tried to print your GCODE file with the host computer?

**Comment by makerbase-mks** [comment]
There may be static interference problems, you can try to use the serial cable and shielding.

**Comment by makerbase-mks** [comment]
There may be static interference problems, you can try to use the serial cable and shielding.

**Comment by dmaltsevQA** [comment]
Have the same mulfunction. I've been made very short cable betwin SBASE and TFT, set 9600 baud rate - doesn't help

**Comment by makerbase-mks** [comment]
@Mosfett1975 what is version of your TFT software?

**Comment by dmaltsevQA** [comment]
it's TFT32 v3.0.2
