### ISSUE TITLE
Feature Request: Filament width sensor

### ISSUE THREAD

**Issue by blackus3r** [makerbase-mks/MKS-TFT#148]
Is there any chance to display the current filament width value (M407) on the main screen?

**Comment by makerbase-mks** [comment]
not support.

**Comment by blackus3r** [comment]
Is it possible to implement this? 

I like your firmware, but I don't want to switch to another firmware only because of this missing feature.

**Comment by makerbase-mks** [comment]
OK , You can make a custom design for it.
King@makerbase.com.cn
