### ISSUE TITLE
Progress action for every 10% during printing ?

### ISSUE THREAD

**Issue by fred2088** [makerbase-mks/MKS-TFT#150]
is it possible to have Gcode command to controller board for every 10% of printing completed ?

Start Gcode,
10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100% Gcode 
Abort Gcode
Completion GCode 

sent to controller board, to control a progress status led ?

Thanks

**Comment by fred2088** [comment]
will add this function ?

**Comment by makerbase-mks** [comment]
The touch screen does not have this feature for the time being.
