### ISSUE TITLE
Flip screen upside down

### ISSUE THREAD

**Issue by Henry2501** [makerbase-mks/MKS-TFT#153]
Good Day. I have a MKS Robin board with TFT 3.2 screen. The way the machine is built i need to install the screen upside down in the machine due to the length of the flat cable only being 300mm. 

Is there a way to turn the screen 180Degrees in the config file or firmware. 

Urgently looking for help, i need this done on 6 machines.

**Comment by Timppa71** [comment]
Yes, you can do it inside "mks_config.txt" file. Scroll down and you can find the parameter almost at the end of file...

**Comment by Henry2501** [comment]
Hello Timppa71

Thank you for the reply. I posted this in the wrong section. I have a MKS
Robin Board that comes with a tft screen. It does not have that option in
the Robin Config files. Tried even the latest config 2.0.7.
I also Added the code
>cfg_OVERTURN_180:1 #The screen is flipped 180°(0: no flip, 1: flip)
to the Robin config file but did not work.

**Comment by makerbase-mks** [comment]
Do you use MKS TFT32_L or MKS Robin TFT?

**Comment by makerbase-mks** [comment]
The MKS Robin TFT have not function of screen overturn 180 .
