### ISSUE TITLE
tft28 white screen

### ISSUE THREAD

**Issue by robertotej** [makerbase-mks/MKS-TFT#155]
I have the screen tft28 v3 + MKS TFT-WIFI V1.0. Software version 3.0.1 and 3.0.2
If I only connect the screen: everything is perfect.
If I connect the wifi module to the screen, connect to the internet fast and well. But when it takes a few minutes to work, the screen turns white and the printer stops; I have to reset the screen to keep it running.
any solution?

**Comment by makerbase-mks** [comment]
Do you used HLK or ESP wifi modual?

**Comment by robertotej** [comment]
https://es.aliexpress.com/item/Latest-3D-Printer-Parts-MKS-TFT-WIFI-Module-Wireless-Smart-Controller-WiFi-APP-Module-for-Smoothieboard/32814332054.html?spm=a2g0s.9042311.0.0.4af563c0jclBuB
