### ISSUE TITLE
SOLVED TFT35: Error:Checksum required when switching back to ASCII protocol

### ISSUE THREAD

**Issue by Udo-Nbg** [makerbase-mks/MKS-TFT#157]
Hardware: 
   MKS TFT35
   MKS-Gen 1.4

Software/Firmware:
   Repetier 1.0.1 (Repetier-Firmware configuration tool for version 1.0.2)
   TFT35_V1.0.1_English

   I did NOT define a Display in the Repetier Firmware, because the display comunicates via serial.

Is there any Display to configure to make the tft working ?

Every time while Testing i got 
**Error:Checksum required when switching back to ASCII protocol.**
in Repetier Host and also on the TFT

Alwas when i send a command via Touchsreen (example): "Settings/Fan/100%" OR "Settings/Fan/0%"  OR any other commands

**What went wrong???**

@115200 ANSI 
@250000

GEN & TFT baudrate alsways change on both devices.

Force checksums once a checksum is received ist set

**Comment by makerbase-mks** [comment]
Do you selected 2 for this configuration:
>cfg_firmware_type:2

**Comment by Udo-Nbg** [comment]
## Of course,

i tried also older Marlin Firmware Version 0.92 or so.... but nothing better happen

also i reboot more than one time the controllers (board and tft).

maybe i have an other idea but i'm actually not at home so i can test in a vew days.





**Where can i find the complete user manual for the tft35**

and the software **mks-host** is onli with chinese letters, is ther a other **english version** available?

**Comment by Udo-Nbg** [comment]
## Problem probably solved,
Errors appear when concurrent access via the HOST software AND commands from TFT Dispay take place.

## Unfortunately, I can not find a data sheet or manual for the TFT35 yet.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT3.5%20Datasheet.pdf
