### ISSUE TITLE
MKS TFT 3.5 Datasheet

### ISSUE THREAD

**Issue by Operrr** [makerbase-mks/MKS-TFT#161]
Hello! Why did not you put the datasheet on this version? I'm very interested in the size of the icons for creating a custom interface.

**Comment by Jinxycob** [comment]
totally agree with Operrr above, am interested but cant find a shred of information ( like  a data sheet ) nor can I see it listed on ali makerbase store https://www.aliexpress.com/store/group/Smart-Display/1047297_502266038.html?spm=2114.12010611.0.0.123f1ed3PPjikr  leaves one wondering if its a genuine product!!

**Comment by Operrr** [comment]
Do the implementers generally visit this place? there are not many answers, all died?

**Comment by schmitzCatz** [comment]
they deleted the datasheets, unfortunately the TFT 3.5 never got uploaded. Maybe the TFT 28 can help you out: https://github.com/makerbase-mks/MKS-TFT/tree/600550aea78e47ddc3311697ec65cffbe52e51bf/MKS-TFT2.8-3.2

**Comment by makerbase-mks** [comment]
Due to our updated the datasheet recently, no instructions have been uploaded.
https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT3.5%20Datasheet.pdf

**Comment by Operrr** [comment]
Thank you

**Comment by Operrr** [comment]
Thank you! Where can I download the plug-in for the SURA slice?


>Среда, 11 июля 2018, 18:53 +08:00 от makerbase <notifications@github.com>:
>
>Из-за недавно обновленного технического описания никаких инструкций не было загружено. 
>https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT3.5%20Datasheet.pdf
>- 
>Вы получаете это, потому что вы создали тему. 
>Ответьте на это письмо прямо,  посмотрите на GitHub или  отключите тему .

**Comment by schmitzCatz** [comment]
any chance on releasing the source code for the modules?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Software/tree/master/MKS%20Plugin

**Comment by Operrr** [comment]
Thank you

**Comment by Operrr** [comment]
Hello! I apologize for persistence. The plug-in 3.X works in versions prior to 3.2.1. In newer versions, the plugin can not save the file. This is not critical, but I would like to use the latest version of the slicer.

**Comment by makerbase-mks** [comment]
@Operrr  We have updated the plugin:
https://github.com/makerbase-mks/Software/tree/master/MKS%20Plugin

**Comment by ivanhauptman** [comment]
Could you please tell me the difference between the MKS TFT 3.2 and 3.5?
And just the size?

**Comment by Operrr** [comment]
not only, 3.5 "can display a preview of the printed model

**Comment by kpdelucia** [comment]
Any instructions on how to install this plug in?  The readme file was blank in the repository
