### ISSUE TITLE
MKS TFT7.0 - Rotate Screen

### ISSUE THREAD

**Issue by gorbi87** [makerbase-mks/MKS-TFT#163]
Hi,
is it possible to Rotate the Screen by 90° to install the TFT vertical?

**Comment by makerbase-mks** [comment]
You need to custom designed for it .

**Comment by makerbase-mks** [comment]
King@makerbase.com.cn

**Comment by gorbi87** [comment]
How can i customize it? How can i change the Button Positions for example? The manual shows only how to change background, color etc.

**Comment by Andrei-Pozolotin** [comment]
See #285

**Comment by mahdieh-dev** [comment]
@Andrei-Pozolotin I checked that link, but it seems that it's just an introduce to the firmware and again no guide to change it.
I tried building the firmware with no changes in the code, the generated `.bin` file made my lcd stuck at `100% uploading`. I searched further and found out that it's got to be decoded with a simple tool dedicated for the `mks robin nano`. I used that and all the screen got mixed up, images got corrupted and the dimension of the graphics reduced to the size of `mks robin nano`. So I found out that it's ultimately useless for `mks tft 7.0` which is my lcd.
In this interval I have talked to many `mks tft` lcd buyers and understood that they have the same problem. Please some one help us how to make changes in the firmware and the most important, **provide a .bin decoder for mkstft70**. Please!! @makerbase-mks
