### ISSUE TITLE
Mks TFY 32 v4.0 

### ISSUE THREAD

**Issue by bogaskilop** [makerbase-mks/MKS-TFT#164]
On aliexpress there are some of version 4.0 screens but on your website and on github not.

No new datasheet or firmware ?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT28%2032%20Datasheet.pdf

https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.8-3.2
