### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by quichy3016** [makerbase-mks/MKS-TFT#166]
Hi, I make a request. Is there any way to create a variable and by means of the 13 buttons we can add or decrease a variable? is to set the offset from the same screen.

**Comment by BlackWolf57** [comment]
Owww yes, please...
Babystepping plus and minus commands with an easy access !

**Comment by quichy3016** [comment]
o add comand M306 for set off set Z.

**Comment by makerbase-mks** [comment]
TFT35 has this function of adjusting Z_offset

**Comment by nip2k2** [comment]
And TFT32 also have that function?

**Comment by makerbase-mks** [comment]
You need to custom designed for it .
