### ISSUE TITLE
tevo little monster TFT Problem all sideways

### ISSUE THREAD

**Issue by rothlive** [makerbase-mks/MKS-TFT#167]
Since I installed the update to version 3.0 from version 1.2 everything is wrong on the screen. Unless I'm using a version larger than 3.0.

But i need to use it with tevo Firmware and it gave no Version over 3.0

![utb8zab ghnjxkjksahgq6xhzfxay](https://user-images.githubusercontent.com/10054386/42245587-8dccdcbe-7f19-11e8-9cf6-1aa56699c06f.jpg)

**Comment by rothlive** [comment]
I have testet a little further.
Tevo Version based on Version 1.2 from 2016.

All versions below 3.0 have the error.
Also the versions of https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.8-3.2/History%20version

Hardware defect?
I dont know.
For it to work again, a new firmware would have to be created based on TFT28_32_v3.0.2 Release file.zip.

Or another hardware unfortunately.
I also do not understand why that is.
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.8-3.2

**Comment by rothlive** [comment]
Tevo send me a new Firmware and then it works fine !

**Comment by Prcrstndr** [comment]
> Tevo send me a new Firmware and then it works fine !

Hello, I'm having problems with the Tevo Little Monster, can you share your new firmware please?

**Comment by rothlive** [comment]
> 
> 
> > Tevo send me a new Firmware and then it works fine !
> 
> Hello, I'm having problems with the Tevo Little Monster, can you share your new firmware please?

yes
How can I get your e-mail address at Github?

**Comment by rothlive** [comment]
My e-mail address is on my side in the imprint.
https://rothlive.de/de/Impressum

**Comment by Prcrstndr** [comment]
> > > Tevo send me a new Firmware and then it works fine !
> > 
> > 
> > Hello, I'm having problems with the Tevo Little Monster, can you share your new firmware please?
> 
> yes
> How can I get your e-mail address at Github?

dgonzalez1013@cova.edu.mx
Thank you :)

**Comment by rothlive** [comment]
You have a Mail

**Comment by ducmphung** [comment]
Hey guys I am having the same issue. Would you mind sending a working version to me also please? duc@ducphung.com thanks in advance.

**Comment by rothlive** [comment]
Ok

 

Von: ducmphung <notifications@github.com> 
Gesendet: Dienstag, 26. März 2019 00:57
An: makerbase-mks/MKS-TFT <MKS-TFT@noreply.github.com>
Cc: rothlive <github@rothlive.de>; Comment <comment@noreply.github.com>
Betreff: Re: [makerbase-mks/MKS-TFT] tevo little monster TFT Problem all sideways (#167)

 

Hey guys I am having the same issue. Would you mind sending a working version to me also please? duc@ducphung.com <mailto:duc@ducphung.com>  thanks in advance.

**Comment by mzaczynski** [comment]
Hello guys, 
my TLM also have the same issue, could you share with me your working firmware please?
My email address at github is: mzaczynski@gmail.com

**Comment by mzaczynski** [comment]
Thanks in advance

**Comment by rothlive** [comment]
You have a Mail with the firmware.

> 
> 
> Hello guys,
> my TLM also have the same issue, could you share with me your working firmware please?
> My email address at github is: [mzaczynski@gmail.com](mailto:mzaczynski@gmail.com)

**Comment by myeoman101** [comment]
Hi I'm also having same issue, could you email me the firmware at myeoman@hotmail.com. Thanks

**Comment by bestia-io** [comment]
hi, same problem on my tlm. Care to share? jtravis.russett@gmail.com thanks!

**Comment by PterodacylDanceParty** [comment]
> You have a Mail with the firmware.
> 
> > Hello guys,
> > my TLM also have the same issue, could you share with me your working firmware please?
> > My email address at github is: [mzaczynski@gmail.com](mailto:mzaczynski@gmail.com)

Hello, could you please send the new firmware to robert.m.busic@gmail.com? I ran into this same issue

**Comment by rothlive** [comment]
Hello

 

Yes.

 

With best regards, Markus Roth from Germany.

 

Von: PterodacylDanceParty <notifications@github.com> 
Gesendet: Sonntag, 16. August 2020 00:13
An: makerbase-mks/MKS-TFT <MKS-TFT@noreply.github.com>
Cc: rothlive <github@rothlive.de>; Comment <comment@noreply.github.com>
Betreff: Re: [makerbase-mks/MKS-TFT] tevo little monster TFT Problem all sideways (#167)

 

You have a Mail with the firmware.

Hello guys,
my TLM also have the same issue, could you share with me your working firmware please?
My email address at github is: mzaczynski@gmail.com <mailto:mzaczynski@gmail.com> 

Hello, could you please send the new firmware to robert.m.busic@gmail.com <mailto:robert.m.busic@gmail.com> ? I ran into this same issue

**Comment by docman11** [comment]
Hi! Can u help me please with working firmware? Same problem... 
Thanks in advance.
My email: docman545@gmail.com

**Comment by PterodacylDanceParty** [comment]
> Hi! Can u help me please with working firmware? Same problem... Thanks in advance. My email: [docman545@gmail.com](mailto:docman545@gmail.com)

It never worked. I gave up and got rid of the machine. I think if I still had the machine I’d convert it to Klipper and just get some cheaper MKS board on Amazon.

**Comment by rothlive** [comment]
> Hi! Can u help me please with working firmware? Same problem... Thanks in advance. My email: [docman545@gmail.com](mailto:docman545@gmail.com)

I have sent them the firmware by e-mail. 

I no longer use the board myself and have switched to a Duet3d board.
