### ISSUE TITLE
filament change not working

### ISSUE THREAD

**Issue by mks67** [makerbase-mks/MKS-TFT#17]
filament change feature is not working correctly
once started extruder runs 3 meters of filament
changing the values in config.txt makes no difference

**Comment by makerbase-mks** [comment]
Hello, thanks for your feedback. I have tried to modify the parameters as followed which has nice effect on the printing. You can try it please.

#the speed of filament replacing(mm/min)
>cfg_filament_change_speed:300

#the length of filament replacing(mm)
>cfg_filament_change_step:1
