### ISSUE TITLE
Use both MKS PWC and MKS 220det

### ISSUE THREAD

**Issue by hermitcrabslab** [makerbase-mks/MKS-TFT#173]
How I can enable/use both?
I want to use the PWC for shutdown/power-up(confirmed working with marlin 2.0x bugfix firmware but not full working with smoothieware, only power up and not shutdown)
And MKS 220 detect for ups and power loss detection to put the printer on pause until power is up again.
How to do it?

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/44328547-6ae04d80-a494-11e8-973c-0c0478f3d345.png)

**Comment by hermitcrabslab** [comment]
I think you did not understand my question, I have both MKS PWC and MKS 220DET and I want to use both with MKS TFT32, problem is that in display configuration I can not enable both is ether MKS PWC or 220Det:

 #enable power detecting module(mks 220det:1; mks pwc:0)
cfg_insert_det_module:0 
I have UPS connected to printer and I want to pausde the print when there is a power loss and also use the power off functions like auto off after print finish function...

**Comment by ksbhatt89** [comment]
Hi hermitcrabslab,
I also have a same query and unfortunately I couldn't find the answer.
Could you get the solution?

**Comment by makerbase-mks** [comment]
There are no conflicts between implementing two functions at the same time. First, in terms of connection, mks 220 det connects to the PB0 port of the TFT, and pwm connects to the PB4 port of the TFT. Profile aspect
#enable power detection module(mks 220det:1; mks pwc:0)
> cfg_insert_det_module:1
Choose mks 220vdet
#enable auto off(no:0; Yes:1) after printing completion
> cfg_print_finish_close_Machine:1
Enable automatic shutdown

**Comment by hermitcrabslab** [comment]
@ksbhatt89 No, not yet

@makerbase-mks maybe I am dumb but I still cannot see how the display will send a pause to the printer when power runs out if is not configured, or you are saying that is not required to define it in config and once the PB0 pin is getting signal from mks 220det the display will send pause to the pinter?
I am right?

**Comment by ksbhatt89** [comment]
I am using ups with mks 220det. Where do I need to connect  mks pwc in the block diagram shown in attachement? It is to be connected to ups or direct supply?
![mks det_ups](https://user-images.githubusercontent.com/19921746/46947110-6f417500-d097-11e8-9da1-849d11afae6c.jpg)

**Comment by michail58** [comment]
здраствуйте форумчане у меня большая просьба нужна помощь связка mks tft 35 +sbase 1.3+mkc 220 det так вот в чем проблема до выключения питания печатает хорошо после выключения стол опускается Далее подаю питание на det 220 после подаю включение принтера голова хомится и приезжает к детали стол поднимается и пошла печать но филамент экструдер не выдавливает
куда копать уже не знаю перепробывал кажется все

**Comment by makerbase-mks** [comment]
@michail58 Under what circumstances did this happen, after the power outage? Generally, the recovery print is heated. Will the extrusion head block?

**Comment by LyaminSS** [comment]
> здраствуйте форумчане у меня большая просьба нужна помощь связка mks tft 35 +sbase 1.3+mkc 220 det так вот в чем проблема до выключения питания печатает хорошо после выключения стол опускается Далее подаю питание на det 220 после подаю включение принтера голова хомится и приезжает к детали стол поднимается и пошла печать но филамент экструдер не выдавливает
> куда копать уже не знаю перепробывал кажется все

Я так решил этот вопрос. Дешево, и сердито! Надежно
https://vk.com/@lyaminss-avtomaticheskoe-vykluchenie-3d-printera-po-zaversheniu-pecha

**Comment by michail58** [comment]
обьясняю ситуацию Ставлю печатать деталь Через некоторое время мне например на ночь нужно выключить принтер Снимаю питание с mks det 220 Принтер останавливается стол опускается на 10 мм Я выключаю принтер Через некоторое время включаю принтер снимаю с паузы идет нагрев стола и сопла После нагрева оси двигаются в ноль дальше головка движется к детали стол поднимается начинается печать  но пруток не выдавливается

**Comment by LyaminSS** [comment]
я пытался тоже печать возобновлять, и у меня она могла начаться на другой высоте, и сбить изделие. И я больше не стал экспериментировать. Мысль была, что я не верно файл конфигурации настроил.

**Comment by michail58** [comment]
а почему не включается экструдер

**Comment by michail58** [comment]
Вообще кто отвечает за паузу mks tft35 или sbase 1.3

**Comment by LyaminSS** [comment]
за паузу отвечает TFT. Он на карту памяти делает запись места остановки.
Печать может не начаться из-за того, что не прогрелся экструдер.
Попробуй сперва прогрев сделать головы, потом возобновить печать.
Чтобы все прошло нормально - карточку вынимай, потом прогревай.
выключай питание, вставляй карточку, и включай, возобновляй

**Comment by michail58** [comment]
У меня ура все заработало Только странно я перешел на другой слайсер и восстановление печати пошло После прогрева головка медленно подошла к детали и также медленно прошла внешнюю оболочку ну а дальше все как обычно

**Comment by MsnSazabi** [comment]
> @ksbhatt89 No, not yet
> 
> @makerbase-mks maybe I am dumb but I still cannot see how the display will send a pause to the printer when power runs out if is not configured, or you are saying that is not required to define it in config and once the PB0 pin is getting signal from mks 220det the display will send pause to the pinter?
> I am right?

Was you able to solve this issue?

**Comment by aokiakagome** [comment]
I made it like this.

https://youtu.be/az0qwhmqn3s

**Comment by hermitcrabslab** [comment]
> I made it like this.
> 
> https://youtu.be/az0qwhmqn3s
Like how? Even spent time to read your google translated blog with no clear picture in the end...

**Comment by aokiakagome** [comment]
Japanese translation is difficult.
sorry

I also have difficulty understanding the problem with translation.

![1577447759213](https://user-images.githubusercontent.com/58908991/71516875-c3c4bf00-28ee-11ea-9fbc-38d6f7de6d91.jpg)

What is the situation of the problem right now?

**Comment by hermitcrabslab** [comment]
A simple but compleat schematic would worth more then a thousand words...

**Comment by aokiakagome** [comment]
Wiring example

![2019-12-29-05-53-22-947_1](https://user-images.githubusercontent.com/58908991/71550454-cf5dd600-2a13-11ea-8ba8-a0ad1a4d826a.jpg)

Start printing
↓
Power loss
↓
Timer relay
Auto power off after 3 minutes
↓
Power on
↓
Printing resume
↓
End of printing
↓
Auto power off after 3 minutes
(Add to end Gcode→G4 S180)

**Comment by hermitcrabslab** [comment]
Very good, thanks\1
