### ISSUE TITLE
My first SkinPack for MKS TFT3.5

### ISSUE THREAD

**Issue by Operrr** [makerbase-mks/MKS-TFT#174]
Set for changing the appearance of the user interface MKS TFT3.5.

How to install:
1. Unzip the archive
2. Copy the mks_pic folder to an SD card or USB media
3. Insert the SD card or USB storage media into the MKS TFT and press the reset button

This is my first project so please do not judge severely, if you find any errors, write to email.

You can download the skin at the link https://1drv.ms/u/s!AicE0iKLGf_0iNQbDRlMWYr1Z3ic_Q

**Comment by makerbase-mks** [comment]
![image](https://user-images.githubusercontent.com/12979070/44328930-99125d00-a495-11e8-9da0-ea5120710beb.png)

**Comment by makerbase-mks** [comment]
copy the file to the SD card

**Comment by odersone** [comment]
Soeh, obviously you know somthing I do not, about the bmp files or whatever, to be able to convert a bmp successfully to bin for the TFT35. Any chanse you can help a struggeling friend out so I too can have my custom icons? 

When I try to convert a correct size bmp it is just scaled wrong when I upload to the TFT

**Comment by makerbase-mks** [comment]
You can use this software to convert and set the corresponding size of the picture.

https://github.com/makerbase-mks/Software/tree/master/Image2LCD

**Comment by odersone** [comment]
Any specific settings than might be important? Scan mode etc? the size I seem to be able to get from the original bin files with Makerbase image editor
