### ISSUE TITLE
Whats the wifi for.

### ISSUE THREAD

**Issue by ghost** [makerbase-mks/MKS-TFT#176]
Hello.

I Just bought a mks noard with tft 2 and mks wifi. How to access the webinterface? 
Ther is just a green settingspage. It was easy to connect to my ap. What now todo with it?

Whats the functionality? I thought i can upload gcode with it....

Thanks

**Comment by ghost** [comment]
Can noone tell what it does?

**Comment by makerbase-mks** [comment]
yes,it can upload the gcode file if you have a nice configuration
https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT28%2032%20Datasheet.pdf
