### ISSUE TITLE
TFT35 Touch Screen. Double display of the first custom button

### ISSUE THREAD

**Issue by GenaUser** [makerbase-mks/MKS-TFT#179]
Hello,
I've an embarrassing bug; The first custom button is displayed twice.
For their part, the functions are organized normally.
This shifts the functions relative to the buttons.
ex: button1 / function1; button1 / function2; button2 / function3 ....
In contrast, the "morefunc" buttons don't have this problem and displays normally (these buttons are only usable while printing)
Am I the only one with this problem?

**Comment by makerbase-mks** [comment]
We will update the firmware as quickly as possible

**Comment by GenaUser** [comment]
Thank you for your prompt response.
I wait for this update impatiently

**Comment by makerbase-mks** [comment]
we have updated the firmware.

**Comment by GenaUser** [comment]
That works! 👍 
Thanks for your reactivity.

**Comment by Operrr** [comment]
You say that the firmware was updated, but in the list of downloaded firmware only version 1.0.1 which I downloaded more than a month ago.

**Comment by makerbase-mks** [comment]
@just fix the bug ，no change the version

**Comment by makerbase-mks** [comment]
@Operrr  just fix the bug ，no change the version
