### ISSUE TITLE
The Chinese inscriptions in English firmware

### ISSUE THREAD

**Issue by dementiev-net** [makerbase-mks/MKS-TFT#18]
Hi,
I'm using version 2.0 of the folder: "Red style\Classic"
Some icons in Chinese

![img_8118](https://cloud.githubusercontent.com/assets/12710264/24401490/4a67d0fa-13bd-11e7-99e0-3c46c30264a5.JPG)
![img_8117](https://cloud.githubusercontent.com/assets/12710264/24401493/4daa73d0-13bd-11e7-8c89-b3b720e3e7f4.JPG)

**Comment by makerbase-mks** [comment]
Sorry, it's my carelessness to make such a fault, I have uploaded the right one  to the Gihub, you can have a try.
