### ISSUE TITLE
TFT2.8-3.2 - WIFI button change into "Back menu" icon when pressed 

### ISSUE THREAD

**Issue by tiwanacote** [makerbase-mks/MKS-TFT#180]
Into WIFI menu there is two buttons at first: 

1) WIFI icon  
2) Back icon

When you press WIFI icon it change to the "back menu" one.
(No using WIFI board)

![20180809_092622](https://user-images.githubusercontent.com/12189456/43899078-35913be8-9bb7-11e8-8d3a-876dd5720035.jpg)

**Comment by makerbase-mks** [comment]
what is the version of your software?

**Comment by makerbase-mks** [comment]
give me your firmware of TFT.

**Comment by tiwanacote** [comment]
https://drive.google.com/open?id=1R6LAGwlNJYlYMuY6k2ADbTzKy6APHNi5

**Comment by tiwanacote** [comment]
Version 3.0.2
