### ISSUE TITLE
TFT2.8-3.2 - Reboot LCD when pressing left up button in "more" menu

### ISSUE THREAD

**Issue by tiwanacote** [makerbase-mks/MKS-TFT#182]
This is a random issue that occurs systematically in some LCDs of our machines. The problem occurs with 3.0.0 & 3.0.2 (We don't tested into 3.0.1 )

If we configure simple command G28 (Home) to this button, the LCD restart or reboot. The Pronterface or Repetier host log shows "Unknown command". Some times shows garbage.

If we don't assign any Gcode command you can press it and there is no problem

Regards

**Comment by makerbase-mks** [comment]
the command of "More"menu need to add the ";" in the end.

**Comment by tiwanacote** [comment]
We have ";" in the end. This is not the problem.
