### ISSUE TITLE
Home Icon custom Gcode

### ISSUE THREAD

**Issue by MHD95** [makerbase-mks/MKS-TFT#184]
Hi all
I'm new to 3Dprinter and i want to make some change in LCD firmware; because of some option that i add to my printer, i have to change some Gcode command that will sent to main board.

for example when user touches the home icon in lcd, i want to sent some commands moreover G28 to main board.
How can i do this? which file i must change in firmware?
is it possible at all?? :))

i have a MKS TFT28, RAMPS1.4 and Marlin Firmware on my printer.

Thank You for answering:))

**Comment by makerbase-mks** [comment]
you can add the command in the "More" button.
