### ISSUE TITLE
Firmware for TFT24 "Offline MKS DLC GRBL CNC Shield Controller"

### ISSUE THREAD

**Issue by DirtyEngineer** [makerbase-mks/MKS-TFT#189]
Seems Makerbase finally released a version of the TFT24 for GRBL. 

![mks tft24 dlc controller](https://user-images.githubusercontent.com/10263751/44439552-9bee7a00-a589-11e8-99bf-cbc70784340e.PNG)

(https://www.aliexpress.com/item/OFFLINE-MKS-DLC-GRBL-CNC-Shield-controller-TFT24-touch-screen-CNC-engraving-laser-control-board-DIY/32911144359.html) 

This is really exciting as I've been asking for this for a while. (https://github.com/makerbase-mks/MKS-TFT/issues/97)

Can you please provide the firmware update for the TFT24 to convert to the GRBL offline Controller.

Thank you.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS_TFT_CNC

**Comment by DirtyEngineer** [comment]
Thank you!

**Comment by Donderda** [comment]
is there also a version for the TFT32?

**Comment by makerbase-mks** [comment]
@Donderda Sorry, for the time being only the version of tft24

**Comment by blikkies** [comment]
Do you have roadmap for TFT32 CNC release?

**Comment by weed2all** [comment]
Do we need to make some mods on grbl file to get mks tft24 to work...or is just plug and play?

**Comment by makerbase-mks** [comment]
@weed2all As long as the baud rate of the screen is the same as the baud rate of the motherboard firmware setting, no other settings are required.

**Comment by weed2all** [comment]
Right...thank you so much...this will promise alot to have standalone cnc controller...

**Comment by ghost** [comment]
Thank you very much for the work done on this for the CNC people. By looking at this GUI I assume this is using the red version GUI?

Could you pleas show photos of each screen? I will be looking to redesign a new GUI that will be a bit more clean and modern.

**Comment by sasha-zimin-81** [comment]
TFT24 для GRBL.  Подскажите пожалуйста, как правильно залить эту прошивку для использования лазера, а то боюсь испортить драйвер.

**Comment by rlwoodjr** [comment]
Is there source code available for this project?

**Comment by paragraf9282** [comment]
TFT24 doesn’t work with GRBL laser if it has limit switches and Homing cycle enabled ($22=1)
Connected TFT24 not allow normally work GRBL laser over USB

**Comment by marcelovx23** [comment]
> TFT24 doesn’t work with GRBL laser if it has limit switches and Homing cycle enabled ($22=1) Connected TFT24 not allow normally work GRBL laser over USB

how you know that?

**Comment by paragraf9282** [comment]
> > TFT24 doesn’t work with GRBL laser if it has limit switches and Homing cycle enabled ($22=1) Connected TFT24 not allow normally work GRBL laser over USB
> 
> how you know that?

I found this out by connecting the TFT 24 to my TwoTrees engraver. I solved the problem with the USB by putting a power switch for the TFT 24. With it, I turned off the 5th line when I used the USB. But the limit switches had to be turned off…

**Comment by marcelovx23** [comment]
> > > TFT24 doesn’t work with GRBL laser if it has limit switches and Homing cycle enabled ($22=1) Connected TFT24 not allow normally work GRBL laser over USB
> > 
> > 
> > how you know that?
> 
> I found this out by connecting the TFT 24 to my TwoTrees engraver. I solved the problem with the USB by putting a power switch for the TFT 24. With it, I turned off the 5th line when I used the USB. But the limit switches had to be turned off…

Same thing but whit a router machine, power swich to tft24 and mks dlc v2, limit switches and Homing cycle should be disabled, when machine activate a limit swich, grbl go to alarm state and no way to remove alarm state whit tft24
