### ISSUE TITLE
Does not respond to M300 or M600

### ISSUE THREAD

**Issue by veedubb65** [makerbase-mks/MKS-TFT#19]
M300 in a gcode file should cause the buzzer to beep. It has no effect.

M600 in a gcode file should cause the printer to pause, mid print, for a filament change. It should also show appropriate tools on the screen for changing filament. It has no effect.

MKS TFT28, MKS firmware 2.0. Latest Marlin Firmware on MKS Base board.

**Comment by makerbase-mks** [comment]
Hello dear,I am sorry that mianboard does not support M300 to run buzzer.
there are 15 commands for filament IN/OUT,so it will not stop until 15 commands finish.

**Comment by pauloblank** [comment]
The board has got a buzzer but no way to use it? If M300 does not work, should be another way of using the buzzer. Please correct this.
