### ISSUE TITLE
TFT2.8-3.2 - No more Z auto levelling feature after recovering printing after power failure

### ISSUE THREAD

**Issue by tiwanacote** [makerbase-mks/MKS-TFT#191]
If you are printing with auto leveling feature and your printer turn off, then, when recovering printing, auto leveling is disabled and your printing fails.
You should add M420 S1 in recovering GCode

Version 3.0.2

**Comment by makerbase-mks** [comment]
You should saved the data to the main board, not the tft.

**Comment by mpcolman** [comment]
and how I save the data to the main board???????
