### ISSUE TITLE
MKS GEN 1.4 + MKS PWC V2 + BLTOUCH = pause

### ISSUE THREAD

**Issue by Romano26** [makerbase-mks/MKS-TFT#192]
Hello

I have for more than a year a mks Gen 1.4 card with a bltouch that works perfectly.
I wanted to install a MKS pwc v2 card to be able to stop my printer once printing is complete.
after more forum me detailing the installs, I managed to make it work all
the problem is that today my printer is pausing during printing, i check the gcode no worries.
I disconnected the PWC board and everything works again.
Have you ever had this problem ?
thank you

**Comment by makerbase-mks** [comment]
you can check the conect of wire and confirurantion of firmware.
