### ISSUE TITLE
Request: TFT35 - stop printing but not disabling heating

### ISSUE THREAD

**Issue by djtaotao** [makerbase-mks/MKS-TFT#197]
Can be added an option in config file when stop the process of printing to not disable the heating of hotend and bed?
Sometimes, for any reason, the printing should be stop and started again after a while and I have to wait again for the whole process heating.

For reprapdiscount controller, in my marlin, for stop printing I have modified in ultralcd.cpp the function that stop heating:

    void lcd_sdcard_stop() {
      card.stopSDPrint();
      clear_command_queue();
      quickstop_stepper();
      print_job_timer.stop();
      //thermalManager.disable_all_heaters();
      #if FAN_COUNT > 0
        for (uint8_t i = 0; i < FAN_COUNT; i++) fanSpeeds[i] = 0;
      #endif
      wait_for_heatup = false;
      lcd_setstatusPGM(PSTR(MSG_PRINT_ABORTED), -1);
      lcd_return_to_status();
    }

**Comment by makerbase-mks** [comment]
You can contact our sales staff to create a custom design for your product.
King@makerbase.com.cn
