### ISSUE TITLE
No feedback from printer using MKS WiFi

### ISSUE THREAD

**Issue by veedubb65** [makerbase-mks/MKS-TFT#20]
Using the latest Firmware and an MKS WiFi module connected to the MKS TFT, I can send an M303 command for PID autotuning, which will cause the hot end t cycle through temperatures as expected, but it never returns the PID autotuning results to the console. (tested with printrun and repetier host)

Likewise, errors codes don't get returned. If I use printrun to try and extrude while nozzle is cold, it refuses to extrude, but doesn't return the error message to the console.

If I connect directly to the MKS Base board via USB, I get normal feedback in the terminal, so the issue is specifically the MKS TFT / MKS WiFi.

**Comment by makerbase-mks** [comment]
Hello dear,it is unavailable to get feedback ,but just say "OK" .
Because TFT will skip some commands .
