### ISSUE TITLE
No reports via WIFI

### ISSUE THREAD

**Issue by 3kmch** [makerbase-mks/MKS-TFT#200]
I connected the WIFI sucsessfully to the TFT. Sending commands from the computer to the device works without problems. :) But when I send "M501" it should report some eeprom settings like "M212...". Somehow the TFT filters out this reports. Any idea how I can grab these values?

Btw I set marlin in the config...

**Comment by ZhuDaHai** [comment]
I think you want M503 to see the settings. 
M501 just reads the settings from EEPROM and makes them active. It doesn't necessarily report them.

**Comment by 3kmch** [comment]
I don't get a report with M503 neither. :/

**Comment by hlgithub7430** [comment]
Hi Kurt, how did you make to send files to the esp module? I get from repetier host always an error.

**Comment by 3kmch** [comment]
@hlgithub7430 I did not try that by now. I just wanted to connect over wifi to list some settings. ;-)

**Comment by Andrei-Pozolotin** [comment]
See #285
