### ISSUE TITLE
No Wifi Button

### ISSUE THREAD

**Issue by ZhuDaHai** [makerbase-mks/MKS-TFT#202]
I have the MKS TFT28 v3.0 display board running firmware v3.0.2
However I do not have a Wifi button under 'Settings' in the menus.
I have the MKS TFT Wifi module installed (not the HLKWIFI) and it is working as I can connect to it via Pronterface using its IP address and Port 8080, and I can control the printer via Pronterface.
There is just no Wifi button to view its status.
Here is my Wifi configuration:

```
>cfg_wifi_type:0
>cfg_wifi_mode:0
>cfg_wifi_ap_name:MySSID
>cfg_wifi_key_code:MyPassword
>cfg_cloud_enable:1
>cfg_wifi_cloud_host:www.baizhongyun.cn
>cfg_cloud_port:10086
>cfg_ip_dhcp_flag:1
>cfg_ip_address:192.168.3.100
>cfg_ip_mask:255.255.255.0
>cfg_ip_gate:192.168.3.1
```
P.S. I have mks_wifi.bin file loaded as well.

Hope someone can help

Thanks!

**Comment by makerbase-mks** [comment]
Where is your firmware downloaded?

**Comment by ZhuDaHai** [comment]
JGAurora web site for their A5 3D Printer.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT2.8-3.2/TFT28_32_v3.0.2%20Release%20file.zip
