### ISSUE TITLE
Customer service

### ISSUE THREAD

**Issue by mpieroway** [makerbase-mks/MKS-TFT#206]
I have sent king a number of emails and in the initial email he expresses his willingness to help. Then he ignores and sends no responses to my emails.

Why do you have no English data sheets for products you sell to the rest of the world and do not answer questions relating to what the product will support?

**Comment by makerbase-mks** [comment]
What do you want the datasheet of product ? We'll update the datasheet continuously.

**Comment by mpieroway** [comment]
It is for the MKS Gen 2z boards. Mr. King said he would respond to direct questions as there are no English datasheets, however after a few emails my questions still have not been answered.
