### ISSUE TITLE
issues after update

### ISSUE THREAD

**Issue by nitr8** [makerbase-mks/MKS-TFT#21]
![img_0516](https://cloud.githubusercontent.com/assets/541890/24586450/71be858a-17a1-11e7-844c-6ab8e5a39fed.JPG)

Hi All,

Menu seems to work, but all icons are blured out, any pointers would be appreciated..

**Comment by Haunz** [comment]
If you copied the firmware from a Mac to SD this will happen. 
Try a Windows based to copy the files. Worked for me. I dont understand why i cant copy it from Mac.

**Comment by nitr8** [comment]
Hi Haunz, thank you for that that resolved my problem! Just copied the files on a Windows VM and it did the trick...
