### ISSUE TITLE
19 secound pauses  every each layer after connecting MKS DET module

### ISSUE THREAD

**Issue by bogaskilop** [makerbase-mks/MKS-TFT#212]
today i connected  MKS DET module to test power outage resume function.

i started simple g code with calibration cube and i observer that every Z height change  printer is stopping at the end of each line just before Z change for next layer and it's taking  19 seconds.

i uploaded my config and simple gcode 
[mks_config.txt](https://github.com/makerbase-mks/MKS-TFT/files/2411259/mks_config.txt)

[calibration.txt](https://github.com/makerbase-mks/MKS-TFT/files/2411263/calibration.txt)

power resume function works because i tested it when i figured out that printer is stopping every Z change  even after purge line it stops for that 19 seconds  but why ? 

print is from SD card at mks tft 32

**Comment by bogaskilop** [comment]
really no answer  from support ?

**Comment by makerbase-mks** [comment]
@bogaskilop Wouldn't this be the problem if you didn't connected the DET module?

**Comment by mcsultan** [comment]
if, m105 in your gcode, del all.
