### ISSUE TITLE
Font Update on TFT32

### ISSUE THREAD

**Issue by FDGil** [makerbase-mks/MKS-TFT#213]
Hello!

recently I downloaded and updated everything on my MKS TFT 32.
i changed firmware to classic and theme to blue.
i also updated fonts embebbed on download available.
The problem is that now the labels of the buttons don appear anymore.
what is causing this issue?
maybe the font file is not working.

**Comment by makerbase-mks** [comment]
>cfg_multiple_language:1
Is there this configuration  enabled?
