### ISSUE TITLE
MKS TFT + BL Touch 

### ISSUE THREAD

**Issue by selvakumaran2016** [makerbase-mks/MKS-TFT#214]
Hi all,
I am using MKS Gen 1.4 + MKS TFT 3.2. Print resume after power outage was working perfectly. 

Now I have added BL touch to the MKS TFT. As the BL Touch is having the self check  when powered on, it is giving issues. 

For example, at the start of the print BL touch  probe is moving up and down for self testing. This is fine.

After some hrs of print, the power shut down happens. Now the print pauses there itself and the nozzle position will stop there itself. After some time the power comes back.  This time also, BL touch probe moves up and down for the self test. But, as the nozzle is touching the print and when the BL touch probe moves down, it is unable to move down. So, it shows 'BL touch error' and the print halts. So, my print has to be scraped.

How to avoid BL touch to do the self test when the power comes back?
Shall we disable the selftest?

Suggestions please.

Thanks

**Comment by makerbase-mks** [comment]
Hi! The BLTOUCH self-test is self is not controlled by marlin.
