### ISSUE TITLE
MKS TFT + Baby stepping

### ISSUE THREAD

**Issue by selvakumaran2016** [makerbase-mks/MKS-TFT#215]
Hi All,

I am using MKS Gen 1.4 + MKS TFT + Marlin.

In Marlin, we can use Babystepping. With 2004 LCD, baby stepping is coming easily. But I am unable to do babystepping with MKS TFT.  I tried to add an icon in the 'More' option by using M290 X--, M290 Y--.

But it is not working. Any suggestions please.

Thanks 
Selvakumaran

**Comment by makerbase-mks** [comment]
>moreitem_button1_cmd:M290 X--;M290 Y--;

**Comment by selvakumaran2016** [comment]
I tried a lot. Its not working. Please suggest any other idea.

**Comment by makerbase-mks** [comment]
Please send me your configuration file mks_config.txt

**Comment by 3dworkio** [comment]
Hello,

I have the same issue, can you confirm me where to add this line?
I attach the file, thanks in advance!

Regards!


[mks_config.txt](https://github.com/makerbase-mks/MKS-TFT/files/4261099/mks_config.txt)

**Comment by makerbase-mks** [comment]
If the screen is idle, you can set it in the configuration file like this:
#set number of "More" button
> moreitem_pic_cnt: 1

#edit command for 1 ~ 7 "More" button, each command must be separated by semicolon ";"
> moreitem_button1_cmd: M290 X-; M290 Y--;

If the screen is printing, you can set it in the configuration file like this:
#how many "More" button display on screen interface
> morefunc_cnt: 1

#command setting on button1 ~ 6
> morefunc1_cmd: M290 X-; M290 Y--;
