### ISSUE TITLE
MKS-TFT2.8-3.2 v3.0.3 -  does not rotate the screen by 180 with the cfg_OVERTURN_180:1

### ISSUE THREAD

**Issue by Acenotass** [makerbase-mks/MKS-TFT#223]
MKS-TFT2.8-3.2 v3.0.3 -  does not rotate the screen by 180 with the cfg_OVERTURN_180:1

**Comment by arnljot** [comment]
Im experiencing the same thing. Im using the win10 look, my pcb is TFT32_L V4.0 and my firmware is 3.0.3

**Comment by arnljot** [comment]
I have now also verified that the problem persists with the "blue" config.

**Comment by arnljot** [comment]
I figured it out, the example configs are with but the template config in the distro rarfile config file is not:

#The screen is flipped 180°(0x00: no flip, 0xEE: flip)
>cfg_OVERTURN_180:0x00

With the swing set to 0xEE, it works

**Comment by makerbase-mks** [comment]
We have updated the configuration file.
