### ISSUE TITLE
Strange things append if move (jog) while gcode paused

### ISSUE THREAD

**Issue by atolala** [makerbase-mks/MKS-TFT#224]
Hi

I have strange issue if i do a pause when gcode is started and when is paused i make move Z-10 and click resume, i have do some serial port log :

When do pause screen send
M116
G91
G1 E-1
G1 Z10
G90
M114

When do resume without move manually
G91
G1 Z-10 F3000
G1 E1.5
G90
M105

When do resume with some move manually (from button move available in pause mode)
G92        ?????????? what it is for ?  i have check all firmware same problem
G1 F3000 X0.0000 Y0.0000 Z5.0000         ??????? what it is for ?  i have check all firmware same problem
G91
G1 Z-10 F3000
G1 E1.5
G90
M105

Br

**Comment by makerbase-mks** [comment]
G90: Set to Absolute Positioning
G91: Set to Relative Positioning
G92: Set the position of the origin
Because the distance of the moving axis when you pause, the G-code text code is relatively zero, so when you resume printing, he will return to the original position.
