### ISSUE TITLE
TFT35 : UI BMP and MakerBaseImageEditor

### ISSUE THREAD

**Issue by stef-ladefense** [makerbase-mks/MKS-TFT#226]
hi,

please update MakerBaseImageEditor for use with news TFT3.5 and TFT70
and make available the original bmp images, that we can leave from your base to modify the icons.

thank

**Comment by makerbase-mks** [comment]
Are you need the function of images transfer .bin files?

**Comment by stef-ladefense** [comment]
No, I have no problem turning a BMP into a BIN!

I ask you to provide the sources of the images that we can take them to add buttons with the same look as yours

**Comment by stef-ladefense** [comment]
up

**Comment by stef-ladefense** [comment]
up

**Comment by stef-ladefense** [comment]
alors MKS ? vous comptez un jour fournir les images raw de vos merdes d'afficheurs bugué jusqu'à la moelle ?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/UI-Design/TFT3.5_UI.rar

**Comment by stef-ladefense** [comment]
c'est pas ça que l'on demande !!!
c'est toutes les images au format brut, en bmp avant transformation en .bin que l'on veut

**Comment by makerbase-mks** [comment]
The bmp files ?

**Comment by makerbase-mks** [comment]
Do you want all the BMP files in TFT35?

**Comment by stef-ladefense** [comment]
oui ! toutes les BMP for TFT35 ! 2 mois que je demande

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/UI-Design/TFT35_BMP_FILE.rar

**Comment by stef-ladefense** [comment]
BRAVO !!! 2 mois pour donner accès a de simples bmp !
mais seulement pour le TFT35, pour les autres c'est pas possible non plus ????

**Comment by AntoszHUN** [comment]
Please update the MakerBase Image Editor for use with news TFT35!

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Software/tree/master/Image2LCD

**Comment by RobertoBrachini** [comment]
Is it possible to have the TFT70 BMPs? or the MakerBase Image Editor updated to open BINs. Thank you

**Comment by AntoszHUN** [comment]
Unfortunately, it is not possible. I don't have the time. Also, there is no
TFT70 display.

RobertoBrachini <notifications@github.com> ezt írta (időpont: 2019. ápr.
29., H 12:50):

**Comment by RobertoBrachini** [comment]
![image](https://user-images.githubusercontent.com/50103573/56892247-51f65600-6a7f-11e9-8292-019df0fc96e4.png)

I can't open BINs

**Comment by RobertoBrachini** [comment]
non riesco ad aprire i BIN

**Comment by stef-ladefense** [comment]
close ? no !
release bmp for all screen !

**Comment by makerbase-mks** [comment]
Sorry, then I reopen it. I am collecting TFT70 picture data ...

**Comment by makerbase-mks** [comment]
Hi! I has upload MKS TFT70 bmp, you can refer to : https://github.com/makerbase-mks/MKS-TFT70/tree/master/TFT70_BMP

**Comment by RobertoBrachini** [comment]
thank...

**Comment by stef-ladefense** [comment]
ok thk
but where bmp for 2.4, 2.4 CNC, 2.8/3.2 ? 
it's also possible to put everything in the same place ?
here https://github.com/makerbase-mks/MKS-TFT/blob/master/UI-Design

**Comment by makerbase-mks** [comment]
@stef-ladefense 
Hi! I will put a TFT70 BMP in UI-Design. However, in the future, we will place corresponding data sheets for each product. Currently, it is in a transition period, thank you for understanding!

**Comment by makerbase-mks** [comment]
I has upload TFT70 BMP to MKS TFT UI-Design, you can refer to : https://github.com/makerbase-mks/MKS-TFT/tree/master/UI-Design

**Comment by ismailkaraman16** [comment]
Hey, can you share ts35's bmp images?
![EfNRrqhUwAAMLwy](https://user-images.githubusercontent.com/84245633/118373987-52a8a900-b5c2-11eb-9bf8-31a1baf69695.jpg)

**Comment by ismailkaraman16** [comment]
okay, i got it from  https://baizhongyun.cn/home/mkstoolview . 
[mks_robinnanov2_ts35_images.zip](https://github.com/makerbase-mks/MKS-TFT/files/6488069/mks_robinnanov2_ts35_images.zip)
