### ISSUE TITLE
How to set temperature limit higher than 270 degree?

### ISSUE THREAD

**Issue by andreytitovich** [makerbase-mks/MKS-TFT#23]
I'm changing in mks_config.txt  "cfg_max_sprayer_temperature:270" to "cfg_max_sprayer_temperature:350"

First time MKS TFT allows me set temperature to the maximum. But after I reboot MKS TFT I can't set temperature higher than 270 degrees. In the preheat menu it limited to 270 degrees. When I try to print file, where temperature is set higher than 270 degrees, the temperature goes to the value, set in .gcode, but then MKS TFT stops.

I use firmware V2.0.0 from the Github. Seems like it's real issue.

P.S. My mainboard is MKS SBASE V1.3 with smoothieware firmware. In the firmware configuration maximum temperature set to 350 degrees.

**Comment by makerbase-mks** [comment]
we have test the function,it is OK.
if you can't use it ,please send email to shelly@makerbase.com.cn .
she will help you. thanks
