### ISSUE TITLE
TFT35 Wire

### ISSUE THREAD

**Issue by formu25400** [makerbase-mks/MKS-TFT#233]
Hello, I have a problem with the TFT35.
the load unload wire function no longer works
on my mks sbase v1.3
any idea about the problem?

**Comment by makerbase-mks** [comment]
Check that the baud rate of the screen and the motherboard are the same.
Set the firmware type of the motherboard in the touch screen, sbase (the smoothie firmware should be selected in the touch screen configuration file)

**Comment by formu25400** [comment]
Everything and okay 
The other functions work well
Just the son function has a problem
the problem and appeared since the last update

tft35 / firmware 1.0.1
MKS sbase v1.3 / marlin 2.0

**Comment by makerbase-mks** [comment]
You mean the old firmware of TFT is normal?  
MKS sbase v1.3 / marlin 2.0??? sbase+marlin2.0??
Our sbase just run in the smoothware.

**Comment by formu25400** [comment]
Yes, with the old firmwar it works.
hihi ya MKS sbase v1.3+marlin 2.0 :)

**Comment by dbemowsk** [comment]
So I have an MKS TFT35 that I would like to try to use with a Fysetc S6 board.  The S6 board does not have an aux1 port, but it does have a UART1 port that provides serial communication.  My question is, can I just connect the +5, GND, RX and TX to the UART port to make it work or is it crucial to have the other 2 data pins from the TFT35 display connected for it to function correctly?  My understanding of the pinout on the 8 pin connector of the TFT35 is this:

 +5 | GND | RXD | TXD
 +5 | GND |  Dxx  | Dyy

I am not sure of the function of the Dxx and Dyy pins on the display.
