### ISSUE TITLE
TFT35 ; TFT70 and OLD TFT24, TFT28/32 originals BMP images 

### ISSUE THREAD

**Issue by stef-ladefense** [makerbase-mks/MKS-TFT#236]
hi,

please make available the original bmp images, that we can leave from your base to modify the icons.

thank

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/UI-Design

**Comment by stef-ladefense** [comment]
Tank but is not good résolution for TFT70 or TFT35

**Comment by stef-ladefense** [comment]
up !

**Comment by stef-ladefense** [comment]
up !

**Comment by makerbase-mks** [comment]
@stef-ladefense Send me your email address.

**Comment by stef-ladefense** [comment]
publish here !
