### ISSUE TITLE
end of filament sensor

### ISSUE THREAD

**Issue by rulochaparro** [makerbase-mks/MKS-TFT#237]
Hi, i noticed that end of filament sensor doesn't work, i check it in version 3.3 and the buzzer doesn't pip but if i instal V3.0 works.

thanks

**Comment by tiwanacote** [comment]
I noticed the same problem, something wrong in new version.

**Comment by rulochaparro** [comment]
Hi again, sorry for the insistence, but do you have some news?

Thanks!

**Comment by makerbase-mks** [comment]
Which product are you using?Which interface did you pick up?

**Comment by makerbase-mks** [comment]
I am test the tft32_v3.0.3 with the pin of P0(or P1) connected filament sensor,and the filament end of,tft32 will display pause state, wait for about 2 seconds ,the buzzer is pip。
