### ISSUE TITLE
Tft35  more extruders for Rumba+ and Laguage File for German

### ISSUE THREAD

**Issue by mattes2019** [makerbase-mks/MKS-TFT#239]
Hello,
I am new here and have some questions.
how can I define the third or more extruder, since the TFT of MKS in the package with RUMBA + is offered should go well. In marlin, I can even define 6 extruders. ??
Is it possible to create your own language files z, B, "German"???

**Comment by makerbase-mks** [comment]
The function of  3 extrusions and German language needs to make a custom designed.Please contact us if you have any requirements:King@makerbase.com.cn

**Comment by mattes2019** [comment]
That's just nonsense. They sell a display that does not even meet the lowest requirements of customers and the Rumba +, which is sold simultaneously in the package, and still praises it as an innovation. Then you want to sell extensions that meet today's minimum standards as a customized development. this is a naughtiness, your product is bad and i will communicate this in the appropriate forums, then you can once again honor your name.
Just release the source code and the language files, the rest will be done by the 3d community.

**Comment by stef-ladefense** [comment]
Bravo +1

**Comment by legalstuff** [comment]
need same things.. 3 extruders.. and German language files (own config)
