### ISSUE TITLE
Error messages?

### ISSUE THREAD

**Issue by cruwaller** [makerbase-mks/MKS-TFT#24]
Is there way to see error messages? Now the GUI is not very informative...

TFT32 with 2.0 firmware has a printing issue and stops suddenly at some point, GUI get stuck (unresponsive) but no information why!!
How to debug the issue??
TFT32 is connected to the SBASE v1.3 which works great (all SD, LAN and USB printing is ok).

Currently the display is useless.

**Comment by makerbase-mks** [comment]
Because this function need higher speed MCU. We can't add this to TFT. Sorry.

**Comment by cruwaller** [comment]
Haha, really? You are using 32bit ARM processor and there is not CPU time to process error messages from uart? Wtf!
How can you process / feed gcode to printer controller? 
Currently this LCD is useless since i cannot locate the error/what happened...

Strange...
