### ISSUE TITLE
Tft35 and mks rm04 module

### ISSUE THREAD

**Issue by ghost** [makerbase-mks/MKS-TFT#241]
I ve tried to get the module to work with tft35 but no luck,all my configurations are correct"i think" the baud rate is 115200 on board,tft35 and the module but i cant get it to passthrought to work pronterface.When i bypass the tft35 and plug the module directly to the sbase v1.3 board it connects with no problem.latest v1.01 firmware and wifi.bin on tft35.the module is connected to the tft35 wifi port...anyone got it to work from there...? Thank you.

**Comment by makerbase-mks** [comment]
You mean the MKS TFT35 not work with MKS TFT WIFI module?

**Comment by ghost** [comment]
yes correct i have the HLKWIFI module.
