### ISSUE TITLE
New firmware when? 

### ISSUE THREAD

**Issue by robustini** [makerbase-mks/MKS-TFT#242]
Many people, including me, are waiting for a new firmware that solves the various problems reported, when you plan to fix them and release a finally functional version?
Or if you are not able to fix it, could you release the code, which at least we look at in many for debugging?
Regards,

Marco

**Comment by stef-ladefense** [comment]
+1

**Comment by thisoldscot** [comment]
+2 Plus responses to issues would be nice.

**Comment by robustini** [comment]
I think the MKS developers are a little bit panicked.
They certainly make good hardware, but about software developing they should do something else in life.
At the moment they have not been able to solve things that are rather simple.

**Comment by thisoldscot** [comment]
I think releasing the source and letting us help to improve the firmware would be a good start, it's not like  its something that needs to stay closed source! would also probably improve sales if it was OS?

**Comment by robustini** [comment]
Releasing the code or a real working firmware would brutally increase display sales.
MKS, you don't have to be a genius to understand it.

**Comment by stef-ladefense** [comment]
MKS are dead! no one answers, they are strong to sell but completely zero to do some things that works

Vous allez quand vous sortir les doigts du cul MKS ?

**Comment by makerbase-mks** [comment]
Sorry for it.We will improve the technical support work in this area.The new firmware is already in beta and is scheduled to be released in the last two weeks.

**Comment by robustini** [comment]
> 
> 
> Sorry for it.We will improve the technical support work in this area.The new firmware is already in beta and is scheduled to be released in the last two weeks.

It would be useful to have this beta firmware to do some tests.

**Comment by weanything** [comment]
OK try as I may I cannot get the Pad7 to upload the firmware in the way described - any help appreciated?

**Comment by stef-ladefense** [comment]
ils sont inconscients chez MKS  ! 
ils laisses leurs utilisateurs avec les problèmes issus de leur incompétence !

mettez à disposition les sources et les versions beta ! tous le monde gagnerait par cette action

**Comment by robustini** [comment]
> 
> 
> Sorry for it.We will improve the technical support work in this area.The new firmware is already in beta and is scheduled to be released in the last two weeks.

The last two weeks have already passed... where is the firmware?

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT3.5/TFT35_V1.0.2 Release file.rar

**Comment by robustini** [comment]
> 
> 
> https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT3.5/TFT35_V1.0.2 Release file.rar

I mean for TFT32-28!!!

**Comment by sandog78** [comment]
Does anyone have a setup with different icons for the TFT35 in a 1.4 board? no examples like other boards to get a different button layout

**Comment by Andrei-Pozolotin** [comment]
See #285

**Comment by makerbase-mks** [comment]
Hi! We have released a new version of the firmware.
