### ISSUE TITLE
Error (typo) in all config files

### ISSUE THREAD

**Issue by PascalB7** [makerbase-mks/MKS-TFT#247]
Hi

In every config file of 3.03 (as of 2018-12-28), the last variable is "cfg_display_eeror_message" instead of "cfg_display_error_message". Not sure if every config files are wrong, or if the error is in the firmware but there is an EEror!

**Comment by makerbase-mks** [comment]
This function is working properly. We will fix this error display in the next version.

**Comment by LyaminSS** [comment]
what command should i use? for firmware 303

**Comment by Poikilos** [comment]
The example file mks_config_EN.txt still has `cfg_display_eeror_message` in "MKS-TFT2.8-3.2". Is the misspelling in the firmware too (must we use the wrong spelling for it to work)??
