### ISSUE TITLE
Filament Runout Sensor

### ISSUE THREAD

**Issue by forum999** [makerbase-mks/MKS-TFT#248]
Is there any instructions on how exactly to wire up the filament sensor?

Also what am i looking for in the firmware to activate it as since the latest firmware it doesnt seem to show up and the word 'shielded' is used alot without explenation?

can you please give me clear cut instructions on how to set up the firm ware and wire in a filament sensor please.

**Comment by makerbase-mks** [comment]
‘shielded’ is for customers who do not use this feature to disable this feature.
This is the TFT datasheet, with a labeled pin of filament sensor:
https://github.com/makerbase-mks/Datasheet/blob/master/English datasheet/MKS TFT28 32 DataSheet.pdf

**Comment by forum999** [comment]
The link you provided gives a 404 error

And i am aware of the pin what i need is proper instructions on how to set it up, what settings to change in the firmware and what wires i need to connect? 

Ie one wire to b1 obviously is not enough? Where do you connect the common etc...

Or 

Shielded hides the setting but how do i actually turn it on?



What we need is a proper set of instructions, What is available is just lazy writing, and comments by people who have to risk their printers by experimenting to make things work with trial and error.

proper instructions are needed

**Comment by rafaelferrari0** [comment]
@forum999 , about the link, do a copy and paste, or replace spaces with "%20"
(spaces are bad ;)

https://github.com/makerbase-mks/Datasheet/blob/master/English%20datasheet/MKS%20TFT28%2032%20DataSheet.pdf

**Comment by Andrei-Pozolotin** [comment]
See #285

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/Datasheet/tree/master/English%20datasheet
