### ISSUE TITLE
Offset Z on 

### ISSUE THREAD

**Issue by TiZYX** [makerbase-mks/MKS-TFT#250]
hi, 
I want to change the Z Offset on my MKS TFT 2.4 like on the MKS TFT 35
could you please add this function ??
thanks for your help

**Comment by makerbase-mks** [comment]
Tft24 does not have this function.

**Comment by Sjoerd** [comment]
Anyone found the solution?

**Comment by makerbase-mks** [comment]
Hi! The latest firmware already supports Z offset and babystep and so on, you can refer to new firmware and update it.
