### ISSUE TITLE
Wifi Module allow only one connection

### ISSUE THREAD

**Issue by an0Nym0us63** [makerbase-mks/MKS-TFT#251]
Wifi Module allow only one connection which is a pain as if cura is launched on a pc and we want to use the app it keeps going on a loop disconnecting and reconnecting each others

**Comment by an0Nym0us63** [comment]
you should try to create multiple sockets Something like 3 or 4 with own ports so that multiple devices can monitor at the same time

**Comment by makerbase-mks** [comment]
Cura and TFT wifi modules work in LAN mode and can be configured as AP mode or STA mode.
