### ISSUE TITLE
3.5 Version 1.01 No TXT or Icons

### ISSUE THREAD

**Issue by AAShepAA** [makerbase-mks/MKS-TFT#252]
I can install 1.01 and connect at 25000 baud rate, but I have no text or icons although I see them installing. I do see "ReadyPrint" and faint rectangles where the txt or icons should be.  I am on a Tevo Tornado GenL board.

Thanks in advance.

**Comment by makerbase-mks** [comment]
there will be some extra files after use the IOS system to extract our files , such as "._bmp_about.bin", and the file name we use is "bmp_about.bin".

**Comment by yummyburger** [comment]
my same, i dont see "._bmp_about.bin", in my though

**Comment by makerbase-mks** [comment]
The extra files are hidden. Maybe you can set the hidden files to be visible. Delete the extra files and restore them. Follow us engineers to fix this problem
