### ISSUE TITLE
Version for MKS-TFT for SBASE running a Laser

### ISSUE THREAD

**Issue by mayhem2408** [makerbase-mks/MKS-TFT#26]
Are there any plans to make a firmware for the TFT more suited to laser CNCs instead of 3D Printers. I have just purchases a MKS SBASE to upgrade my K40 Laser and the colour touch screen would add a nice look to it. I will be running firmware-cnc.bin instead of firmware.bin on my board.

**Comment by benmprojects** [comment]
I would also like to see this.. Please advise if you are considering doing this. Im sure people will donate to fund this.

**Comment by makerbase-mks** [comment]
good idea, but we will do it after 2-3 month. thanks.

**Comment by cmenchion** [comment]
Any progress on this? Desperately need this.

**Comment by Ruisjm1** [comment]
Is possible create CNC interface for jogging and sending files from sd card? and connect in rx and tx arduino running GRBL to make a stand alone controller?

I think people will love it and buy a lot MKS TFT
