### ISSUE TITLE
No Z moving button in CNC version.

### ISSUE THREAD

**Issue by Quajetson** [makerbase-mks/MKS-TFT#260]
Please add Z+ and Z- in moving screen for CNC firmware.

**Comment by makerbase-mks** [comment]
Hello,you can add the function of "More Buttons"  in the settings interface.

**Comment by targetorsk** [comment]
give an example of how to do it ?

**Comment by Quajetson** [comment]
X0 Y0 Z1 F100
X0 Y0 Z-1 F100

wt., 26 lut 2019 o 10:37 targetorsk <notifications@github.com> napisał(a):

**Comment by hondapa** [comment]
Hello where would those parameters placed?
regards

**Comment by Tomaszm700** [comment]
@makerbase-mks This is not the way to solve this issue. Z axis required also value 0.1mm, 1mm and 10mm If you try to make it on add buttons with G-commands there is no enouge buttons do do it. Why don't you copy this functionality from 3D printers just with add values of 0.1mm in stead of 5mm?

**Comment by Quajetson** [comment]
If U need touch panel for CNC, use Nextion TFT. Full customizable with
serial support and graphic editor.

niedz., 28 kwi 2019 o 08:43 Tomaszm700 <notifications@github.com>
napisał(a):

**Comment by Tomaszm700** [comment]
I got nextion as well. This is not solution people buying DLC with tft 24 and become non full functional firmware. More than that there is a space for this, in the direction control screen we have two doubled from main screen buttons. Expectation of the customers is to have fully functional CNC TFT Firmware.

**Comment by Quajetson** [comment]
Trudno się nie zgodzić. Zrezygnowałem z tego badziewia.

śr., 1 maj 2019 o 07:23 Tomaszm700 <notifications@github.com> napisał(a):

**Comment by Tomaszm700** [comment]
Z tego co wiem Chińczycy mają w głębokim poważaniu co my tu piszemy. Zrobiłem TFT 24 ale to jest leczenie syfa pudrem ( dodałem 4 przyciski definiowalne 3 w dół i jeden w górę, tak by można było dojść frezem do materiału.

**Comment by hondapa** [comment]
hello can you put the configuration file, how do you have it? Thank you
regards

**Comment by makerbase-mks** [comment]
Hi! New version cnc firmware, you can test it.

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS_TFT_CNC
