### ISSUE TITLE
tft70 1.0.1 Home -> disable steppers not work

### ISSUE THREAD

**Issue by rafaelferrari0** [makerbase-mks/MKS-TFT#261]
Hi, developers,

I'm using latest firmware 1.0.1 for TFT70. Inside "Home" button, there is a button to disable steppers (last button), but It's not working. Within 1.0.0 version this was working (using same smoothieware version and configuration, and same TFT70 configuration, only changing mkstft70.bin)

![Image of button](https://raw.githubusercontent.com/rafaelferrari0/trash/master/bmp_function1.png)

I cannot understand why TFT70 is so expensive but full of software bugs and malfunctions.
And no answer about bug "tft70 1.0.1 WiFi unstable" #217 , really is impossible to print over wifi using direct Tcp/Ip connection on local network.

I will not recommend MKS-TFT anymore on new projects.

**Comment by makerbase-mks** [comment]
Hi! New firmware should fix this bug.
