### ISSUE TITLE
MKS TFT firmware update stuck on BMP_Autolevel.b... updating...

### ISSUE THREAD

**Issue by liamrabitte** [makerbase-mks/MKS-TFT#262]
hey guys, trying to connect my tft to my sbase 1.3 with smoothie. the update starts and does a couple lines then always gets stuck on BMP_autolevel.b updating. running the board on a corexy, with NO autolevel. in the config its turned off. any help please???

**Comment by liamrabitte** [comment]
the board is a V4.0

**Comment by liamrabitte** [comment]
so i deleted the autolevel file and it went past it now it gets stuck on something else....could it be the SD card??

**Comment by makerbase-mks** [comment]
You can try to replace a card.

**Comment by robustini** [comment]
If you try to update a TFT32 display with TFT35 files stuck on BMP_Autolevel.bin.

**Comment by Andrei-Pozolotin** [comment]
See #285
