### ISSUE TITLE
Filament change function doesn't work

### ISSUE THREAD

**Issue by mykola-tere** [makerbase-mks/MKS-TFT#269]
I have MKS TFT32 V3.0 with firmware V3.0.3, and MKS Gen 1.4 with Marlin 1.1.9 (last release on official GitHub).
Function Filament change doesn't work from start screen and printing screen. On the old version V2.0.1 work fine. On screen all text showing process, but extruder motor doesn't rotate.
Can you help with solving this issues?

Start screen:
![img_20190204_120540](https://user-images.githubusercontent.com/27860606/52205902-4e3ca400-2881-11e9-9277-dedd1a658a2e.jpg)
![img_20190204_120547](https://user-images.githubusercontent.com/27860606/52205903-4ed53a80-2881-11e9-982d-5a0c9fd39743.jpg)
![Uploading IMG_20190204_120605.jpg…]()
![img_20190204_120610](https://user-images.githubusercontent.com/27860606/52205906-4ed53a80-2881-11e9-97a9-474894a974b2.jpg)
![img_20190204_120641](https://user-images.githubusercontent.com/27860606/52205907-4f6dd100-2881-11e9-90e7-e83449074b25.jpg)
![img_20190204_120648](https://user-images.githubusercontent.com/27860606/52205908-4f6dd100-2881-11e9-9364-54a6f9298fe4.jpg)
![img_20190204_120652](https://user-images.githubusercontent.com/27860606/52205909-4f6dd100-2881-11e9-910e-4605d6786321.jpg)
![img_20190204_120704](https://user-images.githubusercontent.com/27860606/52205910-4f6dd100-2881-11e9-8958-0bd320a898ba.jpg)

Printing screen:
![img_20190204_120759](https://user-images.githubusercontent.com/27860606/52205970-817f3300-2881-11e9-9ce2-6b3c3b415a00.jpg)
![img_20190204_120807](https://user-images.githubusercontent.com/27860606/52205971-817f3300-2881-11e9-8cfa-2b932f295e89.jpg)
![img_20190204_120840](https://user-images.githubusercontent.com/27860606/52205972-817f3300-2881-11e9-89a5-7941117822ba.jpg)
![img_20190204_120844](https://user-images.githubusercontent.com/27860606/52205974-817f3300-2881-11e9-9921-e680cfe31605.jpg)
![img_20190204_120908](https://user-images.githubusercontent.com/27860606/52205978-8217c980-2881-11e9-88e7-9396a7d68b2d.jpg)
![img_20190204_120916](https://user-images.githubusercontent.com/27860606/52205979-8217c980-2881-11e9-93c1-e30ae8d5cd3d.jpg)
![img_20190204_120902](https://user-images.githubusercontent.com/27860606/52205976-8217c980-2881-11e9-9bed-49e193ae70c4.jpg)
![img_20190204_120855](https://user-images.githubusercontent.com/27860606/52205975-8217c980-2881-11e9-8c51-de58b0a597e3.jpg)

**Comment by makerbase-mks** [comment]
The maximum extrusion length set by Marlin is larger than the extrusion length set by mks_config.txt.
