### ISSUE TITLE
adding a costumised startscreen 

### ISSUE THREAD

**Issue by rogerwilco3** [makerbase-mks/MKS-TFT#27]
Hello all,

For a startup screen i costumised the startup image.
The image apears but it is completly inverted.
I tryed different settings in Image2bin but nothing changes.
Did anyone tryed it to play around with this ?

**Comment by makerbase-mks** [comment]
please send email to shelly@makerbase.com.cn . she will help

**Comment by makerbase-mks** [comment]
please send email to shelly@makerbase.com.cn . she will help
