### ISSUE TITLE
TFT35 windows looking UI

### ISSUE THREAD

**Issue by sandog78** [makerbase-mks/MKS-TFT#272]
Is there a way to update the TFT35 to look like the windows tile buttons. I know there is examples you can update from on the 28 but no examples for the 35. I tried using files from 28 example files with the 35 firmware and its a know go. If someone has a custom English UI let me know.

**Comment by legalstuff** [comment]
me too

**Comment by makerbase-mks** [comment]
Tft35 has not yet developed the windows version of the firmware yet.

**Comment by gizmocuz** [comment]
Would be great if that could be done!

**Comment by gizmocuz** [comment]
@makerbase-mks , are you closing this issue because a windows based layout is made, or are you closing the issue because you have no plans to add a windows layout ?
It seems the TFT2.8 is more developed... Do you think we can use the layout of this version for the TFT35 ?
