### ISSUE TITLE
Malware on www.makerbase.com.cn

### ISSUE THREAD

**Issue by 762x51** [makerbase-mks/MKS-TFT#28]
When I try to connect to the www.makerbase.com.cn web site my firewall blocks the connection and sends this message:

The site ahead contains malware

Attackers currently on www.makerbase.com.cn might attempt to install dangerous programs on your computer that steal or delete your information (for example, photos, passwords, messages, and credit cards).

Would you please  remove any Malware from your WEB site so I can safely connect to it.

Thank You

**Comment by makerbase-mks** [comment]
we have deal with this problem, please test again
