### ISSUE TITLE
MKS TFT32 and BLTouch

### ISSUE THREAD

**Issue by aceranic** [makerbase-mks/MKS-TFT#281]
I need help configuring one button on TFT32 for BLTouch operation, GCode to be executed.

Thanks

**Comment by legalstuff** [comment]
interesting.. and I´m looking too

**Comment by makerbase-mks** [comment]
M280 P0 S10 PIN Down
M280 P0 S90 pin up
M280 P0 S120 self-test
M280 P0 S160 alarm release
Above is marlin
Different firmware may use different instructions, you can take a different firmware website to understand
