### ISSUE TITLE
MKS TFT28 - z offset (babyset)

### ISSUE THREAD

**Issue by merinkumar** [makerbase-mks/MKS-TFT#283]
Hi, I bought a MKS TFT28, , its good, but no Z-offset option, is there am missing or will it come in future ?
any work around ?

**Comment by iz3man** [comment]
Afaik you can use the "self assigned" Icons to add your own code.

**Comment by makerbase-mks** [comment]
Hi! We has add this function, you can refer to new firmware and update it.
