### ISSUE TITLE
MKS TFT 35 Not updating firmware via USB

### ISSUE THREAD

**Issue by ksalaba** [makerbase-mks/MKS-TFT#284]
I have all the correct files listed in the read me for MKS TFT35, but when I plug in my usb and restart my display it never updates the firmware. It does update the firmware of wifi everytime. If I remove the wifi firmware update then it boots straight to desktop without ever trying to update the firmware.

**Comment by Andrei-Pozolotin** [comment]
See #285

**Comment by ksalaba** [comment]
I was able to successfully update the firmware after using an SD card. Using a USB to update firmware doesn't work.

**Comment by makerbase-mks** [comment]
Yes, now tft35 is only available for updates via sd card
