### ISSUE TITLE
MKS TFT 35 Cannot heat bed and hotend at same time

### ISSUE THREAD

**Issue by ksalaba** [makerbase-mks/MKS-TFT#289]
MKS TFT 35 should run the following GCODE two heat both bed and hotend at same time.
```
M140 S{print_bed_temperature}	; start bed heating and continue
M109 S{print_temperature}		; wait for extruder to reach target temp
M190 S{print_bed_temperature}	; wait for bed to reach target temp
```
This should be managed by an option

**Comment by IrishMoss** [comment]
You can add this yourself by adding a custom button in the mks_config under the "more buttons" section.
I have one that does just that:
`>moreitem_button1_cmd:M104 S200;M140 S60`
