### ISSUE TITLE
Remove black & white text from buttons

### ISSUE THREAD

**Issue by Clova414** [makerbase-mks/MKS-TFT#295]
Just installed my new TFT32 & updated the firmware,  Now I have some black-and-white text covering that normal text on the buttons that I would like to remove and ideas??

**Comment by makerbase-mks** [comment]
This is the color of the display font or the background color of the font. You can modify the color of the font or background by entering the serial number of the color in the configuration file.
#the color of screen background
>cfg_background_color:0x000000

#the color of title text
>cfg_title_color:0xFFFFFF

#the color of temperature,fan,(etc) background
>cfg_state_background_color:0x000000

#the color of temprature,fan,(etc) text
>cfg_state_text_color:0xFFFFFF

#the color of file button
>cfg_filename_background_color:0x000000

#the color of file text
>cfg_filename_color:0xFFFFFF

#the color of background in printing 
>cfg_printingstat_word_background_color:0x000000

#the color of text in printing status
>cfg_printingstat_word_color:0xFFFFFF
