### ISSUE TITLE
TFT28 - REVERSE THE END FILAMENT SENSOR LOGIC

### ISSUE THREAD

**Issue by FranckGib** [makerbase-mks/MKS-TFT#296]
My printer pauses when the sensor is active (so when the filament passes over the sensor) and printing resumes when it is off.
I can not find a way to reverse the logic of the catper on the firmware of the tft

**Comment by IrishMoss** [comment]
assuming you're using your typical microswitch, you should be able to swap the wires on the switch.  One is for normally open (NO) and the other is for normally closed (NC).  Switching between them will 'reverse' the switch signals.

**Comment by makerbase-mks** [comment]
Hi! Mechanical switch signal, usually NC or NO.
