### ISSUE TITLE
TFT70 for CNC

### ISSUE THREAD

**Issue by 369Martin369** [makerbase-mks/MKS-TFT#299]
Hi, I want to use this large display with my CNC. Can you please update the CNC software so that TFT70 can be utilized? thanks. PS: The 7"display is hot!!!

**Comment by Holiswood** [comment]
+1 for this request.  Is it planed to add the CNC firmware for TFT70 ?

**Comment by makerbase-mks** [comment]
We have plans, and MKS TFT24, MKS TFT32 already support CNC, TFT70 will be gradually improved ...

**Comment by jdelolmosanchez** [comment]
+1 for this request.
Has anyone managed to do it yet? I also want to put my TFT70 in my router.
