### ISSUE TITLE
pausing when print from sd/usb

### ISSUE THREAD

**Issue by OversizedWizard** [makerbase-mks/MKS-TFT#30]
every now and again the printer pauses printing from sd/usb device. waits for temp to reach goal again and carries on.  causes a blob of plastic on print.

i dont get this printing direct from pc.

mkstft 28 version 2.0

**Comment by csikiati** [comment]
check in config below value of EXT0_HEAT_MANAGER to be 1. anyway, I am surprised your printer even works, I don't have settings related to steps/mm or what is below in config file so I have decided to use the simple MKS robin config file, which has these options. What is your secret to make it work?

#Type of heat manager for this extruder.
#- 0 = Simply switch on/off if temperature is reached.
#- 1 = PID Temperature control.
#- 3 = Dead-time control.

>EXT0_HEAT_MANAGER	1

**Comment by makerbase-mks** [comment]
Hello,The plastic on the printer is due to the high temperature of the printer, which makes the consumables melt.
