### ISSUE TITLE
How do I set the pre-heat temperatures under the "heat" button?

### ISSUE THREAD

**Issue by josef** [makerbase-mks/MKS-TFT#300]
Hi, I would like to have the temperatures pre-set to 200 for the extruder and 60 for the bed when hitting the "heat" button on the MKS v3.0.3 TFT how is this possible?

![IMG_4433](https://user-images.githubusercontent.com/139631/55099450-988b1600-50b7-11e9-8019-975e4091c652.JPG)
![IMG_4432](https://user-images.githubusercontent.com/139631/55099451-9923ac80-50b7-11e9-8bb7-f77cf7e0bf32.JPG)
![IMG_4431](https://user-images.githubusercontent.com/139631/55099452-9923ac80-50b7-11e9-99bf-bf8b2c24d4f0.JPG)

**Comment by FranckGib** [comment]
Hello,
you have to create a button and put the corresponding GCODE:
M104 S200; M140 S60;

**Comment by makerbase-mks** [comment]
You can customize the button instructions through the configuration file.

############## Function Customization #######################################

#user-defined function1 and 2.(display this button .  disable: 0; enable: 1)
>cfg_function_btn1_display:1


#command of user-defined function
>function_btn1_cmd:M84;


#set number of  "More" button 
>moreitem_pic_cnt:0

#edit command for 1~7 "More" button,each command must be separated by semicolon ";"
>moreitem_button1_cmd:G28 X0;

>moreitem_button2_cmd:G28 X0;

>moreitem_button3_cmd:G28 Y0;

>moreitem_button4_cmd:G28 Y0;

>moreitem_button5_cmd:G28 Z0;

>moreitem_button6_cmd:G28 Z0;

>moreitem_button7_cmd:G28;

#how many "More" button display on screen interface
>morefunc_cnt:0

#command setting on button1~6
>morefunc1_cmd:G28;
>morefunc2_cmd:G28;
>morefunc3_cmd:G28;
>morefunc4_cmd:G28;
>morefunc5_cmd:G28;
>morefunc6_cmd:G28;

#---------------------------------------------------------------------------------
