### ISSUE TITLE
Disable/enable comunication

### ISSUE THREAD

**Issue by davidcgu** [makerbase-mks/MKS-TFT#304]
There is any command I could use to create a button to enable/disable serial communication between screen and the board?

From other side I remember I think there were only used 4 pins on the connection, 2 for power supply(+5Vdc-0) and 2 for serial (Rx-Tx)  can you be so kind to indicate me which ones for each function?

![image](https://user-images.githubusercontent.com/34965121/55687326-e4697500-596b-11e9-88f0-0dedd2ef2fe3.png)

Thanks in advance

**Comment by makerbase-mks** [comment]
5v and g are for power supply, TX and RX are for serial port transmission.
The screen should not be able to disconnect the serial port by instruction.

**Comment by davidcgu** [comment]
Can you let me know the pinout on the connector?

**Comment by makerbase-mks** [comment]
You can refer to MKS Hardware,like Gen_L and so on
