### ISSUE TITLE
Strange conflict with RAMPS 1.4 USB

### ISSUE THREAD

**Issue by chainreaction** [makerbase-mks/MKS-TFT#31]
Hi!
I'm not pretty sure whose issue it is, RAMPS or MKS TFT, but my MKS TFT can communicate with AUX1 on RAMPS only then RAMPS is connected to PC host via USB. It stops to communicate with RAMPS after I unplug USB or push disconnect button in host software. 

This strange behavior appeared after I re-flashed MKS TFT to V2.0.0 and RAMPS to RC8.
MKS TFT is 1.2 version.

Would be glad to have an advise with direction to dig in.

Thank you

**Comment by makerbase-mks** [comment]
maybe your ramps's power supply have problem(the mega2560's 1117 damage). your ramps connected to pc, the pc give power to ramps via usb, so it can work.
