### ISSUE TITLE
 damaged bootloader boot file

### ISSUE THREAD

**Issue by jmoonle** [makerbase-mks/MKS-TFT#314]
Is it possible to provide a bin file for the bootloader firmware, thank you in advance ?

![](https://pp.userapi.com/c849536/v849536000/180505/mBhuQwXf_ug.jpg)

![](https://pp.userapi.com/c854024/v854024000/32582/fp1qiSMvzXQ.jpg)

**Comment by darkspr1te** [comment]
try my repo at  github.com/darkspr1te for v1 and v4 bootloaders
flash at 0x8000000, firmware bin at 0x8007000

**Comment by maxl95** [comment]
@darkspr1te 
I have the same problem, but i am not able to update the firmware with the bootloader builded myself. After update process only a black screen appears.
