### ISSUE TITLE
Request a SD board slot Option and delay screen option

### ISSUE THREAD

**Issue by se3d** [makerbase-mks/MKS-TFT#32]
Request a SD board slot Option to use or print and a configuration txt for shutdown the usb/sd.
The display has a long delay. Using the tft onboard slot , the printer works better.
So, a external SD and a onboard sd option, is a good option. 
Another idea is a refresh rate for this display. It's a slow reading values.

**Comment by makerbase-mks** [comment]
use onboard sd card  need change a lot. and many function can't be used.
so we have not plan to do this.

**Comment by se3d** [comment]
But is not possible to show the external SD or the display firmware on host when connect on usb (firmware of smoothie)
