### ISSUE TITLE
MKS24

### ISSUE THREAD

**Issue by cheffffe** [makerbase-mks/MKS-TFT#322]
Hi, Just bought the MKS24TFT and I can see the files for Z-Axis exists in the current GRBL mks_pic folder
:
bmp_zAdd.bin
bmp_zDec.bin

How can I activate them to see them on the display? I want to operate the Z-Axis as well.

**Comment by cheffffe** [comment]
Many thanks for the great support. This makes the MKS products GREAT!!! go fuck off ..

**Comment by makerbase-mks** [comment]
Hi! MKS TFT24 has support CNC mode, you can download firmware and update it. link: https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS_TFT_CNC
