### ISSUE TITLE
TFT24 CNC firmware for Marlin

### ISSUE THREAD

**Issue by magnushacker** [makerbase-mks/MKS-TFT#326]
Would it possible to create a Marlin compatible version of the TFT24 CNC firmware? I could add some custom gcode to the menus but would like to also read back some information from the mainboard (e.g execute M114 to see the current position). Would also be good to be able to hide some of the unnecessary menu items (e.g change filament and heat bed options etc).

The CNC firmware may be what I'm looking for but it's only compatible with grbl as far as I can tell.

**Comment by MKS-Sean** [comment]
Yes, currently only compatible with GRBL

**Comment by magnushacker** [comment]
> Yes, currently only compatible with GRBL

Ok, but there are no plans to look into Marlin?

**Comment by makerbase-mks** [comment]
Yes we will collect more information.
