### ISSUE TITLE
No heating info with M105 ADC values enabled

### ISSUE THREAD

**Issue by iotricity** [makerbase-mks/MKS-TFT#335]
When the option to show ADC values with the M105 Gcode is activated in Marlin (#define SHOW_TEMP_ADC_VALUES in configuration_adv.h), the measured temperatures on the TFT28 and TFT32 stays at 0 degrees. The value is correctly set by the MKS Gen L controller. However, since the returned value is zero for the TFT28/32 it will not start printing. After disabling the ADC values in Marlin everything works fine.

Using Marlin 1.1.9 on a MKS Gen L 1.0, with a MKS TFT28 on firmware 3.0.3 (also fails on TFT32 with firmware 3.0.3).

**Comment by makerbase-mks** [comment]
Hi! This problem should be caused after the SHOW_TEMP_ADC_VALUES is turned on, causing the program to wait for a certain command. So, if it doesn't have special features, I suggest not to turn on this option.
