### ISSUE TITLE
Filament Change wrong place on v2.0

### ISSUE THREAD

**Issue by se3d** [makerbase-mks/MKS-TFT#34]
When start to print, the change filament that is inside the set option, is not showed on screen. So, using pause I discovered another bug. The hotend car moves to pause and after continue (resume) the extruder moves together with the car. If pause again, it'll not move, but it will not extrude anymore (just retract and fixed position).

**Comment by makerbase-mks** [comment]
we have fix it  in V2.0.1 please test it .

**Comment by se3d** [comment]
The extruder stop or goes to infinity eject filament. or, if you only make a pause, after resume, the extruder is not working too.

**Comment by makerbase-mks** [comment]
please send email to shelly@makerbase.com.cn  . our engineer will join to solve your problem. thanks

**Comment by se3d** [comment]
thanks. I will do that
