### ISSUE TITLE
Feature request...

### ISSUE THREAD

**Issue by SkipperDo** [makerbase-mks/MKS-TFT#340]
Hi there.. Is it possible to label the "More" buttons via Config File in the next version of Firmware?

e.g.
`
>moreitem_button1_cmd: G28;
>moreitem_button1_label:Homing

>moreitem_button2_cmd: M81;
>moreitem_button2_cmd:Printer Off`

Stuff like this.. This would be a damn cool feature & saves a lot of work..

Kind regards..

**Comment by makerbase-mks** [comment]
The gcode format is more compatible with the configuration of 3d printers.
