### ISSUE TITLE
No booting

### ISSUE THREAD

**Issue by Tuxomx** [makerbase-mks/MKS-TFT#355]
Hi. I have a TFT28 V2.0 with firmware updated some time ago, it was working flawlesly. Today I tried to use it and it only beeps and shows a black screen. I have been unable to update firmware. What can I do to fix this?

**Comment by Stady234** [comment]
have you tried no sdcard in screen.. and only the aux cable connected to board?  What does it do when you try to re-flash the firmware?

**Comment by darkspr1te** [comment]
> Hi. I have a TFT28 V2.0 with firmware updated some time ago, it was working flawlesly. Today I tried to use it and it only beeps and shows a black screen. I have been unable to update firmware. What can I do to fix this?

You can reflash bootloader and firmware using simple uart tool(ramps board,arduino,buspirate) and guides from my github, https://github.com/darkspr1te

**Comment by makerbase-mks** [comment]
Hi! Has this issue been resolved?
