### ISSUE TITLE
MKS TFT35

### ISSUE THREAD

**Issue by jacquesderobert** [makerbase-mks/MKS-TFT#358]
I cannot obtain the last firmware the rar is corrupted ;where can  i found it?

**Comment by aokiakagome** [comment]
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT3.5

**Comment by FrankyMaker** [comment]
Many thanks, but please read what he has written !

The RAR File is corrupted and can't be opened

(It is very sad that this was already posted here 26 days ago without reaction and new upload of the file)

**Comment by makerbase-mks** [comment]
The mistake of our work, we have re-uploaded
