### ISSUE TITLE
"cfg_state_bkcolor" element does not exist

### ISSUE THREAD

**Issue by MarshMalloW0007** [makerbase-mks/MKS-TFT#359]
Hello, everyone.
I'm busy creating my skinpack and I found an error in the configuration file "mks_config.txt".
The "cfg_state_bkcolor" element does not exist in the FW while it is in the configuration file.
You must replace "cfg_state_bkcolor" by "cfg_state_color" so that the background color of the temperature, fan, (etc) elements can be changed.

If Makerbase needs help writing its documentation, I can help.

Sincerely
Marsh

![Sceen01_Lo](https://user-images.githubusercontent.com/45604136/71131069-ecb0ca00-21f3-11ea-802d-35ce0c750cd6.png)
![Screen02_Lo](https://user-images.githubusercontent.com/45604136/71131022-c723c080-21f3-11ea-9e5a-cc3e7b1fd6ca.png)

**Comment by makerbase-mks** [comment]
We will test this feature and fix it in version 1.0.3. Currently version 1.0.3 is being tested ...

**Comment by MarshMalloW0007** [comment]
I can help in testing the firmware.

**Comment by makerbase-mks** [comment]
Welcome to test the new firmware.
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT3.5
