### ISSUE TITLE
TFT35 with Fysetc S6

### ISSUE THREAD

**Issue by dbemowsk** [makerbase-mks/MKS-TFT#361]
So I have an MKS TFT35 that I would like to try to use with a Fysetc S6 board. The S6 board does not have an aux1 port, but it does have a UART1 port that provides serial communication. My question is, can I just connect the +5, GND, RX and TX to the UART port to make it work or is it crucial to have the other 2 data pins from the TFT35 display connected for it to function correctly? My understanding of the pinout on the 8 pin connector of the TFT35 is this:

+5 | GND | RXD | TXD
+5 | GND | Dxx | Dyy

I am not sure of the function of the Dxx and Dyy pins on the display.

**Comment by dbemowsk** [comment]
I opened this issue 17 days ago and still have had no response.  I am simply trying to find out the function of the 2 extra data pins on the main 8 pin IDC connector (not the wifi connector).  I would like to get full functionality from this display using it with my Fysetc S6 controller, but can't without knowing the operation of those two pins.

**Comment by makerbase-mks** [comment]
The TX and RX pins on the MKS TFT35 are the transmit and receive pins of the serial port. You can connect to the serial RX and TX pins of your Fysetc S6 motherboard. If necessary, we can provide you with the schematic diagram of the MKS TFT35.

**Comment by dbemowsk** [comment]
My question wasn't about the TX and RX pins.  There are 8 pins, 2 of them are GND and 2 are +5V.  I want to know what the two pins opposite the TX and RX pins are used for.

**Comment by dbemowsk** [comment]
Can SOMEONE respond to this.  My initial post on this was on Christmas day.  This is frustrating and should be a simple response from someone that knows the function of the pins on the MKS TFT35.

**Comment by makerbase-mks** [comment]
+5V  GND  RX   TX
+5V  GND  NC  NC

**Comment by NoPinky** [comment]
@dbemowsk 
so, have you ever made the S6 work with the TFT35? If yes, how?
Thank you

**Comment by dbemowsk** [comment]
Yes. I had to make an adapter to connect the 8 pin IDC connector on the S6 to the soak port on the TFT.  You need yup connect TX on one too the RX on the other, and vice versa. Plus the 5V and GND of course.

**Comment by C3P0-SF** [comment]
Can you show what this looks like? I'm assuming you used AUX 1 on TFT to the UART 4-pin on the S6 board.

**Comment by dbemowsk** [comment]
C3P0-SF, here is the basic wiring needed.
![fysetc_s6_mks_tft](https://user-images.githubusercontent.com/2935181/129463648-fb2e9021-b212-4927-82f7-739d23e44c56.png)
 
At the TFT35 end I have an 8 pin IDC connector like this.
![mks_tft_idc](https://user-images.githubusercontent.com/2935181/129463669-e92bb1fd-3d34-4104-a476-358db65db702.jpg)

Then to plug into the Fysetc S6 side I just put a dupont connector for mine, but you can use one of the polarized dupont style connectors that comes with the S6 board.  I separated every other wire on the ribbon cable to get the wires I needed.  Check and double check with a continuity tester.
![mks_tft_dupont](https://user-images.githubusercontent.com/2935181/129463702-740855a0-9851-4dc5-befc-028579cf0056.jpg)

Then in the firmware you need to define a second serial port in your config.h.  I don't have the firmware handy at the moment to paste in what I changed, but I'm sure you can figue it out if you read on configuring a second serial port.

**Comment by C3P0-SF** [comment]
Thank you. That's what I thought. Turns out my motherboard was a dud and the serial ports didn't work


    On Sunday, 15 August 2021, 11:01:16 GMT+10, dbemowsk ***@***.***> wrote:  
 
 


C3P0-SF, here is the basic wiring needed.


At the TFT35 end I have an 8 pin IDC connector like this.


Then to plug into the Fysetc S6 side I just put a dupont connector for mine, but you can use one of the polarized dupont style connectors that comes with the S6 board.


Then in the firmware you need to define a second serial port in your config.h. I don't have the firmware handy at the moment to paste in what I changed, but I'm sure you can figue it out if you read on configuring a second serial port.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dbemowsk** [comment]
Good luck.
