### ISSUE TITLE
Control buzzer

### ISSUE THREAD

**Issue by LordBBQ** [makerbase-mks/MKS-TFT#363]
Is there a way to manually control the buzzer on the screen?

**Comment by VegetableKingdom** [comment]
This may be controlled by his bootloader. For me, the easiest way. Remove the buzzer

**Comment by LordBBQ** [comment]
What I mean is a way to send a code command to control the buzzer.

**Comment by makerbase-mks** [comment]
This part of the function, we will add on the TFT screen, you can choose the buzzer switch function.

**Comment by LordBBQ** [comment]
Thanks
