### ISSUE TITLE
Customization of screens and background

### ISSUE THREAD

**Issue by MarshMalloW0007** [makerbase-mks/MKS-TFT#368]
Good morning all.
I am busy creating my skinpack for a TFT 35 and I have a problem with a background.
All the parameters in the mks_config.txt for the backgrounds are set to white.
Also, the text for the Z remains white.
![TFT35_Printing](https://user-images.githubusercontent.com/45604136/72259036-cc680580-360f-11ea-862c-8af0bafd674c.png)

Sincerely
Marsh

**Comment by Error26** [comment]
Can you give your configuration file? I'm try to help you.

**Comment by MarshMalloW0007** [comment]
##--------------------------------------------------------------------------------
######Display Customization(button and logo customized see User's Manual) #######

#the color of
##screen background
>cfg_background_color:0xFFFFFF

##title text
>cfg_title_color:0x000000

#the color of temperature, fan,(etc) 
##background
>cfg_state_bkcolor:0xFFFFFF
>cfg_state_color:0xFFFFFF

##text
>cfg_state_text_color:0x000000

#the color of file
##button
>cfg_filename_bkcolor:0xFFFFFF

##text
>cfg_filename_textcolor:0x000000

#the color of general button
##background
>cfg_btn_bkcolor:0xFFFFFF

##text
>cfg_btn_textcolor:0x000000

#the color of status button
##background
>cfg_state_btn_bkcolor:0xFFFFFF

##text
>cfg_state_btn_textcolor:0x000000

#the color of "back" button
##background
>cfg_back_btn_bkcolor:0xFFFFFF

##text
>cfg_back_btn_textcolor:0x000000

#the color of selected button
##background
>cfg_sel_btn_bkcolor:0xFFFFFF

##text
>cfg_sel_btn_textcolor:0x000000

#the color of dialog button
##background
>cfg_dialog_btn_bkcolor:0xFFFFFF

##text
>cfg_dialog_btn_textcolor:0x000000

**Comment by makerbase-mks** [comment]
This is a firmware issue, I can fix it today and upload new firmware.

**Comment by makerbase-mks** [comment]
Welcome to test the new firmware.
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT3.5
