### ISSUE TITLE
"New feature required."The MKS TFT35 das not can control the heating chamber.

### ISSUE THREAD

**Issue by Error26** [makerbase-mks/MKS-TFT#369]
The MKS TFT35 is unable to control the heating of the camera. Is it possible to do this in some way? 
MKS TFT35 and others send command "M141 S" and "M191 S" with G-coge to MKS board. But on display MKS TFT35 i dont see and dont can control the temperature of hotting chamber. On PC and the other display "LCD 12860" i see the temperature and can control the temperature.

**Comment by makerbase-mks** [comment]
Hi! First, We need to ensure that the baud rate of the motherboard and the screen are the same so that the motherboard can receive instructions and execute normally.
