### ISSUE TITLE
2.0.1 not working with mks sbase

### ISSUE THREAD

**Issue by se3d** [makerbase-mks/MKS-TFT#37]
The new firmware is not work propely insert sdcard on slot a lot of icons (icluding a custom icons) on display and a motor of can be found into two places. One is rebooting the display. The infinite change filament In or out was not fixed too. The stop button can't stop the infinite in or out.

**Comment by makerbase-mks** [comment]
Hello my dear friend,
i would like to know more problem details and try to solve it,
would you please take some photos and send to me?
here is my mail
shelly@makerbase.com.cn

**Comment by makerbase-mks** [comment]
thanks

**Comment by salcofago** [comment]
IT WORKS FINE FOR ME

**Comment by se3d** [comment]
I will make a video and show you the problem, ok?

**Comment by makerbase-mks** [comment]
OK,you can send to the mail:shelly@makerbase.com.cn
