### ISSUE TITLE
It's possible access cam by MKS TFT?

### ISSUE THREAD

**Issue by biroli3d** [makerbase-mks/MKS-TFT#375]
Hi,
It's possible you connect usb cam in tft screen and access through Wifi by MKS Wifi?

![image](https://user-images.githubusercontent.com/59924124/72667063-9a331b00-39f6-11ea-8cac-d2d63f204ea1.png)

![image](https://user-images.githubusercontent.com/59924124/72667169-85a35280-39f7-11ea-9142-1540a6422668.png)

**Comment by Operrr** [comment]
No
