### ISSUE TITLE
Configure TFT 2.4 for latest repetier with MKS Base V1.4

### ISSUE THREAD

**Issue by adamhaze8** [makerbase-mks/MKS-TFT#378]
Hi, I'm currently trying to use a TFT 2.4 with my MKS Base V1.4 running the latest repetier firmware, but I'm unsure of if or how the TFT firmware needs to be configured for this to work, since I have it connected via AUX 1 and it turns on but does not send commands. Any tips would be great!

**Comment by makerbase-mks** [comment]
Hi! You don't need to modify the TFT firmware, but the only thing we need to do is to ensure that the baud rate of the TFT is the same as the motherboard firmware setting in order to maintain communication.
