### ISSUE TITLE
MKS-TFT35 status screen

### ISSUE THREAD

**Issue by dereik** [makerbase-mks/MKS-TFT#379]
is there any way to get an info / status display fpr the TFT35.
i would like to see the bed an hotend temp at the same time.
for the TFT32 there is an retro firmware but not for the TFT35

**Comment by makerbase-mks** [comment]
Hi! Currently, there is only one style of MKS TFT35, and we will collect more needs and evaluations.

**Comment by gizmocuz** [comment]
I would love to see this option too ! This should be the default home screen after bootup
With a Abort/Stop button would be nice

I think this is the same as this issue

https://github.com/makerbase-mks/MKS-TFT/issues/292

If possible please reopen that one

**Comment by tschork** [comment]
Yeah, that would be nice to have.
I just installed my tft35 today and was surprised not to find a screen like this.
