### ISSUE TITLE
GRBL $H command in tft24 

### ISSUE THREAD

**Issue by Srferrete** [makerbase-mks/MKS-TFT#383]
I am trying to configure the $ H command on my screen using the firmware for cnc, but I don't know if this command is compatible.

Or substitute "home" button (g28) with the $ H command

Any ideas?

thanks

**Comment by fireflylr** [comment]
The tft24 CNC firmware has a custom button, if you need to add instructions to the screen, you can configure the file ' 'mks_config.txt to modify the instructions of the custom button.
                                                                                                       ---mks
