### ISSUE TITLE
About z-offset

### ISSUE THREAD

**Issue by Bradley-Liu** [makerbase-mks/MKS-TFT#389]
Thanks for you prompt action. I've updated to the 1.05 version firmware. Now babystepping is working perfectly. However, i still got one recommendations for you. In tools->more->z-offset settings, the firmware still got z-offset displayed at 0. It is inconsistent with the babystep setting. I hope you can fix that in the following firmware. Thansk!

**Comment by makerbase-mks** [comment]
Hi！ The firmware v3.05 has fix it.
