### ISSUE TITLE
New GUI themes for MKS-TFT3.5 is available

### ISSUE THREAD

**Issue by ghost** [makerbase-mks/MKS-TFT#391]
I adapt (and extend) majurca MKS-TFT2.8 theme for MKS-TFT3.5 display. Dark, black and light themes available. [Link to repository](https://github.com/DenisShelema/MKS-TFT3.5-light-and-dark-themes). Feel free to put this link anywhere you want.
P.S. Please, open source code for display. Proprietary code is huge disadvantage this days. Your main competitor clearly understand this already.

**Comment by makerbase-mks** [comment]
The interface is beautiful, I will add this connection in the readme of the MKS TFT project, thank you very much! MKS TFT code has been open source, you can refer to the corresponding Tft code ...
