### ISSUE TITLE
TFT35 compiled but black screen

### ISSUE THREAD

**Issue by karabas2011** [makerbase-mks/MKS-TFT#398]
I am able to compile tft35 project ( under IAR 8.30 )
Display is booting as usual but black screen after.
my tft35 is marked as V1.0 version hardware
Need I edit something in code? I am not familiar with IAR
I prefer PlatformIO

There are plenty of warnings
Is your code ready to complie at all? Did you try it yourself?

Log file in attach
[BuildLog.log](https://github.com/makerbase-mks/MKS-TFT/files/4551938/BuildLog.log)

Factory built firmware reflashed and works

**Comment by karabas2011** [comment]
mks_config.txt does NOT  rename to CONFIG.CUR

**Comment by el-quique** [comment]
Hi. Link to IAR software. Thx

**Comment by karabas2011** [comment]
> Hi. Link to IAR software. Thx
https://www.iar.com/iar-embedded-workbench/#!?architecture=Arm

**Comment by karabas2011** [comment]
firmware does not work
I tried IAR versions 8.30, 7.60, 7.10
What I missed?

**Comment by el-quique** [comment]
hi. any tutorial to compile with IAR. Thx

**Comment by karabas2011** [comment]
Open Workspace: Go to EWARM folder in mkstft35 folder and open workspace
You will see code tree.
Now make /clean/rebuild 
The result is in EWARM/mkstft35/Exe/ folder

It seems that they use IAR 7.0
since  IAR 8.11 compiler is changed and possibly incompatible

**Comment by el-quique** [comment]
In MKS TFT 28/32 the code is different. Thank you

**Comment by karabas2011** [comment]
Got it working. You need these steps https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware/wiki/How-to-build-update-nano-firmware

**Comment by onichan88** [comment]
It worked, but with which version of IAR?

**Comment by karabas2011** [comment]
7.1, 7.5 works

**Comment by karabas2011** [comment]
closed

**Comment by venkatkamesh** [comment]
@karabas2011  can you share the iar 7.1 or 7.5 link ?
really appreciated for your help

Thank you

Edit: - solved
