### ISSUE TITLE
Status Screen

### ISSUE THREAD

**Issue by EberleG** [makerbase-mks/MKS-TFT#4]
Can you add a status screen that shows the current Z, X and Y, Hotend temp, Bed temp?  Or open up the source code so someone else can?

**Comment by Steamerzone** [comment]
A status screen is also one thing that I'm missing, so much so that I'm considering going back to a 12864 LCD screen. Please consider adding it, or let someone else do it by opening up the source.

**Comment by pmbroth** [comment]
Please give a status screen, it is needed!!!

**Comment by AlexDoran** [comment]
I added a separate issue for this and another item, but this needs to be done or have the source code released, i have also sent them a message on Aliexpress.

Alex

**Comment by aimartin** [comment]
It would be really awesome if they release the code, but honestly, I don't think they will do it :(.

+1 in this!

**Comment by AlexDoran** [comment]
Guys, after some searching i have stumbled onto this guy's project who has been rebuilding the firmware himself, its seriously worth checking out:

https://hackaday.io/project/18852-alternative-firmware-for-mks-tft32

**Comment by pmbroth** [comment]
He is just changing the button images, and added a few M commands for the leveling buttons.  I have this.  nothing else is going on, unfortunately  at this time.   I really want the status screen, such that I ordered an 12864 screen to have that as my status display, while using this to control the printer

**Comment by aimartin** [comment]
I saw that project, and I've subscribed to it, although I don't think is mature enough... if you plan to use the screen as source for controlling the printer (executing gcode), not sure if that is trustable or not... However, is really interesting indeed, let see :)

**Comment by AlexDoran** [comment]
@pmbroth I think he is rebuilding the firmware using his own source code, the images can be replaced using the standard firmware.

@aimartin Yes it appears to be in the early stages, maybe if there is enough interest diverted to the page it could be an incentive for him to really get it going. I wish i had the knowledge myself to undertake such a task.

**Comment by pmbroth** [comment]
ok cool, then I misspoke.  Apologies!

**Comment by makerbase-mks** [comment]
we will add this function  in V2.0 before 17.2.20. thanks

**Comment by AlexDoran** [comment]
Excellent news, thanks for taking our feedback on board. Can't wait to try it out.

Alex

**Comment by pmbroth** [comment]
Excellent News!!!  Can you look into the pausing issue that many are having when printing from sd card when having a filament sensor connected.

**Comment by makerbase-mks** [comment]
maybe the filament sensor send wrong signal.

**Comment by pmbroth** [comment]
If you look at the open issue for pausing, it seems it is not related to one printer, but several that are trying to use this feature.

**Comment by snoerenberg** [comment]
Hi, when will the firmware 2.0 be released? On 17.02. I could not find any new FE here.

Thanks

**Comment by AlexDoran** [comment]
King Zhong at MKS has sent me the new firmware, i can email it to you if you'd like.

Thanks

**Comment by snoerenberg** [comment]
Can you upload it to zippyshare or something?
Thanks

**Comment by makerbase-mks** [comment]
we have upload at: MKS-TFT/Firmware/MKS-TFT_V2.0.0English.zip; use  red or blue style 's retro firmware.
Add some new function,the datasheet is traslating, and will be upload after some day.

**Comment by pmbroth** [comment]
The new screen is great!  Keep up the good work!
