### ISSUE TITLE
2.0.0 Filament change leaves printer in absolute extrusion distances mode

### ISSUE THREAD

**Issue by VisualGadget** [makerbase-mks/MKS-TFT#40]
I use relative extrusion distances and filament change breaks the print workflow. After this operation extruder goes back and forth repeatedly and extrudes nothing.

**Comment by se3d** [comment]
A similar problem with me and the issues here: https://github.com/makerbase-mks/MKS-TFT/issues/34

**Comment by makerbase-mks** [comment]
Hi! At present, the firmware of the MKS TFT series is relatively stable.
