### ISSUE TITLE
PB0 as filament runout sensor?

### ISSUE THREAD

**Issue by onichan88** [makerbase-mks/MKS-TFT#405]
Hello, The TFT is preconfigured to use PB0 for power off recovery with UPS, and PB1 with filament runout sensor.

I have a IDEX 3d printer (with 2 extruders and 2 noozles, and my question is that if it can configure the PB0 as a PB1 for the second extruder, as I won't use the power off recovery with UPS?

Regards

**Comment by fnhhnxfn** [comment]
hi if you want to use two filament sensor simultaneously you can buy trianglelab filament runout sensor

**Comment by makerbase-mks** [comment]
Hi! I suggest you still use the recommended pin.

**Comment by onichan88** [comment]
I want to use two filament runout sensor, one per extruder. So if one is getting without pla, it should cold that extruder after regret the pla. If the second is getting without pla, it should cold the second extruder.

So, to differentiate both filament runout sensors, it must have two different pinouts.

This is why i want to use pb0 as a second filament runout sensor.

**Comment by makerbase-mks** [comment]
Perhaps the original program does not allow this operation, but you can modify the firmware yourself, we have open sourced the code.
