### ISSUE TITLE
TFT 24 - Electric diagram

### ISSUE THREAD

**Issue by Bubolz** [makerbase-mks/MKS-TFT#410]
Where do I find the wiring diagram to see the available pins?

**Comment by fireflylr** [comment]
The available pins of tft24 should be available in the product details
--mks

**Comment by Bubolz** [comment]
Sorry! Still can't find it. Can you please post a link to the document here on github? Thanks!

**Comment by DivingDuck** [comment]
too much redwoods in the forest :)
https://github.com/makerbase-mks/MKS-TFT-Hardware

**Comment by makerbase-mks** [comment]
You can refer to MKS TFT hardware Schematic diagram
