### ISSUE TITLE
Icons missing after firmware update

### ISSUE THREAD

**Issue by phongshader** [makerbase-mks/MKS-TFT#419]
I updated tft3.5 from 1.0.2 to 1.0.7 and several things went wrong. Boot image is corrupted, icons are missing and it didn't update to 1.0.7 but to 1.0.6. I tried re downloading, downgraded to 1.0.5 didn't fix anything. Marlin printer firmware...?

![tftboot](https://user-images.githubusercontent.com/38082624/84320929-45b84580-ab27-11ea-91bf-bb17b40f0b13.jpg)
![tftIcons](https://user-images.githubusercontent.com/38082624/84320931-4650dc00-ab27-11ea-965d-e439febf8965.jpg)
![tftRev](https://user-images.githubusercontent.com/38082624/84320924-43ee8200-ab27-11ea-9519-7a5f6277b64b.jpg)

**Comment by phongshader** [comment]
I found this, https://github.com/makerbase-mks/MKS-TFT/issues/274, but not sure what this means 

> Ok , problem solved with :
>`cfg_multiple_language:1`

my mks_config.txt does contain that line

**Comment by fireflylr** [comment]
Sorry, the firmware version number in TFT35_V1.0.7 Release file.zip has forgotten to be modified, but the function is more than 1.0.6 to add a function that supports the "UPS" power failure detection module; the picture display error should be that the picture has not been updated. , My test here is no problem you said, please update the image file.
--mks

**Comment by phongshader** [comment]
> please update the image file.
>
What files do I update?
What about missing icons?

**Comment by fireflylr** [comment]
mks_pic

**Comment by phongshader** [comment]
Icons?

**Comment by phongshader** [comment]
I downloaded several mks_pic folders TFT35_V1.0.2, 1.0.5, 1.0.6,1.0.7, TFT70_V1.0.7 all with the same result...no icons, corrupted boot screen image

**Comment by phongshader** [comment]
I've tried loading firmware from examples from v1.0.2 and 1.0.5...still no icons. Where can I download image2lcd? all the download links I found no longer link to the program.

**Comment by fireflylr** [comment]
Can your screen be displayed normally before? Is it abnormal after updating the firmware?

**Comment by phongshader** [comment]
> Can your screen be displayed normally before?
>
when I received it it worked great , I was very happy with it. 

>  Is it abnormal after updating the firmware?
>
I updated the firmware and everything disappeared, no Icons, corrupted boot screen.

**Comment by fireflylr** [comment]
Have you tried formatting your sd and copying the relevant files to update the firmware?
--mks

**Comment by phongshader** [comment]
I found the problem, I was using a Mac to load firmware onto the sd card, I switched to a pc and all is good and working. Something you may want to test and put in documentation.
