### ISSUE TITLE
Retro in Version 2.0.1 32english not work

### ISSUE THREAD

**Issue by GaryK47** [makerbase-mks/MKS-TFT#42]
Hello!
It will only update the images but not the firmware. The file name is incorrect. If you change the filename from mkstft24.bin to mkstft28.bin, the upload works and the display only shows "Booting ...".

**Comment by makerbase-mks** [comment]
Are you used hardware of MKS TFT24?

**Comment by GaryK47** [comment]
I use MKS TFT3.2_L V.2.0.

**Comment by ovsel43** [comment]
On MKS TFT 28 version 2.0 also does not work.
When updating the display, the process reaches 100% and hangs. After rebooting the display hangs on the "booting..."

**Comment by ovsel43** [comment]
Please upload English firmware 2.0.1 retro for tft 28 and 32.

**Comment by ovsel43** [comment]
Retro firmware from the archive "TFT28 32 简体 中文 V2.0.1.zip" works fine on my TFT.
In "TFT 28 32English2.0.1.zip" the retro firmware is not for that display.

**Comment by makerbase-mks** [comment]
We will updat it in today.

**Comment by makerbase-mks** [comment]
We have updated it.
