### ISSUE TITLE
TFT32&35 no Connects

### ISSUE THREAD

**Issue by chapi1es** [makerbase-mks/MKS-TFT#420]
I managed to configure marlin for this MKS Sbase and it works very well with an lcd, but with the TFT32 and TFT35 I do not get it to work, it seems that it does not communicate with the sbase. A help please, thanks Ahhh I tried marlin 2.0.5.3 as 2.0.x.x

**Comment by makerbase-mks** [comment]
You need set #define SERIAL_PORT_2 0 in configuration.h file.

**Comment by chapi1es** [comment]
> 
> 
> You need set #define SERIAL_PORT_2 0 in configuration.h file.

Muchas gracias era eso, ya solucionado 👍
