### ISSUE TITLE
TFT7.0 Does not communicate with mks SGen L 32bit board

### ISSUE THREAD

**Issue by Demitryk** [makerbase-mks/MKS-TFT#429]
TFT is flashed to the newest firmware 1.0.7. Running marlin 2.0 with the latest bug fix on an MKS SGen L 32bit board. Have tried all baud-rates. Tried two different cables.  Printer will not respond to TFT.

Is there something i need to modify in the marlin firmware.

**Comment by Switchcrafter** [comment]
I had the same issue.  I updated Marlin to 2.0.5.4  and flipped the serial ports around in configuration.h 

//#define SERIAL_PORT -1
#define SERIAL_PORT 0

//#define SERIAL_PORT_2 0
#define SERIAL_PORT_2 -1`

Also my baud-rate is 250000 for both devices.  fyi
TFT is on v3.0.5

good luck

**Comment by Demitryk** [comment]
That fixed it, Thank you!
