### ISSUE TITLE
mks 2.8 usb odn't read

### ISSUE THREAD

**Issue by patacco** [makerbase-mks/MKS-TFT#43]
hi, i've tried with many usb sticks but it seems it not function. i've choosen usb in filesystem menu , but it seems it not read ... any suggestion?

**Comment by makerbase-mks** [comment]
there is the file system in the option of set.do you set it of udisk?

**Comment by nemocaledonie** [comment]
As Patacco but on a 3.2 TFT, the screen can't read my udisk, and I already do the change on SET.FILES.
I'm using the latest firmware 2.0.1 English and Marlin 1.1.x

**Comment by makerbase-mks** [comment]
Some usb drives are unsupported and we suggest replacing the udisk.

**Comment by nemocaledonie** [comment]
Ok I'll try another udisk. Thanks for the reply

**Comment by kiar8** [comment]
I apologize for my english
I have a tft 3.2 display with the latest version of firmware downloaded from this site and marlinkimbra works everything but when i need to print from sd or usb card it does not work
