### ISSUE TITLE
MKS TFT35 stop comunicating

### ISSUE THREAD

**Issue by fr4231gm** [makerbase-mks/MKS-TFT#439]
The touchscreen stops comunicating randomly to my Robin e3d board, that makes stop prints at mid or stop send orders to de printer. Software version 1.0.7.

**Comment by fr4231gm** [comment]
Please I need help :(

**Comment by makerbase-mks** [comment]
Hi! What is your settings baudrate? If use 250000, you can try to setting to 115200.

**Comment by fr4231gm** [comment]
Ok thank you! But now I have other problem, I have calibrated the touch screen and now doesnt work, maybe because I didnt calibrate it in the good way, how can I reset that calibration?

**Comment by fr4231gm** [comment]
Solved. Thanks

**Comment by makerbase-mks** [comment]
Can you share your problem solving process？I hope that more users can solve the same problem like you.

**Comment by fr4231gm** [comment]
Hi! I have done some long prints, about 10 hours with the MKS and it worked perfectly. The problem of the calibration was solved re-updating the firmware of the TFT, and the problem of the connection, IDK how, but, I connected my other screen to the printer too because I couldnt work with the MKS TFT and I connected too the SD Card in the Robin e3, and when I connected both things, the MKS started to work perfectly, I know that this has no sense, but magically worked for me xD. Thanks for everything!

**Comment by fr4231gm** [comment]
And I have to say that I didnt change the baudrate. It still using 250000

**Comment by makerbase-mks** [comment]
@fr4231gm 
OK, then I will close this question temporarily.

**Comment by acca84** [comment]
@fr4231gm, i think i have the same problem with MKS SGEN L V1.0 :  https://github.com/makerbase-mks/SGEN_L/issues/46
Do you have a dual hotend setup ? because i can print with one hotend but not two, print stops without reason.
did you find a workaround for using only the TFT35 ?
thanks
