### ISSUE TITLE
MKS Robin TFT35 v1.0

### ISSUE THREAD

**Issue by doon3** [makerbase-mks/MKS-TFT#442]
MKS Robin TFT35 v1.0 has a difference MKS TFT35 v1.0? MKS Robin TFT35 v1.0 firmware v1.0.7 works for me bad... - icons are displayed crookedly, labels are not displayed

**Comment by makerbase-mks** [comment]
Yes, there is have difference. MKS Robin TFT35 is just a simple display screen, it needs to be used with Robin Nano V1.2 motherboard, MKS TFT35 is just a serial screen

**Comment by doon3** [comment]
Thank. is the MKS-TFT firmware right for me MKS Robin TFT35 v1.0 ?

**Comment by makerbase-mks** [comment]
No, MKS Robin Nano firmware is right for youf MKS Robin TFT35, link: https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
