### ISSUE TITLE
TFT35 PRINT PREVIEW

### ISSUE THREAD

**Issue by Yetreyert** [makerbase-mks/MKS-TFT#445]
good morning everyone how can i solve this problem? generates it with each image

![IMG-20200817-WA0012](https://user-images.githubusercontent.com/68908146/90787100-a8d30f00-e304-11ea-84a0-527a3e6ae1b9.jpeg)

**Comment by makerbase-mks** [comment]
Can you try to update agian?

**Comment by Gorkag3d** [comment]
Hi!
It happened the same to me, I applied the solution proposed at:

The model preview in does not work correctly. (Cura version 4.4.1, plugin version 1.0.2) #11

https://github.com/Jeredian/mks-wifi-plugin/issues/11

And it worked for me.
