### ISSUE TITLE
[ThemePort] MKS-TFT2.4-dark-theme

### ISSUE THREAD

**Issue by scmanjarrez** [makerbase-mks/MKS-TFT#447]
Hi everybody,
If you like the DenisSchelema dark-theme, I have made a port for TFT2.4.
You can find it here: https://github.com/scmanjarrez/MKS-TFT2.4-dark-theme

**Comment by makerbase-mks** [comment]
looks great

**Comment by KillSwitch422** [comment]
Thanks for the idea, I decided to port to a red theme specific for Laser version.
No multi language yet
[https://github.com/KillSwitch422/MKS-TFT24-Laser-CnC](url)

**Comment by mks-viva** [comment]
@scmanjarrez Thank you very mach. I will close this issues temporarily.
