### ISSUE TITLE
TFT32 Hardware Issue

### ISSUE THREAD

**Issue by SkipperDo** [makerbase-mks/MKS-TFT#451]
Can you please offer TFT32 v3.0 Schematics & maybe a board view file?
I currently have an TFT32 V3.0 with a burned component & want to repair it..
Thank you...

**Comment by makerbase-mks** [comment]
OK!

**Comment by makerbase-mks** [comment]
You can refer to : https://github.com/makerbase-mks/MKS-TFT-Hardware/tree/master/MKS%20TFT32_L%20V3.x
