### ISSUE TITLE
MKS TFT35 not communicate with MKS DLC in laser mode grbl

### ISSUE THREAD

**Issue by ksdfpr** [makerbase-mks/MKS-TFT#452]
Hello, 
My problem is that FT35 not communicate with MKS DLC in laser mode grbl. I have changed firmare in DLC already and in TFT (v1.0.2) also. Both works fine but without any communication among them. I have check the baudrate to 3 in config file (115200) according to DLC baud rate but nothing. Any idea?

**Comment by makerbase-mks** [comment]
Use laser TFT firmware?

**Comment by ksdfpr** [comment]
Yes, the file MKS_TFT35_laser_V1.0.2 Release file.zip

**Comment by makerbase-mks** [comment]
I think your GRBL has lock, you need send $X unlock it, you can use pronterface connect DLC motherboard check it.

**Comment by ksdfpr** [comment]
I checked it. No reaction

**Comment by ksdfpr** [comment]
... and while I have installed this  file MKS_TFT35_laser_V1.0.2 Release file.zip, in the About menu says "MKS TFT_35_LASER VERSION 1.0.1 
The MKS DLC v2.0 is flashed with the v1.1h via arduino IDE
(and please change the word "conected" with "connected")

**Comment by ksdfpr** [comment]
Any other suggestion?

**Comment by ksdfpr** [comment]
FINALLY!
 The problem: is the auto lock function is enable when grbl starts up. If you have a pc connected, its not a problem, just send a $X command and after that the communication with TFT works. But if you dont have a pc connected to send this command, the communication betweeen DLC and TFT is not working.
The answer: in the config.h  file in grbl you can comment HOMMING_INIT_LOCK  or autohoming on boot, (not the best solutions both...)

**Comment by makerbase-mks** [comment]
So, MKS TFT35 Laser needs to add the unlock command button.

**Comment by ksdfpr** [comment]
Yes, I have checked it. If you press some buttons, the communication stops for some seconds, so it must be on the first screen.
There is missing a home button also (to reach limits, not hom to origin)
Also please correct the "conect" with "connect"
Thank you

**Comment by bouba830** [comment]
avez vous réussi car je me retrouve avec le même problème

**Comment by mks-viva** [comment]
@ksdfpr The latest version has fix it. So, i will close this issues temporarily.
