### ISSUE TITLE
Fan Half speed Icon does not send a command

### ISSUE THREAD

**Issue by JimmymaDdness** [makerbase-mks/MKS-TFT#454]
In my MKS TFT28, I have loaded a forked version of the Firmware.  
The icon button for Fan0 Full speed works, as well as the Fan0 Stop, but I can't get the Fan Half Speed to send the command to turn the fan to half speed.  
How do I change what command is send when the Half speed Icon is pressed?

**Comment by makerbase-mks** [comment]
About FAN speed :
Full speed : M106 S255
Half speed : M106 S127
Close : M106 S0 or M107

**Comment by mks-viva** [comment]
Hi! If have not response, i will close this issues temporarily.
