### ISSUE TITLE
TFT35 booting problem

### ISSUE THREAD

**Issue by hardy8** [makerbase-mks/MKS-TFT#460]
I wanted to update a new logo today, but after inserting the SD card the display only keeps showing "booting", nothing else happens anymore, what can do to get it working again.

Hardy

**Comment by appliedmike** [comment]
is the SD card FAT32 formatted? , have you checked that there is a 'mks_robin_nano35.bin' file or is it a .CUR ?

**Comment by hardy8** [comment]
It has now been resolved, tried several SD cards, also formatted, but after putting in and out many times, it started loading.
Thanks

**Comment by makerbase-mks** [comment]
@appliedmike Thank you
