### ISSUE TITLE
mks tft35 + mks wifi не печатает через wifi  

### ISSUE THREAD

**Issue by dima925925** [makerbase-mks/MKS-TFT#461]
mks tft35 + mks wifi не печатает через wifi. подключается к сети, но telenet не может подключится к порту 8080.

**Comment by mks-viva** [comment]
Hi! Can you provide your MKS TFT35 config file to me and i will check it and it is ok？

**Comment by dima925925** [comment]
проблемма решена. заменил mks wifi модуль на новый. Всё работает

**Comment by mks-viva** [comment]
Haha OK! Thank you for your support to MKS. I will close this issues temporarily.
