### ISSUE TITLE
SOURCE CODE NEEDED: For translate in Italian, german and change the layout.

### ISSUE THREAD

**Issue by kekko7072** [makerbase-mks/MKS-TFT#465]
Hey, i really love MKS SOFTWARE touch screen and are perferct. But now i want ti implement and make It perfect, so  Is It possibile to have the source code ti edit it?  Id like to help the european community adding the Italian lenguage and for mi self changing the layout.

**Comment by kekko7072** [comment]
@makerbase-mks

**Comment by makerbase-mks** [comment]
Hi! Readme has link
![image](https://user-images.githubusercontent.com/12979070/95425373-c15fbd00-0976-11eb-9f76-ccad93995c47.png)

**Comment by kekko7072** [comment]
Thank you so much
