### ISSUE TITLE
Multi-Extruder Control Request

### ISSUE THREAD

**Issue by paloky** [makerbase-mks/MKS-TFT#467]
Hi MKS Team.
This is a request for a multiple extruders.

I have designed an expansion board for MKS Gen 1.4 to get 4 extra extruders.
I need control this 4 extruders from TFT.

With Marlin 2.0 Firmware works fine the control of my expansion board. (4 extra motor control, 4 extra NTC Sensors, 4 extra Heaters).
But I can't control this with TFT.

I see many request for this enhanced.
Please, can you consider making this improvement?

Thank a lot.

**Comment by mks-viva** [comment]
I’m sorry, there is no firmware that supports 4 extruders yet

**Comment by mks-viva** [comment]
I will close this issues temporarity
