### ISSUE TITLE
CNC Firmware for TFT70

### ISSUE THREAD

**Issue by Primer-Merc** [makerbase-mks/MKS-TFT#473]
Can I use this firmware?  If not can you recommend what to use?

MKS_TFT35_CNC_V1.0.2 Release file.zip 

Thanks!

**Comment by Primer-Merc** [comment]
Glad to see this is getting a lot of attention, what a great purchase......... * insert sarcasm *

**Comment by mks-viva** [comment]
Sorry, it cannot be used on MKS TFT70.

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
