### ISSUE TITLE
[theme / skin] TFT 35

### ISSUE THREAD

**Issue by bilou24an199** [makerbase-mks/MKS-TFT#475]
hello,

i want to change the std skin of my tft 35.
i have downloaded the application MKSTOOL which is a great solution to update the theme or to make a custom theme

in the standard position of your github

https://github.com/makerbase-mks/MKS-TOOL

a new theme is proposed = mks_picdiy

this theme is gorgeous, but there is only one pb = in the menu "HOME" =

![image](https://user-images.githubusercontent.com/39101542/99187207-86129400-2755-11eb-819d-803c3086bba0.png)

the icon is not appearing for the "HOME" button is it a software bug or is this button icon is missing in the distribution ?

please can you provide th ICON to have a complet theme

Best regards

**Comment by bilou24an199** [comment]
Ok i compare 2 folders = the folder of the std theme and the folder of diy theme
the button icon which is missing call =
bmp_zeroA.bin

for a first solution, i duplicate the bmp_zero.bin and i rename it = bmp_zeroA.bin

 it is may be not the good icon, but now, no icon is missing.

is it possible to have the photoshop files, because i would like and custom button (more button) and to match with the theme (blue button with black bckground and colored dots) it will be usefull to have the original files

thank in advance

best regards

**Comment by bilou24an199** [comment]
some other std icons are missing =

the icon for file system =
- bmp_usb.bin
- bmp_usb_sel.bin

and may be more,

please put the archive from this skin (in illustrator or photoshop or other native files) in the TFT design UI

BR

**Comment by mks-viva** [comment]
Thank you for your feedback, I will report this issue with our engineer.

**Comment by mks-viva** [comment]
You can try to use it config: https://www.baizhongyun.cn/home/mkstoolview

**Comment by bilou24an199** [comment]
hello i have not use your link but thank you for your help

i send you a zip file on email _**4164049@qq.com**_

with my "adaptation" of the mks_picdiy

i want to deposite it on the github but no access to do that or not found the mean to do that

BR
