### ISSUE TITLE
Mks ts35???

### ISSUE THREAD

**Issue by AlexejLach** [makerbase-mks/MKS-TFT#477]
I want to buy MCS TS35! but I do not understand how to print there is no sd or usb connector! where to stick sd?

**Comment by AlexejLach** [comment]
And another question, is there an image of the printed model on the tc35 screen

**Comment by mks-viva** [comment]
Hi! 
MKS TS35 can be use to MKS Robin Nano V2 and supported MKS UI, Marlin UI, Marlin 12864 style
MKS TS35 can be use to MKS SGEN_L V1/V2 and supported Marlin UI, Marlin 12864 style
So, MKS TS35 only a display screen and read tf card from motherboard

**Comment by AlexejLach** [comment]
I still don't understand if it can show the image of the model?

**Comment by mks-viva** [comment]
Of course, but you need use MKS UI style.
