### ISSUE TITLE
Mks tft 32 cnc update error

### ISSUE THREAD

**Issue by ascarons22** [makerbase-mks/MKS-TFT#478]
tft 32 1.02 update file gives sd error in 82%, tested with several cards, a solution?

**Comment by mks-viva** [comment]
Hi! Can you provide a video for me?

**Comment by ascarons22** [comment]
[
[mks.zip](https://github.com/makerbase-mks/MKS-TFT/files/5561878/mks.zip)

](url)

**Comment by ascarons22** [comment]
Inside the zip is the video, it always hangs at the same point, tested with several cards.

**Comment by mks-viva** [comment]
Is the SD card formatted?

**Comment by ascarons22** [comment]
yes, formatted in fat32, with the 3d printer file it works, with version 1.0 it works, with version 1.02 always error in 82%.

**Comment by mks-viva** [comment]
I will communicate this issue with our engineer.

**Comment by kapsko** [comment]
im having same thing happen any update

**Comment by secondstar1** [comment]
> I will communicate this issue with our engineer.
Any feedback from engineer? I have the same issue.

**Comment by MKS-Sean** [comment]
@ascarons22 Hi,I think I solved this problem, just update to the latest firmware
#498
