### ISSUE TITLE
mks tft 35 stopped seeing the board

### ISSUE THREAD

**Issue by AlexejLach** [makerbase-mks/MKS-TFT#480]
mks tft 35 stopped seeing the board. everything was fine yesterday, but today he does not see her. I flashed the screen and checked the cable, nothing helps

**Comment by AlexejLach** [comment]
https://github.com/makerbase-mks/MKS-TFT/issues/218
obsalyut the same problem as in this branch but there is no solution please help

**Comment by onsc** [comment]
Same problem here. I think uart is broken.

**Comment by mks-viva** [comment]
Most likely, the problem lies in the serial port circuit

**Comment by onsc** [comment]
> Most likely, the problem lies in the serial port circuit

Should we replace chip or wait to another firmware ? What do you think?

**Comment by mks-viva** [comment]
It is difficult for me to find out exactly where the problem lies, because I don’t have similar hardware, but you can refer to MKS TFT35 hardware.
https://github.com/makerbase-mks/MKS-TFT-Hardware/blob/master/MKS%20TFT35/MKS%20TFT35%20V1.0_003/MKS%20TFT35%20V1.0_003%20SCH.pdf

**Comment by onsc** [comment]
serial ports connected to directly stm chip. So is it possible only that pins are broken?
i connected to Arduino mega. And used multi serial. Same baudrate. And clicked some printer command buttons. Nothing shows.at Arduino side. is it good method to test stm serial? Thank you.

**Comment by mks-viva** [comment]
This is serial hardware on mks tft35
STM32 PB11 RXD connect to AUX-1 RXD
STM32 PB10 TXD-1 connect to D9(Level conversion chip) , D9 TXD connect to AUX-TXD
![image](https://user-images.githubusercontent.com/16629551/99934746-d4e5ac80-2d99-11eb-9882-90b75fde6df2.png)

**Comment by onsc** [comment]
> Level conversion chip

Thank you very much for your interest. I just realized that level conversion chip. What do  you suggest me to check or any check method to analyze ? 
Maybe problem is the conversion chip ...

**Comment by mks-viva** [comment]
D9 is : SN74LVC1T45DCKR
If firmware settings is OK. I think there is a high probability that D9 is not working properly, which leads to communication failure.

**Comment by onsc** [comment]
> D9 is : SN74LVC1T45DCKR
> If firmware settings is OK. I think there is a high probability that D9 is not working properly, which leads to communication failure.

Thank you mks-viva. I ll try to replace in a week. I think firmware has right configuration and OK.

**Comment by mks-viva** [comment]
OK! Good luck for you.

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.

**Comment by onsc** [comment]
Sorry for big delay. i couldn't get that part in that form. So i couldn't tried. Thank you.
