### ISSUE TITLE
ERROR 404 - MKS TFT35 DenisShelema's 3.5 inch ui 

### ISSUE THREAD

**Issue by AldoI** [makerbase-mks/MKS-TFT#481]
has anyone kept this "DenisShelema's 3.5 inch UI theme"?
Unfortunately the user has deleted the github account and is no longer available for download

**Comment by mks-viva** [comment]
@AldoI 
Haha! You may need to ask on facebook, the answer will be faster.

**Comment by scmanjarrez** [comment]
Look at this fork: https://github.com/alexws54tk/MKS-TFT3.5-light-and-dark-themes

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
