### ISSUE TITLE
TFT 35 Laser Screen

### ISSUE THREAD

**Issue by newjoke** [makerbase-mks/MKS-TFT#482]
does the TFT35 laser screen run with Smoothieware?
I got the 3D printer version running but not the laser screen!

**Comment by mks-viva** [comment]
Hi! The current MKS TFT35 laser firmware only supports GRBL mode and cannot be used to smoothieware directly.

**Comment by mks-viva** [comment]
I will close this issues temporarily.

**Comment by djnatalino** [comment]
HI! There are updates?
