### ISSUE TITLE
TFT32 - After update to V3.0.6 no Heat Bed is showing up

### ISSUE THREAD

**Issue by BenediktS** [makerbase-mks/MKS-TFT#483]
I just updated my "MKS TFT32_L V3.0" to the firmware version v3.0.6 . 
After the update the heating bed is not showing up anymore. 

It is not showing up in the pre heat screen nor in the printing screen.
In my configuration file this are the hotbed lines:

>cfg_custom_bed_flag: 1     # Please choose  1:Enable bed  0:Disable bed
>cfg_max_hotbed_temperature: 150     # The max target temp of heated bed
 
Did i miss something?

**Comment by mks-viva** [comment]
Hi! You can check your baudrate settings in your config file.

**Comment by BenediktS** [comment]
I checked it. 
It is the same baudrate  that is configured on the marlin board.

I could see the sprayer temperature and can use it. 
I can also print without problems. 
I could only not see the hotbed.  

Is the sprayer temperature using a different communication then the hotbed?

**Comment by mks-viva** [comment]
Marlin firmware have config hotbed?

**Comment by BenediktS** [comment]
I have to update the firmware i will get back to you. I think i can test it next weekend.

**Comment by mks-viva** [comment]
Waiting for your good news

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.
