### ISSUE TITLE
MKS TFT 43 V1.0

### ISSUE THREAD

**Issue by JoergHub** [makerbase-mks/MKS-TFT#488]
[hello](

> [url](https://www.facebook.com/twotrees3Dprinter/community/?ref=page_internal
)

) my dispaly of my Two Trees bluer plus is not working properly it only shows lines. can anyone help me who knows the error thank you

**Comment by mks-viva** [comment]
Hi! I want to know. have you performed any operations?

**Comment by JoergHub** [comment]
Firmware update

**Comment by JoergHub** [comment]
where do you get the firmware for the tft 43 v1.0 ??

**Comment by mks-viva** [comment]
MKS Robin TFT43 firmware: https://github.com/makerbase-mks/MKS-Robin-Nano-V1.X/tree/master/Nano%20firmware%20v1.x.x/nano43

**Comment by mks-viva** [comment]
I will close this issues temporarily.
