### ISSUE TITLE
MKS TFT35 V1.0 CNC firmware not communicate with Arduino CNC shield V3

### ISSUE THREAD

**Issue by RepRapThailand** [makerbase-mks/MKS-TFT#489]
Hello,

I can move motor with GRBL sender but not with TFT35.

GRBL Firmware
https://github.com/gnea/grbl/releases/download/v1.1h.20190825/grbl_v1.1h.20190825.hex
******************************************************************************************************

TFT35 CNC
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS_TFT_CNC/MKS_TFT35_CNC_V1.0.2%20Release%20file.zip

![1606699384157](https://user-images.githubusercontent.com/15525407/100559599-d0634b80-32e5-11eb-84db-7d3bd271a6c0.jpg)

*******************************************************************************************************

Show "connected"  but not connected to the Arduino CNC shield.

![35813](https://user-images.githubusercontent.com/15525407/100559952-e3c2e680-32e6-11eb-8787-e7db29093dd4.jpg)

**Comment by mks-viva** [comment]
Hi! 
GRBL default baudrate is 115200
Your TFT set baudrate is 115200
So, your firmware settings is ok!
Now, we need check connect of MKS TFT35 to CNC shield V3
MKS TFT35 AAUX-1 need connect to CNC shield V3's TX RX GND 5V
![image](https://user-images.githubusercontent.com/16629551/100567266-0bc04300-3303-11eb-8414-de9864f4e0d0.png)
![image](https://user-images.githubusercontent.com/16629551/100567475-8721f480-3303-11eb-82ef-0e3f21610e1d.png)

**Comment by RepRapThailand** [comment]
![35841](https://user-images.githubusercontent.com/15525407/100571312-707c9d00-3305-11eb-936a-32f464d0157e.jpg)

![35842](https://user-images.githubusercontent.com/15525407/100571323-770b1480-3305-11eb-9455-bea972517a62.jpg)

![35843](https://user-images.githubusercontent.com/15525407/100571336-7c685f00-3305-11eb-81fc-9b52ece8dc10.jpg)

**************************************************************************************************************************

from TFT35
TX      Brown
RX      RED
GND  Orange
5V      Yellow

**Comment by mks-viva** [comment]
You need change connect:
MKS TFT35 TX connect to CNC shield V3's RX
MKS TFT35 RX connect to CNC shield V3's TX

**Comment by RepRapThailand** [comment]
ok, success!
Sorry for the stupidity.
ขอบคุณมาก

**Comment by Sergii2602** [comment]
Я так і не зрозумів підключив но мотори не реагують.чи потрібно ще залити прошивку в ардуїно ?

**Comment by StephenWillis2** [comment]
Thank you, I needed this info a lot.
