### ISSUE TITLE
WIFI TFT Exception

### ISSUE THREAD

**Issue by nemocaledonie** [makerbase-mks/MKS-TFT#49]
Hi, On my TFT (V2.0.1 English) the TFT WIFI module make an error :"Exception" . I try to upload the MksWIFI.ino.bin without success, still same error.

**Comment by makerbase-mks** [comment]
Are you sure your phone is connected to "MKS_wifi"?

**Comment by nemocaledonie** [comment]
Of course ! and the password « makerbase ».



De: makerbase <notifications@github.com>
Répondre: makerbase-mks/MKS-TFT <reply@reply.github.com>
Date: 2 septembre 2017 at 14:26:57
À: makerbase-mks/MKS-TFT <mks-tft@noreply.github.com>
Cc: Nemocaledonie <nemocaledonie@yahoo.fr>, Author <author@noreply.github.com>
Sujet:  Re: [makerbase-mks/MKS-TFT] WIFI TFT Exception (#49)  

Are you sure your phone is connected to "MKS_wifi"?
