### ISSUE TITLE
tft 35

### ISSUE THREAD

**Issue by Yetreyert** [makerbase-mks/MKS-TFT#490]
hi all
mks cfg screen display mode 0

I'm making a firmware starting from the mks base. where can I find this parameter? I would like the 8 icon configuration and all the display settings (classic mode is defined by mks tools)

**Comment by mks-viva** [comment]
Is there a duplication? https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware/issues/138

**Comment by mks-viva** [comment]
Hi! If have not response, i will close this issues temporarily.
