### ISSUE TITLE
MKS TFT35 CNC V1.0.2

### ISSUE THREAD

**Issue by nikki-m** [makerbase-mks/MKS-TFT#491]
Have downloaded MKS TFT35 CNC V1.0.2 to my Makerbase TFT35 board, which I want to configure for CNC use. 
However, there appears to be no z axis control available.
Have I downloaded the latest firmware or have I chosen the wrong files?
Also, what is involved in changing the x and y direction arrows to something more 'sensible' - ie which actually reflect the direction the spindle is moving in. Such as straight up, straight down, left and right. Rather than the diagonal arrows used at the moment.

**Comment by mks-viva** [comment]
Hi! Like this, you need copy all to SD card and insert to MKS TFT35 and update it
![image](https://user-images.githubusercontent.com/16629551/101300034-264c6c00-386f-11eb-817b-ffd81528bba1.png)
![image](https://user-images.githubusercontent.com/16629551/101300091-601d7280-386f-11eb-8ebb-aeafdfd2c908.png)
![image](https://user-images.githubusercontent.com/16629551/101300101-67dd1700-386f-11eb-854c-e32b79119d4d.png)
good luck for you

**Comment by mks-viva** [comment]
I will close this issues temporarily

**Comment by Gareth-Green** [comment]
Hello mks-viva and other members who may be able to help me. 

Unfortunately, I am having the same issue as nicky-m. 

I am very new to this and only received my MKS TFT32_L V4.0 in the post this week. 

I want to be able to control a desktop CNC 3018-Pro with it. 

I have tried to download the correct firmware but I don't have access to the Z axis and in the about section on the device, it is still listed as a TFT32_LASER.

The main issue though is the Z axis.  I would appreciate any help or a link to the correct firmware... as I said I'm very new at this... and learning as I go along. 

Thank you for help with this. 

Gareth
