### ISSUE TITLE
no images after setup

### ISSUE THREAD

**Issue by fvhohnhorst** [makerbase-mks/MKS-TFT#492]
i need help with setting up the MKSTFT 2.4 V1.1

when i upload via an SD-Card the firmware, everything is working, except there are only white square where the images should be.
![1](https://user-images.githubusercontent.com/75643009/102014774-04b02080-3d58-11eb-8a44-670113f38ca6.jpg)

**Comment by mks-viva** [comment]
You need recopy mks_pic and update it
![image](https://user-images.githubusercontent.com/16629551/102034992-4ee9de00-3dfa-11eb-918f-28b052970db7.png)

**Comment by fvhohnhorst** [comment]
tried that, but still there are no images shown...

**Comment by mks-viva** [comment]
Can you tell me which firmware and version you downloaded?

**Comment by fvhohnhorst** [comment]
downloaded the TFT24_V3.0.6 Realase file

**Comment by DivingDuck** [comment]
Don't know if you had check this: 
You need to have a complete set of directories and files including mkstft24.bin and mks_config.txt at the same time on the sd-card. The pic-files  will only be uploaded if the config file with correct naming is available and is not called like config.cur / mkstft24.cur. All files have to follow the original naming conventions and locations. No renaming is allowed.

**Comment by fvhohnhorst** [comment]
This is on the card before setting it up
![Unbenannt](https://user-images.githubusercontent.com/75643009/102858119-02ba2180-442a-11eb-828f-5a47f2950e51.JPG)

**Comment by fvhohnhorst** [comment]
![Unbenannt](https://user-images.githubusercontent.com/75643009/102858185-241b0d80-442a-11eb-88b1-a34cabdc5fcd.JPG)

**Comment by fvhohnhorst** [comment]
This is on the sd Card before setting it up

**Comment by fvhohnhorst** [comment]
![1](https://user-images.githubusercontent.com/75643009/102858238-35641a00-442a-11eb-900b-2277ff81a1fa.jpg)

**Comment by fvhohnhorst** [comment]
after testing the fans, all of the images are changed

**Comment by fvhohnhorst** [comment]
![2](https://user-images.githubusercontent.com/75643009/102858343-65abb880-442a-11eb-8a67-0b208ecd2ec8.JPG)

**Comment by fvhohnhorst** [comment]
this is after setting it up

**Comment by DivingDuck** [comment]
Maybe I'm wrong, but shouldn't the file name of mks_config.txt also change to config.cur if it has been successfully processed?

**Comment by mks-viva** [comment]
@fvhohnhorst 
I think the motherboard does not actually read the SD card. If it can be read, then all the files will be renamed. I suggest you can try and test it with another card

**Comment by fvhohnhorst** [comment]
thanks for your help, with another sd card it finally worked
