### ISSUE TITLE
tft35 laser feature request

### ISSUE THREAD

**Issue by llocken45** [makerbase-mks/MKS-TFT#493]
it would be nice to have config settings in menu and g code command prompt

**Comment by mks-viva** [comment]
Hi! Can you give me an example, for example...

**Comment by llocken45** [comment]
The updates that came out on v1.0.7 but for the laser and cnc versions 
Added g code console
Added features to machine settings 
Its easy to change using g code commands but it would be nice to have settings similar to the firmware used for 3d printers

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 18, 2020 at 3:58 AM, mks-viva<notifications@github.com> wrote:   


Hi! Can you give me an example, for example...

**Comment by mks-viva** [comment]
Thank you for your feedback, I will communicate this feature with our engineers.
