### ISSUE TITLE
Video support for CNC users.

### ISSUE THREAD

**Issue by LancingBiker21** [makerbase-mks/MKS-TFT#495]
Hi Guys.,Could you make an instructional video using a TFT3.5 display and driver board (MKS DLC) running a CNC machine? That is NOT a 3D printer or lazer cutter and using the latest firmware available- just to prove it can be done! 
You advertise on AliExpress and claim that the TFT 3.5 is capable of doing this a lot of buyers would like to see it I'm sure.
Thanks , LB

**Comment by mks-viva** [comment]
Hi! You need settings
1. GRBL set CNC mode
2. MKS TFT35 config set CNC mode and firmware use https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS_TFT_CNC/MKS_TFT35_CNC_V1.0.2%20Release%20file.zip
![image](https://user-images.githubusercontent.com/16629551/103469930-61768800-4da6-11eb-9fdb-66892b3adf9a.png)

**Comment by LancingBiker21** [comment]
Hi, Thanks for your quick response... I will try to reload the firmware as per your example and get back to you with the results. Would be good if you could provide some screen shoots of the CNC GUI for reference so I know what to expect.

**Comment by mks-viva** [comment]
Thank you for your feedback. We will receive suggestions from more users.

**Comment by condigia** [comment]
> Thank you for your feedback. We will receive suggestions from more users.

However, TFT 35 Having problems reading files .nc . if DLC connect PC run ok. fix it
