### ISSUE TITLE
MKS_TFT32_laser_V1.0.2 82% update error

### ISSUE THREAD

**Issue by secondstar1** [makerbase-mks/MKS-TFT#498]
Hi,

There is an issue with MKS_TFT32_laser_V1.0.2 firmware while updating from SD card, Update process stucks with message "SD ERR" at 82% progress. The same SD card works perfect with TFT28_32_v3.0.6 firmware, update process successfully finished with it. The issue only with Laser/CNC firmware. 
I use MKS TFT28 v1.2 display. Playing with different SD card/FAT-FAT32/... doesn't help to solve an issue.

**Comment by secondstar1** [comment]
I was able to update TFT28 with MKS_TFT32_CNC_V1.0.1 firmware successfully. So the issue in 1.0.2 firmware indeed.

**Comment by MKS-Sean** [comment]
@secondstar1 Hello, I have updated the firmware. This problem is caused by the difference between the new version and the old version. It can be solved by updating to the latest firmware.

**Comment by ascarons22** [comment]
yeahhh,works

**Comment by mks-viva** [comment]
So，I will close this issues temporarily
