### ISSUE TITLE
more custom menus

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [makerbase-mks/MKS-TFT#50]
please provide:
1) more custom menus entry points, i.e. on the home screen
2) custom section similar to "fan control", where it is possible to increment/decrement a custom parameter

**Comment by makerbase-mks** [comment]
In the mks_config.txt file, you can configure instructions in "# command setting on button1 ~ 6" to control the fan.

**Comment by Andrei-Pozolotin** [comment]
yes, and this is very limited functionality
