### ISSUE TITLE
How to MKS DLC with TFT35 and TMC2208

### ISSUE THREAD

**Issue by asarmelin** [makerbase-mks/MKS-TFT#507]
I'm looking for tutorial to integrate Makerbase MKS DLC (v2.0) motherboard with MKS TFT35 display (v1.0) and TMC2208 stepper driver (v1.2).
I updated the TFT35 firmware for laser (MKS TFT35_LASER v1.0.3) because laser is my goal.
When on, MKS DLC with red LED on and blue LED flashing. MKS TFT35 "disconnected".
XLoader does not recognize the port for MKS DLC (Windows 10).

**Comment by mks-viva** [comment]
You can only use the standard mode of TMC2208
