### ISSUE TITLE
Mks_WIFI.ino.bin ??? and Changing filament button

### ISSUE THREAD

**Issue by nemocaledonie** [makerbase-mks/MKS-TFT#53]
Hi, In the directory /Red style/Classic/ you have a file (and only in this folder) Mks_WIFI.ino.bin, so when I'm updated my TFT,  I copied this file too in the SD card, except now the WIFI don't working any more.
How I can go back to the original configuration ? (i've still "EXCEPTION" in the WIFI menu).

Second question : how you can change the filament when you printing ? no button or something like that. Only when the printer don't work (It's not very helpful, because you can do it manually and faster)

**Comment by makerbase-mks** [comment]
what is the version of your firmware?

**Comment by nemocaledonie** [comment]
Ver. 2.0.1 English.

**Comment by makerbase-mks** [comment]
We're testing it here and it's working. Are you sure your phone is connected to "MKS_wifi"?

**Comment by nemocaledonie** [comment]
Of course ! and the password "makerbase"

**Comment by makerbase-mks** [comment]
We have released the latest firmware V3.0.0, you can  download and update it.

**Comment by cruwaller** [comment]
What's new in 3.0? Bug fixes? Readme is not updated...

**Comment by nemocaledonie** [comment]
Thanks for the 3.0.0. Now I can change the filament (no trying yet but the button is on the screen), and the "exception" has gone...
