### ISSUE TITLE
TFT32 Not working

### ISSUE THREAD

**Issue by murdock62** [makerbase-mks/MKS-TFT#54]
Hello,
I encounter a problem with the screen.
When I connect it it just beep beep, beep, beep, beep beep ... But the screen remains black.
To eliminate a connection problem I replaced it with the screen of one of my other machine and everything works.
Could you help me please?
Many thanks !
Best regards.
François.

**Comment by makerbase-mks** [comment]
what is the version of your firmware and hardware?

**Comment by murdock62** [comment]
Hardware version 2.0. Firmware dont know, the screen never work.

Many thanks for your help.

**Comment by makerbase-mks** [comment]
Doesn't the screen show "booting"?

**Comment by murdock62** [comment]
Nope. Anything on the screen.
Only continuous beep beep.

**Comment by makerbase-mks** [comment]
Where your stuff is bought, you can contact customer service and they will help you.

**Comment by mks83** [comment]
Same exact problem here, can somebody please post an outcome

**Comment by makerbase-mks** [comment]
Maybe you should contact sales staff to replace this screen.

**Comment by Lugosol** [comment]
In some boards like mine,the MKS Gen L the TFT header is inverted, cut border of the connector so it fits in "wrong" inverted position. I thought: That can't be it, I'm going to fuse something... Nope.
Actually you are connecting it already inverted if you don't change it...
Hope it helps.
