### ISSUE TITLE
MKS DLC V2.0

### ISSUE THREAD

**Issue by davisalan** [makerbase-mks/MKS-TFT#547]
I just purchase MKS DLC V2.0 Board for my Atomstack A5 Laser. But I don't see any differences as an upgrade from original LaserBox V1.0. Wondering anyone try this board. Even functions are same, Grbl Laser version is the same. Confused. I think this is the replacement only not an upgrade. Both boards connecting to MKS TFT35 with success. İs this waste of money or what.
![IMG20210621155350](https://user-images.githubusercontent.com/12734107/122766232-f6fcca00-d2a9-11eb-83d0-0cc62cc7f1e1.jpg)
![IMG20210621155402](https://user-images.githubusercontent.com/12734107/122766244-fa905100-d2a9-11eb-8fcd-e0cacfd92563.jpg)

**Comment by mks-viva** [comment]
Only DC power interface
