### ISSUE TITLE
and the French ?

### ISSUE THREAD

**Issue by nemocaledonie** [makerbase-mks/MKS-TFT#57]
Hi, in your newest firmware, in /Red Style/Retro/mks_pic I found "bmp_french.bin and bpm_french_sel.bin but nowhere in config file. Do you know how I can using the "french" possibility ?
Obviously I'm french :-)

**Comment by makerbase-mks** [comment]
Our TFT does not supported French, and another product, Robin, has French.

**Comment by nemocaledonie** [comment]
Too bad ... :-( maybe later ?

**Comment by makerbase-mks** [comment]
Yes,we will consider it.

**Comment by nemocaledonie** [comment]
Nice :-)
