### ISSUE TITLE
TFT32 input is reversed

### ISSUE THREAD

**Issue by thejordanclark** [makerbase-mks/MKS-TFT#63]
On my MKS TFT32_L v1.0 with firmware V3.0.0  the input is mirrored.  If I click on the right side it registers the click on the left side.  All input is mirrored left <-> right.   Is there a way to reverse that?

**Comment by makerbase-mks** [comment]
When and where did you download this firmware?

**Comment by thejordanclark** [comment]
I downloaded it from GitHub,  This repo on 8/31.  So just over a month ago.

https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT2.8-3.2/Firmware/TFT28%2032_V3.0.0_English.zip

I have tried a few of the varients, currently it is loaded with "Red style" -> Retro

**Comment by Math1010** [comment]
Same problem !
Have you find a solution ? 
Thanks

**Comment by thejordanclark** [comment]
Unfortunately no, from what I can tell this has to be something in the firmware.  What version of the MKS TFT32 do you have?  Mine is a v1.0.  I also have a friend that also has a v1.0 that is doing the same thing.

To date I have never actually got my TFT32 "working" because of this.  It actually had this problem when I got it over a year ago.. at the time I shelved it and just recently dug it back out hopping that these issues would have been resolved.   If the code was released for this I would be happy dig through and see if I can come up with a solution.  Until it get's fixed or the firmware code is released so we can help my TFT32 is basically useless.

**Comment by nargos** [comment]
Same problem with my v1.0 MKS TFT32 display.

:-(

**Comment by makerbase-mks** [comment]
you can change the hardware of  TFT32_L V3.0

**Comment by thejordanclark** [comment]
@makerbase-mks Are you saying we can change or V1.0 TFT32 to a V3.0?  Do you have details about what the changes are?

**Comment by crbertilson** [comment]
Same problem here please elaborate on the solution.

**Comment by thejordanclark** [comment]
I still have yet to find a solution.  I updated to the newest firmware released a couple month ago and it still has the same issue.  I would like to know how "you can change the hardware of TFT32_L V3.0" as stated by makerbase-mks.

**Comment by thejordanclark** [comment]
Is there no option for us that have MKS TFT32_L v1.0 on any current version of the firmware then?   You mentioned changing our "MKS TFT32_L v1.0" to "TFT32_L V3.0" but no response of how that is possible.

Any help would be appreciated.  Basically I currently have to touch the opposite section of the TFT32_L when ever I need to use it.

**Comment by makerbase-mks** [comment]
@thejordanclark
 Have you updated the firmware？The new firmware cannot directly support the old version of the hardware, mainly because the hardware does not support it, we are sorry!
