### ISSUE TITLE
MKS TFT32 firmware?

### ISSUE THREAD

**Issue by naviathan** [makerbase-mks/MKS-TFT#65]
All the firmware files are labeled as mkstft28.bin. Why are there no mktft32.bin?

**Comment by makerbase-mks** [comment]
TFT28 and TFT32 use the same file name.

**Comment by zen** [comment]
Why do you keep this issue opened?

**Comment by naviathan** [comment]
I'm not doing anything

**Comment by zen** [comment]
It's a question for @makerbase-mks ;)
