### ISSUE TITLE
TFT32 Retro not working on any style and language

### ISSUE THREAD

**Issue by mdogancay** [makerbase-mks/MKS-TFT#68]
I tried to update my tft 32 with retro type of main screen but all retro types not updating and not
booting. After update images on update, stuck on "complated" message. After restart stucking on "booting..." screen.
I tried all retro type ROMs and no one works.

any ideas ?

**Comment by Ganriber** [comment]
I have not worked too! Please correct, this is the most comfortable style...

**Comment by Ganriber** [comment]
Filled new firmware, downloaded, installed and now working!

**Comment by mdogancay** [comment]
@Ganriber Confirmed. Working on my TFT too.
