### ISSUE TITLE
Additional Feedback / Status Screen - Feature Requests

### ISSUE THREAD

**Issue by AlexDoran** [makerbase-mks/MKS-TFT#7]
Hi there, 

I really like the TFT32 but i was wonder if it was possible to add some additional functions to its software. If i had a decent knowledge of coding i would attempt this myself.

First of all i think it would be nice for the Screen to Boot into a 'Status Screen', this would show the Current Temps / Fan Speed / Axis Positions (Much like the LCD RAMPS Screens do), from here you could navigate to the main menu.

Also, when a print is active it is really useful to be able to see current Axis positions, Especially the Z / Layer Height.

Are these features that could possibly be added?

Thanks

Alex

**Comment by makerbase-mks** [comment]
we will add Temps/Z axis to status  in V2.0  .
thank you.

**Comment by AlexDoran** [comment]
Perfect, Thank you.

Alex

**Comment by nitr8** [comment]
Am i blind or is there no status in V2.0 @makerbase-mks

**Comment by makerbase-mks** [comment]
MKS-TFT/Firmware/MKS-TFT_V2.0.0English.zip; use red or blue style 's **retro f**irmware.

**Comment by makerbase-mks** [comment]
Please use: MKS-TFT/Firmware/MKS-TFT_V2.0.0English.zip; use red or blue style 's  **retro** firmware.

**Comment by murdock62** [comment]
Hi, is it possible to have the Status screen in all the style specially in classic please ?

Many thanks !

François.
