### ISSUE TITLE
MKS TFT28 fw V3 PROBLEM

### ISSUE THREAD

**Issue by Ditrow** [makerbase-mks/MKS-TFT#71]
today I updated my fw mks ftf28 on ramps with version fw 1.2 it was all in line
after updating fw on V3 win8 display stopped reacting where to look for problem i'm in the end I need to print and it does not work me
for every advice I thank you

**Comment by makerbase-mks** [comment]
I tested it with tft28_v3.0.0 in English and did not detect the problem.
