### ISSUE TITLE
MKS TFT32 Filament Runout sensor does not beep

### ISSUE THREAD

**Issue by martind-n** [makerbase-mks/MKS-TFT#76]
After triggering filament runout sensor, printing pauses but there's no alert. No beep, nothing.
As far as I could see on some youtube tutorials, it should start beeping until user fills up new filament.
Does anybody else have seen this behavior? 
I'm running Marlin 1.1.3 and TFT V3.0.

Thanks.
Martin.-

**Comment by makerbase-mks** [comment]
We tested the version of TFTV3.0.0, and the buzzer would ring.

**Comment by martind-n** [comment]
Mine doesn't... And the buzzer works fine because it beeps on power on.
Any sugestion?

**Comment by makerbase-mks** [comment]
where did you download the firmware?

**Comment by makerbase-mks** [comment]
You can connect PB0 and GND, and if TFT32 is normal, the buzzer will ring

**Comment by martind-n** [comment]
This is how I connected it but nothing happens... The printing stops but there's no sound alerting...
