### ISSUE TITLE
When replacing the fillament, the extruder motor is standing

### ISSUE THREAD

**Issue by edwardjanecek** [makerbase-mks/MKS-TFT#77]
Hi, I have a fiber exchange problem. The sensor works, and the printer moves away from printing according to the settings. The signal beeps. But if I change the ejecting thread, I will graphically display Unloading on the display, but nothing happens physically. The same problem is with Loading Fibers, and the engine is physically stood. The fiber exchange temperature is OK. Version 3.0 TFT 28.

**Comment by makerbase-mks** [comment]
You can update the latest firmware, which is currently a stable version.
