### ISSUE TITLE
mks tft32 v2.0 firmware update scrambled buttons

### ISSUE THREAD

**Issue by scooterharrell** [makerbase-mks/MKS-TFT#81]
I updated my firmware to the latest and now all of my buttons look scrambled I've tried to revert back to V2 did not help

**Comment by makerbase-mks** [comment]
anything pictures?

**Comment by makerbase-mks** [comment]
you can update the firmware of v3.0.1

**Comment by thejordanclark** [comment]
I don't know if it is related but I had a similar issue when I updated my firmware using a Mac to write the files to the SD card.  Something is messed up with how the Mac wrote the bin file to the SD card and how the MKS-TFT reads it which broke all the images.  I fixed mine by using a linux box in my case to write the files to the SD card.

**Comment by makerbase-mks** [comment]
Where did you download the firmware and images.

**Comment by makerbase-mks** [comment]
Where did you download the firmware and images?
