### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by atolala** [makerbase-mks/MKS-TFT#82]
Hi

I'm a recently user with your MKSTFT32, for me all work correctly but i like the possibility to show X and Y coordinate when playing files, and when make Move function.

But in other way if you can diplay all time X Y Z at the bottom of the screen this is i think really usefull.

I think the job is not really hard to do, you have already Z displayed in Move menu.

Many thanks for great job

**Comment by atolala** [comment]
When play files Z coordinate display Z reading from actual  readed line  from sdcard ? 
I think this is better to display actual Z position of the extruder . (and adding X and Y please)

**Comment by makerbase-mks** [comment]
this is display the Z position of printer.
