### ISSUE TITLE
Issues with MKS 32TFT connected to MKS Gen v1.4

### ISSUE THREAD

**Issue by d2xhale** [makerbase-mks/MKS-TFT#83]
I'm having issues all the sudden with the MKS 32 TFT (LCD control panel) not sending code to the board. The printer currently will move using Pronterface linked using USB no problem. The MKS 32 TFT will power fine and respond to my touch browsing through menus but will not send code to the board. This problem just started and nothing has changed from when it last worked to now, Is there anyway to isolate the problem to help with problem solving?

**Comment by zagranichnyy** [comment]
Repetier firmware?

**Comment by makerbase-mks** [comment]
Is it normal to use it before?

**Comment by d2xhale** [comment]
Using the latest Marlin firmware. Yes the panel was working perfect previously

**Comment by wbarber69** [comment]
do you have the baud rate set properly?

**Comment by wbarber69** [comment]
Closed? Nothing is satisfactory here

Sent from my iPhone

On Apr 26, 2018, at 4:28 AM, makerbase <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #83<https://github.com/makerbase-mks/MKS-TFT/issues/83>.
