### ISSUE TITLE
MKS TFT32 Fails to Boot Properly - White Screen

### ISSUE THREAD

**Issue by matigi** [makerbase-mks/MKS-TFT#86]
I'm having an issue with my TFT32L_V3.0 board running V3.0 firmware, I'm using the screen with MKS sbase V1.3. Most often, when turned on it'll show the booting screen, and then, the screen goes full white, and fails to respond.

If I reboot the screen using the button many times, it will eventually boot properly. Sometimes it will boot properly from the start, I can't find a pattern to the issue. When it's working there are no issues.

I've tried reloading the firmware many times, I can't find a solution. What can I do?

Thanks,

**Comment by makerbase-mks** [comment]
you need to update the firmware of v3.0.1
https://github.com/makerbase-mks/MKS-TFT/tree/master/MKS-TFT2.8-3.2/Firmware
