### ISSUE TITLE
Bug display of Fan setting load

### ISSUE THREAD

**Issue by atolala** [makerbase-mks/MKS-TFT#87]
Hi

they are a bug with Fan % display when you start from 0 and push + button the display stay to 0

the display work is to push 100% or 50% before use + and -

Can you check this please ?

best regards

**Comment by makerbase-mks** [comment]
what is the version of the firmware.

**Comment by atolala** [comment]
Hi

All version from 2 to 3.01 you can try to go to fan menu, 
clic for close fan
and clic + button many time, fan start slowly but diplay show 0 all the time

Thanks for reply
