### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by jhnf** [makerbase-mks/MKS-TFT#9]
Hello! Why is there no support for other languages, such as Russian? I can help with the translation.

**Comment by makerbase-mks** [comment]
other languages can change the pictures icon to support.

**Comment by makerbase-mks** [comment]
Dear Sir,
Greeting! 
 i am writing to if yould do me a favour.
We are creating multi-language for MKS TFT touch screen,one of them is  Russian.
If you help to  translate  in Russian for us.That will be highly appreciated!
Would you please provide me your mail?
Or contact me ,
shelly@makerbase.com.cn

**Comment by caipira69** [comment]
Hello,

Where or how, if possible, to add / translate the mks-ftf firmware into Portuguese?

Thanks in advance,
Best regards
Carlos
