### ISSUE TITLE
Trying to print from SD card, no files found

### ISSUE THREAD

**Issue by HugoW1975** [makerbase-mks/MKS-TFT#90]
Hi,

I have the TFT32, downloaded and installed latest firmware, everything works except for printing from the SD card. I copy the .GCODE file that Cura created onto the card, same card I succesfully used to upgrade the firmware, but it doesn't find files to print. Where should I look next?

BTW, I run it in combination with a MKS SBase V1.3 board, printing from the PC with Pronterface goes well.

Cheers,

Hugo

**Comment by makerbase-mks** [comment]
You should selet the USB in the  interface of set->FileSys
