### ISSUE TITLE
MKS Robin V2.0.3 Turkish language?

### ISSUE THREAD

**Issue by mucitteam** [makerbase-mks/MKS-TFT#91]
That is Emrullah Yolasığmaz from Turkey, We want to produce our 3d printers and we decided about your boards MKS Robin V2.0.3 for using. But we need to language changing. Could you help us about this for Turkish language? If you can sent to us any language changing method we can translate Turkish.

Second question how can I add internal memory out of existing sd card.

**Comment by makerbase-mks** [comment]
You can customize it.
shelly@makerbase.com.cn

**Comment by mucitteam** [comment]
Hi Makerbase 
there is no return to the mail
I wonder if the mail did not reach
