### ISSUE TITLE
MKS TFT 32 firmware update in question 

### ISSUE THREAD

**Issue by seabassattitude** [makerbase-mks/MKS-TFT#92]
I update firmware. Appeared to erase old and update new completely. Only when I power up, it only displays booting, and does nothing else. Is there way to reset or otherwise correct this issue?

**Comment by medicshort87** [comment]
I have the same issue. Anything resolve this?

**Comment by seabassattitude** [comment]
It turns out I had tried to load everything instead of just the version I needed. After selecting the version I wanted (classic, blue, etc), opening and checking the appropriate configuration, then save to a 2GB SD card and loaded. Then everything work perfect. I love this touch screen now, it is a much better interface than stock.
