### ISSUE TITLE
M-OFF button missing

### ISSUE THREAD

**Issue by marcohaddad** [makerbase-mks/MKS-TFT#93]
I have just updated my MKS-TFT32 to firmware 3.0, and decided to stay with the classic style.
I wonder why there is a blank space on the Settings screen, where should be the Motors Off button, and there is not such function in any where else.

**Comment by makerbase-mks** [comment]
the mks_tft32 firmware 3.0 display the M-off button only  on the simple and retro style.You can configure instruction of "M84" in the More button.

**Comment by Jaka57** [comment]
No, I can't get to display M-off button on retro style, instead of this I've got PSU-off icon
Firmware v.3.0.1, MKS TFT v.3.0

**Comment by Jaka57** [comment]
bmp_function1.bin and bmp_function2.bin in blue style are the same but in red style they are as suppose to be.

**Comment by makerbase-mks** [comment]
We've updated it.

**Comment by marcohaddad** [comment]
The update was for the hole thing or just the reds button bmp?
Thanks!

**Comment by makerbase-mks** [comment]
just the pictures.
