### ISSUE TITLE
MKS TFT7.0 - How to set temperature limit higher than 270 degree?

### ISSUE THREAD

**Issue by batory6666** [makerbase-mks/MKS-TFT#96]
I'm changing in_config.txt cfg_max_sprayer_temperature :270°C to  cfg_max_sprayer_temperature:300°C and cfg_max_bed_temperature to 180°C

First time MKS TFT7.0 allows me set bed and sprayer temperature to the maximum. But after reboot MKS TFT7.0 I can't set temperature higher than 270°C and bed higher than 150°C.

**Comment by makerbase-mks** [comment]
Give me your email, I will send you a revised firmware, or wait for our next updated version.

**Comment by batory6666** [comment]
My email: batory6666@aol.co.uk
Ps. Thanks
Best regards
--
Sent from AOL Email App for Android Tuesday, 30 January 2018, 01:50am +00:00 from makerbase  notifications@github.com :

**Comment by batory6666** [comment]
Thanks
Email has been sent to You.
Best Regards

**Comment by makerbase-mks** [comment]
send to this mailbox: 173664774@qq.com
