### ISSUE TITLE
Grbl Compatible Firmware

### ISSUE THREAD

**Issue by DirtyEngineer** [makerbase-mks/MKS-TFT#97]
I have several MKS-TFT's for my 3d printers and I'm really happy with them. I would love to be able to use these boards to control my Grbl based CNC and laser cutter machines.

Can I suggest modifying a version of the MKS-TFT firmware to be Grbl compatible?  There presently isn't a good stand alone controller for Grbl cnc's and the MKS-TFT would fit the bill perfectly.  I think it would be very popular and you would sell a lot of units. 

[https://github.com/gnea/grbl](url)

**Comment by makerbase-mks** [comment]
We'll think about that later.
