### ISSUE TITLE
MKS TFT70 mks_pic  Booting logo & Button pictures

### ISSUE THREAD

**Issue by kimer2002** [makerbase-mks/MKS-TFT#98]
Hi!
Need datasheet for pictures for customization.
width, height, dpp.
And need RETRO themes to view the settings on the main screen/
Thanks!

**Comment by makerbase-mks** [comment]
https://github.com/makerbase-mks/MKS-TFT/blob/master/MKS-TFT7.0/MKS%20TFT7.0%20V1.0%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C.pdf
This is datasheet of the Chinese ,but it have the picture name that you want.

**Comment by makerbase-mks** [comment]
We will release an English datasheet in a short time.
