### ISSUE TITLE
Translations/corrections

### ISSUE THREAD

**Issue by KuroiSabato** [makerbase-mks/MKS-TFT#99]
I do want to translate the menus to italian and German. And also to correct some English errors...
how can I do it?

**Comment by KuroiSabato** [comment]
no support?

**Comment by MS1987** [comment]
Which lcd do you use? 
With TFT28/TFT32 you can ask makerbase to custom design for you.
With TFT24 , you can config through the config file.

**Comment by KuroiSabato** [comment]
for the tft32.
ask for them? Don't think they can write on Italian and German... (not even English... still have "CANCLE" written on some screens...)
Anyway... seems that they are not concerned to answer my question. 

good products, but the technical support leaves to desire...

**Comment by MS1987** [comment]
@KuroiSabato You can provide relative translation for them.

**Comment by makerbase-mks** [comment]
You can provide relative translation for us and custom design the Italian of TFT32.

**Comment by KuroiSabato** [comment]
I need, if possible, a list of all the commands to be translated. can you send me?

**Comment by makerbase-mks** [comment]
Specific requirements and expenses you can contact:：shelly@makerbase.com.cn

**Comment by makerbase-mks** [comment]
you can send the specific requrement to the email : shelly@makerbase.com.cn

**Comment by KuroiSabato** [comment]
ok... will do. thank you

**Comment by KuroiSabato** [comment]
it would be nice, if someone answer the email...

**Comment by makerbase-mks** [comment]
give me your email.

**Comment by makerbase-mks** [comment]
Give me your email to :engineer1@makerbase.com.cn

**Comment by KuroiSabato** [comment]
email sent

**Comment by KuroiSabato** [comment]
got the mail. will translate and send you asap.
thank you!

**Comment by FedericoBroglia** [comment]
Please May i have it too? I'm Italian I need translation for MKStft32 please help me

**Comment by Laleyenda83** [comment]
Can i have the file too then i translate it to danish :)
